// Copyright (c) marcschier. Licensed under the MIT License.
// <auto-generated />
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace OpenUsd.Interop;

internal enum OpenUsdImageEncodeStatus : uint
{
    Ok = 0,
    InvalidInput = 1,
    Unsupported = 2,
    QuotaExceeded = 3,
    Cancelled = 4,
    IoError = 5,
    NativeError = 6,
    OutOfMemory = 7
}

[StructLayout(LayoutKind.Sequential, Pack = 8)]
internal struct OpenUsdImageExrRequest
{
    internal uint StructSize;
    internal uint Version;
    internal uint Flags;
    internal uint PixelFormat;
    internal uint Width;
    internal uint Height;
    internal uint RowOrder;
    internal uint ColorPolicy;
    internal uint AlphaPolicy;
    internal uint WindowPolicy;
    internal int DataOriginX;
    internal int DataOriginY;
    internal int DisplayOriginX;
    internal int DisplayOriginY;
    internal uint DisplayWidth;
    internal uint DisplayHeight;
    internal uint PixelAspectNumerator;
    internal uint PixelAspectDenominator;
    internal ulong PixelCeiling;
    internal ulong OutputByteLimit;
    internal ulong Reserved0;
    internal ulong Reserved1;
    internal ulong Reserved2;
}

[StructLayout(LayoutKind.Sequential, Pack = 8)]
internal struct OpenUsdImageExrResult
{
    internal uint StructSize;
    internal uint Version;
    internal OpenUsdImageEncodeStatus Status;
    internal uint Win32Error;
    internal ulong EncodedBytes;
    internal uint EncodedRows;
    internal uint Reserved0;
    internal ulong Reserved1;
}

public static unsafe partial class OpenUsdNativeRuntime
{
    private static partial class NativeMethods
    {
        [LibraryImport(OpenUsdNativeContract.LibraryName, EntryPoint = "openusd_image_encode_exr_rgba16f_v1")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial uint EncodeExrRgba16Float(
            OpenUsdImageExrRequest* request,
            uint requestBytes,
            byte* rgba16fLe,
            ulong rgba16fBytes,
            ulong borrowedWindowsHandle,
            delegate* unmanaged[Cdecl]<nint, uint, uint, ulong, uint> cancellation,
            nint cancellationContext,
            OpenUsdImageExrResult* result,
            uint resultBytes);
    }
}
