<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>OpenUsd.Runtime.Core.win-x64</PackageId>
    <Description>OpenUSD core native runtime and data plugin resources for Windows x64.</Description>
    <PackageTags>openusd;usd;native;runtime;windows;x64</PackageTags>
    <RuntimePackageKind>Core</RuntimePackageKind>
    <RuntimePackageRid>win-x64</RuntimePackageRid>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeSymbols>false</IncludeSymbols>
    <EnablePackageValidation>false</EnablePackageValidation>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
  </PropertyGroup>

  <Import Project="../OpenUsd.Runtime.Packaging/OpenUsd.Runtime.Packaging.targets" />

</Project>
