// Copyright (c) marcschier. Licensed under the MIT License.

using System.Reflection;
using System.Text.Json;

namespace OpenUsd.Tests;

/// <summary>
/// Gates the managed schema facades against the schema registry the pinned OpenUSD
/// install actually ships.
/// </summary>
/// <remarks>
/// <para>
/// <c>schemas/openUsd/schema-registry.g.json</c> is generated by
/// <c>python eng/generate-schema-coverage.py</c> from the pinned install's
/// <c>plugInfo.json</c> and <c>generatedSchema.usda</c> resources. It is the ground
/// truth: every schema type of the ten domain libraries the public facades claim,
/// and every property each type declares. Inherited properties are attributed once,
/// to the schema that introduces them, so a property is stated exactly once.
/// </para>
/// <para>
/// <c>usdPhysics</c> in that set is the standard schema library OpenUSD ships, which
/// the <c>OpenUsd.Physics</c> facades wrap. It is unrelated to the repository-owned
/// codeless plugin under <c>schemas/openUsdPhysics</c>, which has its own definition,
/// generator and contract tests.
/// </para>
/// <para>
/// <c>schemas/openUsd/managed-coverage.map.json</c> is the reviewed counterpart. A
/// schema is either mapped to the managed types that represent it, or recorded as an
/// explicit exception with a reason. The same holds property by property. These tests
/// join the two and fail when the pinned registry gains a schema or a property that
/// nobody has decided about, when a mapping names a managed type or member that does
/// not exist, and when the reviewed coverage totals regress.
/// </para>
/// <para>
/// Property-level coverage is never inferred from naming. A mapping exists only where
/// a reviewer wrote one, and both ends of it are verified: the property against the
/// pinned registry, the member against the compiled assembly.
/// </para>
/// <para>
/// The tests are pure managed file and reflection inspection: no OpenUSD native
/// runtime is needed. Regenerating the inventory does need the pinned native install,
/// which is why <c>--verify</c> runs in a CI job that stages it.
/// </para>
/// </remarks>
public sealed class OpenUsdSchemaCoverageContractTests
{
    private const int ReviewedCoveredSchemas = 81;
    private const int ReviewedMappedProperties = 205;

    /// <summary>
    /// Members every facade carries as stage plumbing rather than as a schema
    /// property. Mapping a property to one of these would satisfy the gate while
    /// representing nothing, so they are rejected by name.
    /// </summary>
    private static readonly HashSet<string> StructuralMembers =
        ["Path", "Prim", "Stage", "Wrap", "TryWrap", "Apply", "Has"];

    private static readonly BindingFlags MemberLookup =
        BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static |
        BindingFlags.DeclaredOnly;

    [Test]
    public async Task EveryPinnedSchemaHasExactlyOneReviewedCoverageEntry()
    {
        using JsonDocument registry = ReadJson(RegistryPath());
        using JsonDocument map = ReadJson(MapPath());

        HashSet<string> pinned = [.. Schemas(registry).Select(schema => schema.TypeName)];
        HashSet<string> reviewed = [.. Entries(map).Keys];

        await Assert.That(pinned).IsNotEmpty();
        foreach (string typeName in pinned)
        {
            await Assert.That(reviewed.Contains(typeName)).IsTrue()
                .Because($"{typeName} is in the pinned OpenUSD registry but has no entry in "
                    + "schemas/openUsd/managed-coverage.map.json.");
        }

        foreach (string typeName in reviewed)
        {
            await Assert.That(pinned.Contains(typeName)).IsTrue()
                .Because($"{typeName} is mapped but no longer exists in the pinned OpenUSD "
                    + "registry; remove the stale entry.");
        }
    }

    [Test]
    public async Task EveryCoverageEntryIsEitherMappedOrAReviewedException()
    {
        using JsonDocument map = ReadJson(MapPath());
        HashSet<string> reasons = [.. Reasons(map).Keys];

        foreach ((string typeName, JsonElement entry) in Entries(map))
        {
            bool mapped = entry.TryGetProperty("managedTypes", out JsonElement managedTypes);
            bool uncovered = entry.TryGetProperty("uncovered", out JsonElement reason);

            await Assert.That(mapped ^ uncovered).IsTrue()
                .Because($"{typeName} must declare either managedTypes or a single "
                    + "'uncovered' reason, never both and never neither.");

            if (mapped)
            {
                await Assert.That(managedTypes.GetArrayLength()).IsGreaterThan(0)
                    .Because($"{typeName} declares an empty managedTypes list.");
                continue;
            }

            await Assert.That(reasons.Contains(reason.GetString()!)).IsTrue()
                .Because($"{typeName} is uncovered for '{reason.GetString()}', which is not "
                    + "declared in exceptionReasons.");
            await Assert.That(entry.TryGetProperty("properties", out _)).IsFalse()
                .Because($"{typeName} is uncovered, so it must not map properties.");
            await Assert.That(entry.TryGetProperty("propertyExceptions", out _)).IsFalse()
                .Because($"{typeName} is uncovered, so its properties are uncovered with it.");
        }
    }

    [Test]
    public async Task EveryMappedManagedTypeIsPublicInTheOpenUsdAssembly()
    {
        using JsonDocument map = ReadJson(MapPath());
        Assembly assembly = typeof(UsdPrim).Assembly;

        await Assert.That(assembly.GetName().Name)
            .IsEqualTo(map.RootElement.GetProperty("assembly").GetString());

        foreach ((string typeName, JsonElement entry) in Entries(map))
        {
            foreach (string managed in ManagedTypeNames(entry))
            {
                Type? resolved = assembly.GetType(managed, throwOnError: false);
                await Assert.That(resolved).IsNotNull()
                    .Because($"{typeName} maps to '{managed}', which does not exist in the "
                        + "OpenUsd assembly.");
                await Assert.That(resolved!.IsPublic).IsTrue()
                    .Because($"{typeName} maps to '{managed}', which is not public; the "
                        + "coverage claim is about the public surface.");
            }
        }
    }

    [Test]
    public async Task EveryDeclaredPropertyIsMappedOrExplicitlyExcepted()
    {
        using JsonDocument registry = ReadJson(RegistryPath());
        using JsonDocument map = ReadJson(MapPath());
        Dictionary<string, JsonElement> entries = Entries(map);

        foreach ((_, string typeName, _, string[] declared) in Schemas(registry))
        {
            if (!entries.TryGetValue(typeName, out JsonElement entry))
            {
                // Reported by EveryPinnedSchemaHasExactlyOneReviewedCoverageEntry.
                continue;
            }

            if (entry.TryGetProperty("uncovered", out _))
            {
                continue;
            }

            HashSet<string> mapped = [.. Names(entry, "properties")];
            HashSet<string> excepted = [.. Names(entry, "propertyExceptions")];

            await Assert.That(mapped.Intersect(excepted)).IsEmpty()
                .Because($"{typeName} maps and excepts the same property.");

            foreach (string property in declared)
            {
                await Assert.That(mapped.Contains(property) || excepted.Contains(property))
                    .IsTrue()
                    .Because($"{typeName} declares '{property}' in the pinned registry, but "
                        + "the coverage map neither maps it to a managed member nor records "
                        + "it as a reviewed exception.");
            }

            foreach (string property in mapped.Concat(excepted))
            {
                await Assert.That(declared.Contains(property)).IsTrue()
                    .Because($"{typeName} maps '{property}', which the pinned registry does "
                        + "not declare on that schema; remove the stale mapping.");
            }
        }
    }

    [Test]
    public async Task EveryMappedPropertyResolvesToAPublicManagedMember()
    {
        using JsonDocument map = ReadJson(MapPath());
        Assembly assembly = typeof(UsdPrim).Assembly;

        foreach ((string typeName, JsonElement entry) in Entries(map))
        {
            if (!entry.TryGetProperty("properties", out JsonElement properties))
            {
                continue;
            }

            Type[] managed = [.. ManagedTypeNames(entry)
                .Select(name => assembly.GetType(name, throwOnError: false))
                .Where(type => type is not null)
                .Select(type => type!)];

            foreach (JsonProperty property in properties.EnumerateObject())
            {
                string member = property.Value.GetString()!;
                bool resolved = managed.Any(type => RepresentsAProperty(type, member));

                await Assert.That(resolved).IsTrue()
                    .Because($"{typeName}.{property.Name} maps to member '{member}', which "
                        + $"none of [{string.Join(", ", ManagedTypeNames(entry))}] declares "
                        + "as an instance property, method or field of its own.");
            }
        }
    }

    [Test]
    public async Task MemberResolutionRejectsInheritedStaticAndStructuralMembers()
    {
        Type sphere = typeof(Geom.UsdGeomSphere);
        Type mesh = typeof(Geom.UsdGeomMesh);

        await Assert.That(RepresentsAProperty(sphere, "Radius")).IsTrue();
        await Assert.That(RepresentsAProperty(mesh, "GetPoints")).IsTrue();

        // Inherited from object or ValueType: present on every type, represents nothing.
        await Assert.That(RepresentsAProperty(sphere, "ToString")).IsFalse();
        await Assert.That(RepresentsAProperty(sphere, "GetHashCode")).IsFalse();
        await Assert.That(RepresentsAProperty(sphere, "Equals")).IsFalse();
        await Assert.That(RepresentsAProperty(sphere, "GetType")).IsFalse();

        // Stage plumbing and construction helpers: declared, but not a property.
        await Assert.That(RepresentsAProperty(sphere, "Path")).IsFalse();
        await Assert.That(RepresentsAProperty(sphere, "Prim")).IsFalse();
        await Assert.That(RepresentsAProperty(sphere, "Wrap")).IsFalse();
        await Assert.That(RepresentsAProperty(sphere, "TryWrap")).IsFalse();
        await Assert.That(RepresentsAProperty(typeof(Physics.UsdPhysicsMassAPI), "Apply"))
            .IsFalse();
        await Assert.That(RepresentsAProperty(typeof(Physics.UsdPhysicsMassAPI), "Has"))
            .IsFalse();

        // A member of a different facade never satisfies this one.
        await Assert.That(RepresentsAProperty(sphere, "GetPoints")).IsFalse();
        await Assert.That(RepresentsAProperty(sphere, "NoSuchMember")).IsFalse();

        // Extension methods live on a static class, not on the facade they extend.
        await Assert.That(RepresentsAProperty(sphere, "DefineSphere")).IsFalse();
    }

    [Test]
    public async Task ThePhysicsEntriesMapTheStandardLibraryNotTheRepositoryPlugin()
    {
        using JsonDocument registry = ReadJson(RegistryPath());
        using JsonDocument map = ReadJson(MapPath());
        Dictionary<string, JsonElement> entries = Entries(map);

        string[] physics = [.. Schemas(registry)
            .Where(schema => schema.Library == "usdPhysics")
            .Select(schema => schema.TypeName)];

        await Assert.That(physics).Count().IsEqualTo(17)
            .Because("the pinned usdPhysics library declares 17 schema types.");

        foreach (string typeName in physics)
        {
            JsonElement entry = entries[typeName];
            await Assert.That(entry.TryGetProperty("uncovered", out _)).IsFalse()
                .Because($"{typeName} is wrapped by an OpenUsd.Physics facade.");

            foreach (string managed in ManagedTypeNames(entry))
            {
                await Assert.That(managed).StartsWith("OpenUsd.Physics.")
                    .Because($"{typeName} is a standard usdPhysics schema.");
            }
        }

        // The repository-owned codeless plugin is a different surface, generated from
        // schemas/openUsdPhysics and gated by OpenUsdPhysicsSchemaContractTests. Its
        // types must never leak into this map.
        foreach ((string typeName, JsonElement entry) in entries)
        {
            await Assert.That(typeName).DoesNotStartWith("OpenUsdPhysics");
            foreach (string managed in ManagedTypeNames(entry))
            {
                await Assert.That(managed).DoesNotStartWith("OpenUsd.Physics.OpenUsdPhysics");
            }
        }
    }

    [Test]
    public async Task EveryExceptionReasonIsDeclaredAndUsed()
    {
        using JsonDocument map = ReadJson(MapPath());
        Dictionary<string, string> reasons = Reasons(map);
        HashSet<string> used = [];

        foreach ((string typeName, JsonElement entry) in Entries(map))
        {
            if (entry.TryGetProperty("uncovered", out JsonElement uncovered))
            {
                _ = used.Add(uncovered.GetString()!);
            }

            if (!entry.TryGetProperty("propertyExceptions", out JsonElement exceptions))
            {
                continue;
            }

            foreach (JsonProperty exception in exceptions.EnumerateObject())
            {
                string reason = exception.Value.GetString()!;
                await Assert.That(reasons.ContainsKey(reason)).IsTrue()
                    .Because($"{typeName}.{exception.Name} claims reason '{reason}', which is "
                        + "not declared in exceptionReasons.");
                _ = used.Add(reason);
            }
        }

        foreach ((string reason, string text) in reasons)
        {
            await Assert.That(text).IsNotEmpty()
                .Because($"exception reason '{reason}' must say why the gap is accepted.");
            await Assert.That(used.Contains(reason)).IsTrue()
                .Because($"exception reason '{reason}' is unused; drop it so the file keeps "
                    + "stating only live exceptions.");
        }
    }

    [Test]
    public async Task TheInventoryWasGeneratedFromThePinnedOpenUsdRelease()
    {
        using JsonDocument registry = ReadJson(RegistryPath());
        using JsonDocument lockFile = ReadJson(
            Path.Combine(FindRepositoryRoot(), "eng", "openusd.install.lock.json"));

        JsonElement pinned = lockFile.RootElement.GetProperty("openUsd");
        JsonElement generated = registry.RootElement.GetProperty("openUsd");

        await Assert.That(generated.GetProperty("commit").GetString())
            .IsEqualTo(pinned.GetProperty("commit").GetString())
            .Because("the inventory is stale for the pinned OpenUSD commit; rerun "
                + "python eng/generate-schema-coverage.py against the pinned install.");
        await Assert.That(generated.GetProperty("version").GetString())
            .IsEqualTo(pinned.GetProperty("version").GetString());
    }

    [Test]
    public async Task InventoryCountsAgreeWithTheEnumeratedSchemas()
    {
        using JsonDocument registry = ReadJson(RegistryPath());
        JsonElement counts = registry.RootElement.GetProperty("counts");
        (string Library, string TypeName, string Kind, string[] Properties)[] schemas =
            [.. Schemas(registry)];

        await Assert.That(counts.GetProperty("schemas").GetInt32()).IsEqualTo(schemas.Length);
        await Assert.That(counts.GetProperty("ownProperties").GetInt32())
            .IsEqualTo(schemas.Sum(schema => schema.Properties.Length));
        await Assert.That(counts.GetProperty("libraries").GetInt32())
            .IsEqualTo(registry.RootElement.GetProperty("libraries").GetArrayLength());
        await Assert.That(schemas.Select(schema => schema.TypeName).Distinct())
            .Count().IsEqualTo(schemas.Length)
            .Because("a schema type must be inventoried exactly once.");
    }

    [Test]
    public async Task CoverageDoesNotRegressBelowTheReviewedBaseline()
    {
        using JsonDocument registry = ReadJson(RegistryPath());
        using JsonDocument map = ReadJson(MapPath());
        Dictionary<string, JsonElement> entries = Entries(map);

        int coveredSchemas = 0;
        int mappedProperties = 0;
        foreach ((_, string typeName, _, _) in Schemas(registry))
        {
            if (!entries.TryGetValue(typeName, out JsonElement entry) ||
                entry.TryGetProperty("uncovered", out _))
            {
                continue;
            }

            coveredSchemas++;
            mappedProperties += Names(entry, "properties").Count();
        }

        await Assert.That(coveredSchemas).IsGreaterThanOrEqualTo(ReviewedCoveredSchemas)
            .Because("a schema that used to have a managed facade lost it; that is an API "
                + "regression, not an exception to record.");
        await Assert.That(mappedProperties).IsGreaterThanOrEqualTo(ReviewedMappedProperties)
            .Because("a property that used to resolve to a typed facade member no longer "
                + "does; moving it into propertyExceptions hides a regression.");
    }

    /// <summary>
    /// Decides whether <paramref name="member"/> on <paramref name="type"/> can stand
    /// for a schema property.
    /// </summary>
    /// <remarks>
    /// Three things are rejected. Members inherited from <see cref="object"/> or
    /// <see cref="ValueType"/> — <c>ToString</c>, <c>Equals</c>, <c>GetHashCode</c>,
    /// <c>GetType</c> — exist on every type and would let any mapping pass, so the
    /// lookup is <see cref="BindingFlags.DeclaredOnly"/>. Static members are the
    /// facade's construction helpers (<c>Wrap</c>, <c>TryWrap</c>, <c>Apply</c>), never
    /// a property view. And the stage plumbing every facade carries (<c>Path</c>,
    /// <c>Prim</c>) is rejected by name: it is declared and instance, but represents
    /// the prim rather than any property on it.
    /// </remarks>
    private static bool RepresentsAProperty(Type type, string member)
    {
        if (StructuralMembers.Contains(member))
        {
            return false;
        }

        foreach (MemberInfo candidate in type.GetMember(member, MemberLookup))
        {
            bool isStatic = candidate switch
            {
                PropertyInfo property => (property.GetMethod ?? property.SetMethod)!.IsStatic,
                MethodInfo method => method.IsStatic,
                FieldInfo field => field.IsStatic,
                _ => true,
            };

            if (!isStatic)
            {
                return true;
            }
        }

        return false;
    }

    private static IEnumerable<(string Library, string TypeName, string Kind, string[] Properties)>
        Schemas(JsonDocument registry)
    {
        foreach (JsonElement library in registry.RootElement.GetProperty("libraries").EnumerateArray())
        {
            string name = library.GetProperty("name").GetString()!;
            foreach (JsonElement schema in library.GetProperty("schemas").EnumerateArray())
            {
                yield return (
                    name,
                    schema.GetProperty("typeName").GetString()!,
                    schema.GetProperty("schemaKind").GetString()!,
                    [.. schema.GetProperty("properties").EnumerateArray()
                        .Select(property => property.GetProperty("name").GetString()!)]);
            }
        }
    }

    private static Dictionary<string, JsonElement> Entries(JsonDocument map) =>
        map.RootElement.GetProperty("schemas").EnumerateObject()
            .ToDictionary(entry => entry.Name, entry => entry.Value);

    private static Dictionary<string, string> Reasons(JsonDocument map) =>
        map.RootElement.GetProperty("exceptionReasons").EnumerateObject()
            .ToDictionary(entry => entry.Name, entry => entry.Value.GetString()!);

    private static IEnumerable<string> ManagedTypeNames(JsonElement entry) =>
        entry.TryGetProperty("managedTypes", out JsonElement managed)
            ? managed.EnumerateArray().Select(value => value.GetString()!)
            : [];

    private static IEnumerable<string> Names(JsonElement entry, string propertyName) =>
        entry.TryGetProperty(propertyName, out JsonElement value)
            ? value.EnumerateObject().Select(property => property.Name)
            : [];

    private static string RegistryPath() => SchemaRoot("schema-registry.g.json");

    private static string MapPath() => SchemaRoot("managed-coverage.map.json");

    private static string SchemaRoot(string fileName) =>
        Path.Combine(FindRepositoryRoot(), "schemas", "openUsd", fileName);

    private static JsonDocument ReadJson(string path) => JsonDocument.Parse(File.ReadAllText(path));

    private static string FindRepositoryRoot()
    {
        DirectoryInfo? directory = new(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "OpenUsd.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new InvalidOperationException(
            $"Unable to locate the repository root from '{AppContext.BaseDirectory}'.");
    }
}
