// Copyright (c) marcschier. Licensed under the MIT License.

using System.Text.Json;

namespace OpenUsd.Tests;

/// <summary>
/// Guards the generated <c>openUsdPhysics</c> codeless schema artifacts against the
/// single JSON definition they are produced from.
/// </summary>
/// <remarks>
/// <para>
/// Everything under <c>schemas/openUsdPhysics/</c> except
/// <c>openUsdPhysics.schema.json</c> and <c>tools/generate_schema.py</c> is generated
/// by <c>python schemas/openUsdPhysics/tools/generate_schema.py</c>. Nothing forces a
/// contributor to rerun the generator, and a hand edit to a <c>.usda</c> or to
/// <c>plugInfo.json</c> looks perfectly reasonable in review. These tests fail when the
/// generated artifacts and the definition disagree.
/// </para>
/// <para>
/// They also pin the two invariants the rest of the physics work depends on: the plugin
/// stays codeless (no <c>LibraryPath</c>, so a stock OpenUSD runtime can load it without
/// a compiled schema library), and every property lives under the
/// <c>openUsdPhysics:&lt;group&gt;:&lt;name&gt;</c> namespace so that the
/// <c>openUsdPhysics:* &gt; physx* &gt; physics:*</c> precedence rule can be applied by
/// namespace alone.
/// </para>
/// <para>
/// The tests are pure managed file inspection: no OpenUSD native runtime is needed, so
/// they run in the ordinary managed test pass. Registration against a real USD registry
/// is covered separately by
/// <c>tests/OpenUsd.NativeCoverage.Tests/OpenUsdPhysicsSchemaRegistrationTests.cs</c>.
/// </para>
/// </remarks>
public sealed class OpenUsdPhysicsSchemaContractTests
{
    private const string PropertyNamespace = "openUsdPhysics";

    [Test]
    public async Task DefinitionDeclaresACodelessLibraryUnderTheProjectNamespace()
    {
        using JsonDocument definition = ReadJson(DefinitionPath());
        JsonElement library = definition.RootElement.GetProperty("library");

        await Assert.That(library.GetProperty("name").GetString()).IsEqualTo("openUsdPhysics");
        await Assert.That(library.GetProperty("prefix").GetString()).IsEqualTo("OpenUsdPhysics");
        await Assert.That(library.GetProperty("propertyNamespace").GetString()).IsEqualTo(PropertyNamespace);
        await Assert.That(library.GetProperty("codeless").GetBoolean())
            .IsTrue()
            .Because("the plugin must load on a stock OpenUSD runtime with no compiled schema library.");
    }

    [Test]
    public async Task EveryPropertyUsesTheThreePartProjectNamespace()
    {
        using JsonDocument definition = ReadJson(DefinitionPath());

        foreach (JsonElement schemaClass in definition.RootElement.GetProperty("classes").EnumerateArray())
        {
            string className = schemaClass.GetProperty("name").GetString()!;
            foreach (JsonElement property in schemaClass.GetProperty("properties").EnumerateArray())
            {
                string name = property.GetProperty("name").GetString()!;
                string[] parts = name.Split(':');

                await Assert.That(parts.Length).IsEqualTo(3)
                    .Because($"'{name}' on {className} must be openUsdPhysics:<group>:<name>.");
                await Assert.That(parts[0]).IsEqualTo(PropertyNamespace)
                    .Because($"'{name}' on {className} must live in the project namespace.");
                await Assert.That(parts[1]).IsNotEmpty();
                await Assert.That(parts[2]).IsNotEmpty();
            }
        }
    }

    [Test]
    public async Task PlugInfoRegistersExactlyTheDefinedSchemas()
    {
        using JsonDocument definition = ReadJson(DefinitionPath());
        using JsonDocument plugInfo = ReadPlugInfo();

        JsonElement plugin = SinglePlugin(plugInfo);
        JsonElement types = plugin.GetProperty("Info").GetProperty("Types");

        HashSet<string> registered = [.. types.EnumerateObject().Select(property => property.Name)];
        HashSet<string> defined = [];

        foreach (JsonElement schemaClass in definition.RootElement.GetProperty("classes").EnumerateArray())
        {
            string name = schemaClass.GetProperty("name").GetString()!;
            _ = defined.Add(name);

            await Assert.That(registered.Contains(name)).IsTrue()
                .Because($"{name} is defined but missing from plugInfo.json; rerun the generator.");

            JsonElement entry = types.GetProperty(name);
            await Assert.That(entry.GetProperty("schemaIdentifier").GetString()).IsEqualTo(name);
            await Assert.That(entry.GetProperty("schemaKind").GetString())
                .IsEqualTo(schemaClass.GetProperty("kind").GetString());
            await Assert.That(entry.GetProperty("autoGenerated").GetBoolean()).IsTrue();

            string[] bases = [.. entry.GetProperty("bases").EnumerateArray().Select(value => value.GetString()!)];
            await Assert.That(bases).Count().IsEqualTo(1);
            await Assert.That(bases[0]).IsEqualTo(RegisteredBaseName(schemaClass.GetProperty("base").GetString()!))
                .Because($"{name} must register under the C++ name of its declared base.");
        }

        await Assert.That(registered.Except(defined)).IsEmpty()
            .Because("plugInfo.json registers a type that no longer exists in the definition.");
    }

    [Test]
    public async Task PlugInfoDescribesACodelessResourcePlugin()
    {
        using JsonDocument plugInfo = ReadPlugInfo();
        JsonElement plugin = SinglePlugin(plugInfo);

        await Assert.That(plugin.GetProperty("Type").GetString()).IsEqualTo("resource");
        await Assert.That(plugin.GetProperty("Name").GetString()).IsEqualTo("openUsdPhysics");
        await Assert.That(plugin.GetProperty("ResourcePath").GetString()).IsEqualTo("resources");
        await Assert.That(plugin.GetProperty("Root").GetString()).IsEqualTo("..");
        await Assert.That(plugin.TryGetProperty("LibraryPath", out _)).IsFalse()
            .Because("a codeless schema plugin must not point at a compiled library.");
    }

    [Test]
    public async Task GeneratorInputDeclaresSkipCodeGeneration()
    {
        string schema = await File.ReadAllTextAsync(SchemaRoot("schema.usda"));

        await Assert.That(schema).Contains("string libraryName = \"openUsdPhysics\"");
        await Assert.That(schema).Contains("string libraryPrefix = \"OpenUsdPhysics\"");
        await Assert.That(schema).Contains("bool skipCodeGeneration = true");
    }

    [Test]
    public async Task GeneratedSchemaLayerContainsEveryClassAndProperty()
    {
        using JsonDocument definition = ReadJson(DefinitionPath());
        string layer = await File.ReadAllTextAsync(GeneratedPath("generatedSchema.usda"));

        foreach (JsonElement schemaClass in definition.RootElement.GetProperty("classes").EnumerateArray())
        {
            string name = schemaClass.GetProperty("name").GetString()!;
            string kind = schemaClass.GetProperty("kind").GetString()!;
            string declaration = kind == "concreteTyped"
                ? $"class {name} \"{name}\""
                : $"class \"{name}\"";

            await Assert.That(layer).Contains(declaration)
                .Because($"{name} is missing from generatedSchema.usda; rerun the generator.");

            foreach (JsonElement property in schemaClass.GetProperty("properties").EnumerateArray())
            {
                string propertyName = property.GetProperty("name").GetString()!;
                await Assert.That(layer).Contains(propertyName)
                    .Because($"{propertyName} is missing from generatedSchema.usda; rerun the generator.");
            }
        }
    }

    [Test]
    public async Task PrecedenceManifestRanksProjectOpinionsAboveForeignAndStandardOnes()
    {
        using JsonDocument manifest = ReadJson(SchemaRoot("precedence-manifest.json"));
        Dictionary<string, JsonElement> namespaces = manifest.RootElement.GetProperty("namespaces")
            .EnumerateArray()
            .ToDictionary(entry => entry.GetProperty("namespace").GetString()!, entry => entry);
        Dictionary<string, int> ranks = namespaces.ToDictionary(
            pair => pair.Key,
            pair => pair.Value.GetProperty("rank").GetInt32());

        await Assert.That(ranks["openUsdPhysics"]).IsEqualTo(0);
        await Assert.That(ranks["physx"]).IsEqualTo(1);
        await Assert.That(ranks["physics"]).IsEqualTo(2);
        await Assert.That(ranks["openUsdPhysics"] < ranks["physx"]).IsTrue();
        await Assert.That(ranks["physx"] < ranks["physics"]).IsTrue();
        await Assert.That(namespaces["openUsdPhysics"].GetProperty("source").GetString()).IsEqualTo("project");
        await Assert.That(namespaces["physx"].GetProperty("source").GetString()).IsEqualTo("foreign")
            .Because("physx* is an optional foreign raw input; no PhysxSchema definition is vendored.");
    }

    [Test]
    public async Task PrecedenceManifestCoversEveryDefinedPropertyExactlyOnce()
    {
        using JsonDocument definition = ReadJson(DefinitionPath());
        using JsonDocument manifest = ReadJson(SchemaRoot("precedence-manifest.json"));

        List<string> entries = [.. manifest.RootElement.GetProperty("properties").EnumerateArray()
            .Select(entry => entry.GetProperty("property").GetString()!)];

        await Assert.That(entries.Distinct()).Count().IsEqualTo(entries.Count)
            .Because("a property must resolve through exactly one manifest entry.");

        HashSet<string> mapped = [.. entries];
        int definedCount = 0;
        int classCount = 0;

        foreach (JsonElement schemaClass in definition.RootElement.GetProperty("classes").EnumerateArray())
        {
            classCount++;
            foreach (JsonElement property in schemaClass.GetProperty("properties").EnumerateArray())
            {
                definedCount++;
                string name = property.GetProperty("name").GetString()!;
                await Assert.That(mapped.Contains(name)).IsTrue()
                    .Because($"{name} has no precedence manifest entry; rerun the generator.");
            }
        }

        JsonElement counts = manifest.RootElement.GetProperty("counts");
        await Assert.That(counts.GetProperty("schemas").GetInt32()).IsEqualTo(classCount);
        await Assert.That(counts.GetProperty("properties").GetInt32()).IsEqualTo(definedCount);
        await Assert.That(entries.Count).IsEqualTo(definedCount);
    }

    [Test]
    public async Task EveryManifestEntryIsAProjectOwnedOpinion()
    {
        using JsonDocument manifest = ReadJson(SchemaRoot("precedence-manifest.json"));

        foreach (JsonElement entry in manifest.RootElement.GetProperty("properties").EnumerateArray())
        {
            string property = entry.GetProperty("property").GetString()!;
            await Assert.That(entry.GetProperty("source").GetString()).IsEqualTo("project")
                .Because($"{property} is generated from the project definition.");
            await Assert.That(entry.GetProperty("sourceNamespace").GetString()).IsEqualTo(PropertyNamespace);
            await Assert.That(entry.GetProperty("rank").GetInt32()).IsEqualTo(0);
        }
    }

    [Test]
    public async Task DefinitionCoversEveryAgreedPhysicsDomain()
    {
        using JsonDocument definition = ReadJson(DefinitionPath());
        HashSet<string> classes = [.. definition.RootElement.GetProperty("classes").EnumerateArray()
            .Select(schemaClass => schemaClass.GetProperty("name").GetString()!)];

        string[] required =
        [
            "OpenUsdPhysicsCharacterControllerAPI",
            "OpenUsdPhysicsVehicleAPI",
            "OpenUsdPhysicsVehicleWheelAttachmentAPI",
            "OpenUsdPhysicsVehicleWheelAPI",
            "OpenUsdPhysicsVehicleSuspensionAPI",
            "OpenUsdPhysicsVehicleTireAPI",
            "OpenUsdPhysicsVehicleTireFrictionTable",
            "OpenUsdPhysicsVehicleEngineAPI",
            "OpenUsdPhysicsVehicleGearsAPI",
            "OpenUsdPhysicsVehicleAutoGearBoxAPI",
            "OpenUsdPhysicsVehicleClutchAPI",
            "OpenUsdPhysicsVehicleDifferentialAPI",
            "OpenUsdPhysicsVehicleBrakesAPI",
            "OpenUsdPhysicsVehicleSteeringAPI",
            "OpenUsdPhysicsFixedTendon",
            "OpenUsdPhysicsSpatialTendon",
            "OpenUsdPhysicsTendonAttachmentAPI",
            "OpenUsdPhysicsMimicJointAPI",
            "OpenUsdPhysicsParticleSystemAPI",
            "OpenUsdPhysicsParticleSetAPI",
            "OpenUsdPhysicsParticleClothAPI",
            "OpenUsdPhysicsPbdMaterialAPI",
            "OpenUsdPhysicsDiffuseParticlesAPI",
            "OpenUsdPhysicsParticleAnisotropyAPI",
            "OpenUsdPhysicsParticleSmoothingAPI",
            "OpenUsdPhysicsParticleIsosurfaceAPI",
            "OpenUsdPhysicsSurfaceDeformableAPI",
            "OpenUsdPhysicsSurfaceDeformableMaterialAPI",
            "OpenUsdPhysicsVolumeDeformableAPI",
            "OpenUsdPhysicsVolumeDeformableMaterialAPI",
            "OpenUsdPhysicsAttachment",
            "OpenUsdPhysicsAutoAttachmentAPI",
            "OpenUsdPhysicsCollisionFilterSettingsAPI",
            "OpenUsdPhysicsCookedDataAPI",
        ];

        foreach (string name in required)
        {
            await Assert.That(classes.Contains(name)).IsTrue()
                .Because($"{name} is part of the retained physics surface the plugin must cover.");
        }
    }

    [Test]
    public async Task CoverageMatrixStatesEveryDomainAsCoveredOrAsAnExplicitGap()
    {
        using JsonDocument definition = ReadJson(DefinitionPath());
        JsonElement gaps = definition.RootElement.GetProperty("gaps");

        await Assert.That(gaps.GetArrayLength()).IsGreaterThan(0)
            .Because("the plan requires physics domains to be stated, not silently missing.");

        Dictionary<string, bool> coverage = [];
        foreach (JsonElement domain in gaps.EnumerateArray())
        {
            string name = domain.GetProperty("domain").GetString()!;
            await Assert.That(name).IsNotEmpty();
            await Assert.That(domain.GetProperty("reason").GetString()).IsNotEmpty()
                .Because($"'{name}' must say why it is or is not covered.");
            coverage[name] = domain.GetProperty("covered").GetBoolean();
        }

        await Assert.That(coverage["characterControllers"]).IsTrue();
        await Assert.That(coverage["vehicles"]).IsTrue();
        await Assert.That(coverage["articulationTendons"]).IsTrue();
        await Assert.That(coverage["particles"]).IsTrue();
        await Assert.That(coverage["deformables"]).IsTrue();
        await Assert.That(coverage["attachments"]).IsTrue();
        await Assert.That(coverage.Values.Any(covered => !covered)).IsFalse()
            .Because("option B requires every agreed domain to be representable by openUsdPhysics:* schemas.");
    }

    private static JsonElement SinglePlugin(JsonDocument plugInfo)
    {
        JsonElement plugins = plugInfo.RootElement.GetProperty("Plugins");
        return plugins[0];
    }

    /// <summary>
    /// Maps a base class as written in <c>schema.usda</c> to the C++ name
    /// <c>usdGenSchema</c> records in <c>plugInfo.json</c>.
    /// </summary>
    private static string RegisteredBaseName(string declaredBase) => declaredBase switch
    {
        "APISchemaBase" => "UsdAPISchemaBase",
        "Typed" => "UsdTyped",
        _ => declaredBase,
    };

    private static JsonDocument ReadJson(string path) => JsonDocument.Parse(File.ReadAllText(path));

    /// <summary>
    /// Reads <c>plugInfo.json</c>, which OpenUSD allows to carry <c>#</c> comment lines
    /// that are not legal JSON.
    /// </summary>
    private static JsonDocument ReadPlugInfo()
    {
        string body = string.Join(
            '\n',
            File.ReadAllLines(GeneratedPath("plugInfo.json"))
                .Where(line => !line.TrimStart().StartsWith('#')));
        return JsonDocument.Parse(body);
    }

    private static string DefinitionPath() => SchemaRoot("openUsdPhysics.schema.json");

    private static string GeneratedPath(string fileName) =>
        Path.Combine(SchemaRoot("resources"), fileName);

    private static string SchemaRoot(string relativePath) =>
        Path.Combine(FindRepositoryRoot(), "schemas", "openUsdPhysics", relativePath);

    private static string FindRepositoryRoot()
    {
        DirectoryInfo? directory = new(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "OpenUsd.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new InvalidOperationException(
            $"Unable to locate the repository root from '{AppContext.BaseDirectory}'.");
    }
}
