// Copyright (c) marcschier. Licensed under the MIT License.

namespace OpenUsd.Rendering.Silk;

/// <summary>
/// The pick targets one hdSilk ABI v22 mesh record answers with the identity
/// the scene authored.
/// </summary>
/// <remarks>
/// A cleared flag is a refusal rather than missing data. The delegate could not
/// map this record's emitted components onto authored ones, and
/// <see cref="SilkSubprimUnsupportedReason"/> names why. A consumer must refuse
/// the target with that diagnostic instead of returning an emitted index as if
/// it were authored identity: an emitted index names a component the stage does
/// not have, so no round trip could resolve it back.
/// </remarks>
[Flags]
public enum SilkSubprimIdentity
{
    /// <summary>The record answers no subprim target exactly.</summary>
    None = 0,

    /// <summary>
    /// Every emitted triangle names the authored face it was triangulated from.
    /// </summary>
    Face = 1,

    /// <summary>
    /// Every emitted primitive corner names the authored mesh edge it spans, or
    /// names no edge at all when it is a triangulation diagonal.
    /// </summary>
    Edge = 2,

    /// <summary>
    /// Every emitted vertex names the authored point it was emitted from, even
    /// when a face-varying attribute duplicated that point across corners.
    /// </summary>
    Point = 4
}

/// <summary>
/// Why one hdSilk mesh record refuses an exact subprim pick target.
/// </summary>
/// <remarks>
/// The reasons are flags because a single record can refuse edges and points
/// for different causes.
/// </remarks>
[Flags]
public enum SilkSubprimUnsupportedReason
{
    /// <summary>The record refuses nothing.</summary>
    None = 0,

    /// <summary>
    /// The record is a refined subdivision surface. Its emitted vertices and the
    /// edges between them were generated by the refiner and correspond to no
    /// authored component, so there is no authored index to return.
    /// </summary>
    RefinedSubdivision = 1,

    /// <summary>
    /// The emitted topology's components are not authored mesh components: a
    /// point list, a resubdivided line list, or a curve segment list.
    /// </summary>
    TopologyMode = 2,

    /// <summary>
    /// The emitted arrays stopped matching the authored topology the table was
    /// built from.
    /// </summary>
    Geometry = 4,

    /// <summary>
    /// The tables would exceed the ABI's bounded subprim-identity byte budget,
    /// so the record publishes neither rather than one.
    /// </summary>
    Budget = 8
}
