// Copyright (c) marcschier. Licensed under the MIT License.

using System.Reflection;
using System.Text;
using System.Text.Json;

namespace OpenUsd.Rendering.Silk;

/// <summary>
/// Shared deterministic lifetime for native resources referenced by submissions.
/// </summary>
public abstract class SilkGraphicsResourceBase : IDisposable
{
    private readonly object _lifetimeGate = new();
    private int _leaseCount;
    private bool _disposeRequested;
    private bool _nativeReleased;

    /// <inheritdoc/>
    public void Dispose()
    {
        GC.SuppressFinalize(this);
        bool release;
        lock (_lifetimeGate)
        {
            if (_disposeRequested)
            {
                return;
            }
            _disposeRequested = true;
            release = _leaseCount == 0;
            if (release)
            {
                _nativeReleased = true;
            }
        }
        if (release)
        {
            ReleaseNative();
        }
    }

    /// <summary>Acquires a submission or owner lease.</summary>
    protected IDisposable AcquireResourceLease()
    {
        lock (_lifetimeGate)
        {
            ObjectDisposedException.ThrowIf(_disposeRequested, this);
            _leaseCount++;
        }
        return new ResourceLease(this);
    }

    /// <summary>Rejects public operations after disposal was requested.</summary>
    protected void ThrowIfResourceDisposed()
    {
        lock (_lifetimeGate)
        {
            ObjectDisposedException.ThrowIf(_disposeRequested, this);
        }
    }

    /// <summary>Releases the native resource after disposal and all leases.</summary>
    protected abstract void ReleaseNative();

    private void ReleaseLease()
    {
        bool release;
        lock (_lifetimeGate)
        {
            _leaseCount--;
            release = _disposeRequested && _leaseCount == 0 && !_nativeReleased;
            if (release)
            {
                _nativeReleased = true;
            }
        }
        if (release)
        {
            ReleaseNative();
        }
    }

    private sealed class ResourceLease(SilkGraphicsResourceBase resource) : IDisposable
    {
        private SilkGraphicsResourceBase? _resource = resource;

        public void Dispose() =>
            Interlocked.Exchange(ref _resource, null)?.ReleaseLease();
    }
}

/// <summary>Shader stages supported by the first graphics pipeline slice.</summary>
public enum SilkShaderStage
{
    /// <summary>Vertex stage.</summary>
    Vertex,

    /// <summary>Fragment or pixel stage.</summary>
    Fragment,

    /// <summary>Compute stage.</summary>
    Compute
}

/// <summary>Checked native shader binary formats.</summary>
public enum SilkShaderBinaryFormat
{
    /// <summary>DirectX intermediate language.</summary>
    Dxil,

    /// <summary>Standard portable intermediate representation for Vulkan.</summary>
    SpirV,

    /// <summary>Pinned Apple Metal library.</summary>
    MetalLibrary
}

/// <summary>Mesh shader feature bits generated by the checked shader manifest.</summary>
[Flags]
public enum SilkShaderFeatures
{
    /// <summary>No optional mesh shader features.</summary>
    None = 0,

    /// <summary>Texture coordinates are available to the mesh shader.</summary>
    Uv = 1,

    /// <summary>A base-color texture is bound.</summary>
    BaseColorMap = 2,

    /// <summary>A normal texture is bound.</summary>
    NormalMap = 4,

    /// <summary>
    /// A roughness texture is bound. The numeric value and the <c>roughmetal</c>
    /// artifact token are kept for API and artifact stability, but the slot drives
    /// roughness alone: metallic has its own <see cref="MetallicMap"/> bit, and the
    /// two are fully independent. A packed occlusion/roughness/metallic file simply
    /// sets both bits, because it reaches the renderer as two connections naming one
    /// asset and two different UsdUVTexture output channels.
    /// </summary>
    RoughnessMetallicMap = 8,

    /// <summary>An emissive texture is bound.</summary>
    EmissiveMap = 16,

    /// <summary>
    /// A metallic texture is bound. Independent of <see cref="RoughnessMetallicMap"/>
    /// in both directions: a metallic-only material sets this bit alone, and a
    /// roughness-only material never sets it, so neither input can disturb the other.
    /// </summary>
    MetallicMap = 32,

    /// <summary>An opacity texture is bound.</summary>
    OpacityMap = 64,

    /// <summary>An occlusion texture is bound.</summary>
    OcclusionMap = 128,

    /// <summary>A specular-color texture is bound.</summary>
    SpecularColorMap = 256,

    /// <summary>A clearcoat texture is bound.</summary>
    ClearcoatMap = 512,

    /// <summary>A clearcoat-roughness texture is bound.</summary>
    ClearcoatRoughnessMap = 1024,

    /// <summary>An index-of-refraction texture is bound.</summary>
    IorMap = 2048
}

/// <summary>Stable mesh shader permutation identifier.</summary>
public readonly record struct SilkShaderPermutationId
{
    private const SilkShaderFeatures KnownFeatures =
        SilkShaderFeatures.Uv |
        SilkShaderFeatures.BaseColorMap |
        SilkShaderFeatures.NormalMap |
        SilkShaderFeatures.RoughnessMetallicMap |
        SilkShaderFeatures.EmissiveMap |
        SilkShaderFeatures.MetallicMap |
        SilkShaderFeatures.OpacityMap |
        SilkShaderFeatures.OcclusionMap |
        SilkShaderFeatures.SpecularColorMap |
        SilkShaderFeatures.ClearcoatMap |
        SilkShaderFeatures.ClearcoatRoughnessMap |
        SilkShaderFeatures.IorMap;
    private const SilkShaderFeatures MapFeatures =
        SilkShaderFeatures.BaseColorMap |
        SilkShaderFeatures.NormalMap |
        SilkShaderFeatures.RoughnessMetallicMap |
        SilkShaderFeatures.EmissiveMap |
        SilkShaderFeatures.MetallicMap |
        SilkShaderFeatures.OpacityMap |
        SilkShaderFeatures.OcclusionMap |
        SilkShaderFeatures.SpecularColorMap |
        SilkShaderFeatures.ClearcoatMap |
        SilkShaderFeatures.ClearcoatRoughnessMap |
        SilkShaderFeatures.IorMap;

    /// <summary>Initializes a manifest-valid mesh shader permutation.</summary>
    public SilkShaderPermutationId(SilkShaderFeatures features)
    {
        ValidateFeatures(features);
        Features = features;
    }

    /// <summary>Gets the manifest feature bits.</summary>
    public SilkShaderFeatures Features { get; }

    /// <summary>Gets the no-feature mesh permutation.</summary>
    public static SilkShaderPermutationId None => new(SilkShaderFeatures.None);

    /// <summary>Gets the checked mesh vertex artifact stem.</summary>
    public string MeshVertexArtifactName =>
        GetVertexArtifactName();

    /// <summary>Gets the checked mesh fragment artifact stem.</summary>
    public string MeshFragmentArtifactName =>
        GetFragmentArtifactName();

    internal SilkBindingLayoutDescriptor CreateMeshBindingLayout()
    {
        if ((Features & MapFeatures) == 0)
        {
            return SilkBindingLayoutDescriptor.SceneParameters;
        }

        var slots = new List<SilkBindingSlot>();
        if ((Features & MapFeatures) != 0)
        {
            AddTextureSlots(
                slots,
                SilkBindingLayoutDescriptor.BaseColorSamplerBinding,
                SilkBindingLayoutDescriptor.BaseColorTextureBinding);
            AddTextureSlots(
                slots,
                SilkBindingLayoutDescriptor.RoughnessMetallicSamplerBinding,
                SilkBindingLayoutDescriptor.RoughnessMetallicTextureBinding);
            AddTextureSlots(
                slots,
                SilkBindingLayoutDescriptor.MetallicSamplerBinding,
                SilkBindingLayoutDescriptor.MetallicTextureBinding);
            AddTextureSlots(
                slots,
                SilkBindingLayoutDescriptor.EmissiveSamplerBinding,
                SilkBindingLayoutDescriptor.EmissiveTextureBinding);
            AddTextureSlots(
                slots,
                SilkBindingLayoutDescriptor.OpacitySamplerBinding,
                SilkBindingLayoutDescriptor.OpacityTextureBinding);
            AddTextureSlots(
                slots,
                SilkBindingLayoutDescriptor.OcclusionSamplerBinding,
                SilkBindingLayoutDescriptor.OcclusionTextureBinding);
            AddTextureSlots(
                slots,
                SilkBindingLayoutDescriptor.SpecularColorSamplerBinding,
                SilkBindingLayoutDescriptor.SpecularColorTextureBinding);
            AddTextureSlots(
                slots,
                SilkBindingLayoutDescriptor.ClearcoatSamplerBinding,
                SilkBindingLayoutDescriptor.ClearcoatTextureBinding);
            AddTextureSlots(
                slots,
                SilkBindingLayoutDescriptor.ClearcoatRoughnessSamplerBinding,
                SilkBindingLayoutDescriptor.ClearcoatRoughnessTextureBinding);
            AddTextureSlots(
                slots,
                SilkBindingLayoutDescriptor.IorSamplerBinding,
                SilkBindingLayoutDescriptor.IorTextureBinding);
        }
        AddTextureSlots(
            slots,
            SilkShaderFeatures.NormalMap,
            SilkBindingLayoutDescriptor.NormalSamplerBinding,
            SilkBindingLayoutDescriptor.NormalTextureBinding);
        if ((Features & MapFeatures) != 0)
        {
            // The material's single composite image, declared for every
            // MAP_MATERIAL pipeline because the checked binary references it in
            // every one of them; a material that binds no composite leaves the
            // slot at the shared stand-in, exactly as an unbound material map
            // does. Added last on purpose: descriptor offsets follow slot order,
            // so appending keeps every pre-existing offset where it was.
            AddTextureSlots(
                slots,
                SilkBindingLayoutDescriptor.CompositeSamplerBinding,
                SilkBindingLayoutDescriptor.CompositeTextureBinding);
        }
        return SilkBindingLayoutDescriptor.ForMaterial(slots);
    }

    internal SilkShaderPermutationId CanonicalizeForPipeline()
    {
        if ((Features & MapFeatures) == 0)
        {
            return this;
        }

        SilkShaderFeatures canonical =
            SilkShaderFeatures.Uv | SilkShaderFeatures.BaseColorMap;
        if ((Features & SilkShaderFeatures.NormalMap) != 0)
        {
            canonical |= SilkShaderFeatures.NormalMap;
        }
        return new SilkShaderPermutationId(canonical);
    }

    private static void ValidateFeatures(SilkShaderFeatures features)
    {
        if ((features & ~KnownFeatures) != 0)
        {
            throw new ArgumentOutOfRangeException(nameof(features));
        }
        if ((features & MapFeatures) != 0 &&
            (features & SilkShaderFeatures.Uv) == 0)
        {
            throw new ArgumentException(
                "Mesh texture-map shader features require SilkShaderFeatures.Uv.",
                nameof(features));
        }
    }

    private string GetVertexArtifactName()
    {
        const string baseName = "mesh.vertex";
        if ((Features & SilkShaderFeatures.Uv) == 0)
        {
            return baseName;
        }

        var suffix = new StringBuilder();
        AppendToken(suffix, Features, SilkShaderFeatures.Uv, "uv");
        AppendToken(suffix, Features, SilkShaderFeatures.NormalMap, "normal");
        return $"{baseName}.{suffix}";
    }

    private string GetFragmentArtifactName()
    {
        const string baseName = "mesh.fragment";
        if (Features == SilkShaderFeatures.None)
        {
            return baseName;
        }

        var suffix = new StringBuilder("uv");
        if ((Features & MapFeatures) != 0)
        {
            suffix.Append("+material");
        }
        if ((Features & SilkShaderFeatures.NormalMap) != 0)
        {
            suffix.Append("+normal");
        }
        return $"{baseName}.{suffix}";
    }

    private static void AddTextureSlots(
        List<SilkBindingSlot> slots,
        uint samplerBinding,
        uint textureBinding)
    {
        slots.Add(new SilkBindingSlot(
            0,
            samplerBinding,
            SilkBindingKind.Sampler,
            0,
            SilkShaderStageVisibility.Fragment));
        slots.Add(new SilkBindingSlot(
            0,
            textureBinding,
            SilkBindingKind.SampledTexture,
            0,
            SilkShaderStageVisibility.Fragment));
    }

    private void AddTextureSlots(
        List<SilkBindingSlot> slots,
        SilkShaderFeatures feature,
        uint samplerBinding,
        uint textureBinding)
    {
        if ((Features & feature) == 0)
        {
            return;
        }

        AddTextureSlots(slots, samplerBinding, textureBinding);
    }

    private static void AppendToken(
        StringBuilder suffix,
        SilkShaderFeatures features,
        SilkShaderFeatures feature,
        string token)
    {
        if ((features & feature) == 0)
        {
            return;
        }
        if (suffix.Length != 0)
        {
            suffix.Append('+');
        }
        suffix.Append(token);
    }
}

/// <summary>Describes one checked shader module.</summary>
public readonly record struct SilkShaderModuleDescriptor(
    SilkShaderStage Stage,
    SilkShaderBinaryFormat Format,
    string EntryPoint,
    ReadOnlyMemory<byte> Code)
{
    /// <summary>Validates module code and entry point.</summary>
    public void Validate()
    {
        if (!Enum.IsDefined(Stage))
        {
            throw new ArgumentOutOfRangeException(nameof(Stage));
        }
        if (!Enum.IsDefined(Format))
        {
            throw new ArgumentOutOfRangeException(nameof(Format));
        }
        ArgumentException.ThrowIfNullOrWhiteSpace(EntryPoint);
        if (Code.IsEmpty)
        {
            throw new ArgumentException("Shader code cannot be empty.", nameof(Code));
        }
    }
}

/// <summary>Backend shader module.</summary>
public interface ISilkGraphicsShaderModule : IDisposable
{
    /// <summary>Gets the module descriptor.</summary>
    SilkShaderModuleDescriptor Descriptor { get; }
}

/// <summary>Shader visibility for one binding.</summary>
[Flags]
public enum SilkShaderStageVisibility
{
    /// <summary>Vertex stage visibility.</summary>
    Vertex = 1,

    /// <summary>Fragment stage visibility.</summary>
    Fragment = 2,

    /// <summary>Compute stage visibility.</summary>
    Compute = 4
}

/// <summary>The kind of resource occupying one binding slot.</summary>
public enum SilkBindingKind
{
    /// <summary>A uniform (constant) buffer.</summary>
    UniformBuffer = 0,

    /// <summary>A texture read through a sampler.</summary>
    SampledTexture = 1,

    /// <summary>A sampler.</summary>
    Sampler = 2,

    /// <summary>A read-only structured/storage buffer.</summary>
    StorageBuffer = 3
}

/// <summary>
/// One slot in a material binding layout.
/// </summary>
public readonly record struct SilkBindingSlot(
    uint Set,
    uint Binding,
    SilkBindingKind Kind,
    uint UniformByteSize,
    SilkShaderStageVisibility Visibility)
{
    /// <summary>Validates one slot in isolation.</summary>
    public void Validate()
    {
        if (Kind is not (SilkBindingKind.UniformBuffer or
            SilkBindingKind.SampledTexture or SilkBindingKind.Sampler or
            SilkBindingKind.StorageBuffer))
        {
            throw new ArgumentOutOfRangeException(
                nameof(Kind),
                "A binding slot kind must be uniform buffer, storage buffer, sampled texture, or sampler.");
        }
        if (Kind == SilkBindingKind.UniformBuffer)
        {
            if (UniformByteSize == 0 || (UniformByteSize % 16) != 0)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(UniformByteSize),
                    "A uniform buffer slot must be a non-zero multiple of 16 bytes.");
            }
        }
        else if (UniformByteSize != 0)
        {
            throw new ArgumentException(
                "Only a uniform buffer slot carries a byte size.",
                nameof(UniformByteSize));
        }
        if (Visibility == 0)
        {
            throw new ArgumentException(
                "A binding slot must be visible to at least one stage.",
                nameof(Visibility));
        }
    }
}

/// <summary>Reflected SceneParameters binding layout.</summary>
public readonly record struct SilkBindingLayoutDescriptor(
    uint Set,
    uint Binding,
    uint UniformByteSize,
    SilkShaderStageVisibility Visibility)
{
    /// <summary>
    /// Gets the additional material, instance, and frame-resource slots.
    /// </summary>
    /// <remarks>
    /// Additive on purpose. The renderer-neutral device interface is implemented by
    /// three backends and several test doubles, so widening the layout through this
    /// descriptor keeps every existing implementation and caller compiling unchanged
    /// while letting a material layout be described at all, which the single
    /// SceneParameters slot could not express.
    /// </remarks>
    public IReadOnlyList<SilkBindingSlot> MaterialSlots { get; init; } = [];

    /// <summary>The binding slot carrying the surface constants and the light.</summary>
    public const uint SurfaceParametersBinding = 7;

    /// <summary>The binding slot carrying per-frame projection and clip-plane data.</summary>
    public const uint FrameParametersBinding = 8;

    /// <summary>The sampler used by sampled density volumes.</summary>
    internal const uint VolumeSamplerBinding = 13;

    internal const uint BaseColorSamplerBinding = 1;
    internal const uint NormalSamplerBinding = 10;
    internal const uint RoughnessMetallicSamplerBinding = 11;
    internal const uint EmissiveSamplerBinding = 12;
    internal const uint BaseColorTextureBinding = 2;
    internal const uint NormalTextureBinding = 3;
    internal const uint RoughnessMetallicTextureBinding = 4;
    internal const uint EmissiveTextureBinding = 5;

    /// <summary>
    /// The sampler for the metallic texture. Metallic has its own slot rather than
    /// sharing the roughness slot, so a metallic-only material binds nothing to
    /// roughness and vice versa.
    /// </summary>
    internal const uint MetallicSamplerBinding = 14;

    /// <summary>The metallic texture. See <see cref="MetallicSamplerBinding"/>.</summary>
    internal const uint MetallicTextureBinding = 15;
    internal const uint OpacitySamplerBinding = 16;
    internal const uint OpacityTextureBinding = 17;
    internal const uint OcclusionSamplerBinding = 18;
    internal const uint OcclusionTextureBinding = 19;
    internal const uint SpecularColorSamplerBinding = 20;
    internal const uint SpecularColorTextureBinding = 21;
    internal const uint ClearcoatSamplerBinding = 22;
    internal const uint ClearcoatTextureBinding = 23;
    internal const uint ClearcoatRoughnessSamplerBinding = 24;
    internal const uint ClearcoatRoughnessTextureBinding = 25;
    internal const uint IorSamplerBinding = 26;
    internal const uint IorTextureBinding = 27;

    /// <summary>
    /// The sampler for the material's single composite image.
    /// </summary>
    /// <remarks>
    /// One universal slot, not one per material parameter: a per-parameter
    /// composite would need eleven more sampler/texture pairs, and every mesh
    /// pipeline would have to declare them. Which parameter it drives is a
    /// runtime value in the surface constants, so it adds no shader permutation.
    /// </remarks>
    internal const uint CompositeSamplerBinding = 28;

    /// <summary>The material's single composite image. See <see cref="CompositeSamplerBinding"/>.</summary>
    internal const uint CompositeTextureBinding = 29;

    /// <summary>The sampled 3D density texture used by volumes.</summary>
    internal const uint VolumeDensityTextureBinding = 9;

    private static IReadOnlyList<SilkBindingSlot> SharedMeshSlots =>
    [
        new(
            0,
            6,
            SilkBindingKind.StorageBuffer,
            0,
            SilkShaderStageVisibility.Vertex),
        new(
            0,
            SurfaceParametersBinding,
            SilkBindingKind.StorageBuffer,
            0,
            SilkShaderStageVisibility.Fragment),
        new(
            0,
            FrameParametersBinding,
            SilkBindingKind.StorageBuffer,
            0,
            SilkShaderStageVisibility.Vertex | SilkShaderStageVisibility.Fragment)
    ];

    private static SilkBindingSlot VolumeDensityTextureSlot => new(
        0,
        VolumeDensityTextureBinding,
        SilkBindingKind.SampledTexture,
        0,
        SilkShaderStageVisibility.Fragment);

    /// <summary>Creates the checked mesh SceneParameters layout.</summary>
    public static SilkBindingLayoutDescriptor SceneParameters => new(
        0,
        0,
        SilkCheckedShaderAssets.SceneParameters.ByteSize,
        SilkShaderStageVisibility.Vertex | SilkShaderStageVisibility.Fragment)
    {
        MaterialSlots =
        [
            .. SharedMeshSlots
        ]
    };

    internal static SilkBindingLayoutDescriptor SampledVolumeParameters => SceneParameters with
    {
        MaterialSlots =
        [
            .. SharedMeshSlots,
            new(
                0,
                VolumeSamplerBinding,
                SilkBindingKind.Sampler,
                0,
                SilkShaderStageVisibility.Fragment),
            VolumeDensityTextureSlot
        ]
    };

    internal static (uint Sampler, uint Texture) GetMaterialTextureBindings(
        SilkMaterialParameter parameter) =>
        parameter switch
        {
            SilkMaterialParameter.DiffuseColor =>
                (BaseColorSamplerBinding, BaseColorTextureBinding),
            SilkMaterialParameter.Normal =>
                (NormalSamplerBinding, NormalTextureBinding),
            SilkMaterialParameter.Roughness =>
                (RoughnessMetallicSamplerBinding, RoughnessMetallicTextureBinding),
            SilkMaterialParameter.Metallic =>
                (MetallicSamplerBinding, MetallicTextureBinding),
            SilkMaterialParameter.EmissiveColor =>
                (EmissiveSamplerBinding, EmissiveTextureBinding),
            SilkMaterialParameter.Opacity =>
                (OpacitySamplerBinding, OpacityTextureBinding),
            SilkMaterialParameter.Occlusion =>
                (OcclusionSamplerBinding, OcclusionTextureBinding),
            SilkMaterialParameter.SpecularColor =>
                (SpecularColorSamplerBinding, SpecularColorTextureBinding),
            SilkMaterialParameter.Clearcoat =>
                (ClearcoatSamplerBinding, ClearcoatTextureBinding),
            SilkMaterialParameter.ClearcoatRoughness =>
                (ClearcoatRoughnessSamplerBinding, ClearcoatRoughnessTextureBinding),
            SilkMaterialParameter.Ior =>
                (IorSamplerBinding, IorTextureBinding),
            _ => throw new ArgumentOutOfRangeException(
                nameof(parameter),
                parameter,
                "The material parameter does not have a 2D shader texture slot.")
        };

    /// <summary>Creates a material layout from its slots.</summary>
    public static SilkBindingLayoutDescriptor ForMaterial(
        IReadOnlyList<SilkBindingSlot> slots)
    {
        ArgumentNullException.ThrowIfNull(slots);
        if (slots.Count == 0)
        {
            throw new ArgumentException(
                "A material binding layout requires at least one slot.",
                nameof(slots));
        }
        // Slot 0 stays the SceneParameters uniform so a material pipeline keeps the
        // same scene constants at the same place as every existing pipeline. The
        // checked mesh shaders also always declare the instance buffer and the
        // surface constants, so both are carried into every material layout.
        IReadOnlyList<SilkBindingSlot> shared = SharedMeshSlots;
        var materialSlots = new SilkBindingSlot[slots.Count + shared.Count];
        for (int index = 0; index < shared.Count; index++)
        {
            materialSlots[index] = shared[index];
        }
        for (int index = 0; index < slots.Count; index++)
        {
            materialSlots[index + shared.Count] = slots[index];
        }
        return SceneParameters with { MaterialSlots = materialSlots };
    }

    /// <summary>Validates the layout.</summary>
    public void Validate()
    {
        if (Set != 0 || Binding != 0)
        {
            throw new ArgumentException("SceneParameters must use set 0, binding 0.");
        }
        if (UniformByteSize != 80)
        {
            throw new ArgumentOutOfRangeException(
                nameof(UniformByteSize),
                "SceneParameters must contain exactly 80 bytes.");
        }
        if (Visibility !=
            (SilkShaderStageVisibility.Vertex | SilkShaderStageVisibility.Fragment))
        {
            throw new ArgumentException(
                "SceneParameters must be visible to vertex and fragment stages.",
                nameof(Visibility));
        }
        IReadOnlyList<SilkBindingSlot> slots = MaterialSlots ?? [];
        for (int index = 0; index < slots.Count; index++)
        {
            SilkBindingSlot slot = slots[index];
            slot.Validate();
            if (slot.Set != 0)
            {
                // Every backend binds exactly one set today: Vulkan binds set 0, and
                // D3D12 and Metal have no set concept at all. Accepting a second set
                // would describe a binding no backend could ever reach.
                throw new ArgumentException(
                    "A material slot must use set 0, the only set the backends bind.");
            }
            if (slot.Set == 0 && slot.Binding == 0)
            {
                throw new ArgumentException(
                    "A material slot cannot occupy set 0, binding 0, which is SceneParameters.");
            }
            for (int other = 0; other < index; other++)
            {
                if (slots[other].Set == slot.Set && slots[other].Binding == slot.Binding)
                {
                    throw new ArgumentException(
                        $"Material slots collide at set {slot.Set}, binding {slot.Binding}.");
                }
            }
        }
    }

    /// <summary>
    /// Requires that a material slot of <paramref name="kind"/> exists at the given
    /// set and binding, and returns its index within
    /// <see cref="MaterialSlots"/>.
    /// </summary>
    /// <remarks>
    /// Every backend binds resources through this one check, so a slot mismatch fails
    /// identically everywhere instead of surfacing as a different backend-specific
    /// validation error, or worse, as a silently unbound resource.
    /// </remarks>
    /// <exception cref="InvalidOperationException">
    /// No slot of that kind is declared at that set and binding.
    /// </exception>
    public int RequireMaterialSlot(uint set, uint binding, SilkBindingKind kind)
    {
        IReadOnlyList<SilkBindingSlot> slots = MaterialSlots ?? [];
        for (int index = 0; index < slots.Count; index++)
        {
            SilkBindingSlot slot = slots[index];
            if (slot.Set == set && slot.Binding == binding)
            {
                if (slot.Kind != kind)
                {
                    throw new InvalidOperationException(
                        $"Set {set}, binding {binding} is a {slot.Kind} slot, not a {kind} slot.");
                }
                return index;
            }
        }
        throw new InvalidOperationException(
            $"The bound pipeline declares no material slot at set {set}, binding {binding}.");
    }
}

/// <summary>Backend resource binding layout.</summary>
public interface ISilkGraphicsBindingLayout : IDisposable
{
    /// <summary>Gets the reflected descriptor.</summary>
    SilkBindingLayoutDescriptor Descriptor { get; }
}

/// <summary>Describes linked checked shader modules.</summary>
public readonly record struct SilkShaderProgramDescriptor(
    ISilkGraphicsShaderModule VertexShader,
    ISilkGraphicsShaderModule FragmentShader,
    ISilkGraphicsBindingLayout BindingLayout);

/// <summary>Linked shader program.</summary>
public interface ISilkGraphicsShaderProgram : IDisposable
{
    /// <summary>Gets the binding layout.</summary>
    ISilkGraphicsBindingLayout BindingLayout { get; }
}

/// <summary>Vertex semantics supported by the checked mesh shader.</summary>
public enum SilkVertexSemantic
{
    /// <summary>Object-space position.</summary>
    Position,

    /// <summary>Object-space normal.</summary>
    Normal,

    /// <summary>Texture coordinate.</summary>
    TexCoord,

    /// <summary>Object-space tangent and bitangent sign.</summary>
    Tangent
}

/// <summary>Vertex element formats.</summary>
public enum SilkVertexFormat
{
    /// <summary>Three contiguous 32-bit floating-point values.</summary>
    Float3 = 0,

    /// <summary>Two contiguous 32-bit floating-point values.</summary>
    Float2 = 1,

    /// <summary>Four contiguous 32-bit floating-point values.</summary>
    Float4 = 2
}

/// <summary>Describes one vertex attribute.</summary>
public readonly record struct SilkVertexAttributeDescriptor(
    SilkVertexSemantic Semantic,
    uint Location,
    uint Offset,
    SilkVertexFormat Format);

/// <summary>Describes an interleaved vertex buffer.</summary>
public readonly record struct SilkVertexLayoutDescriptor(
    uint Stride,
    IReadOnlyList<SilkVertexAttributeDescriptor> Attributes)
{
    /// <summary>Gets the checked POSITION/NORMAL layout.</summary>
    public static SilkVertexLayoutDescriptor PositionNormal => new(
        24,
        [
            new(SilkVertexSemantic.Position, 0, 0, SilkVertexFormat.Float3),
            new(SilkVertexSemantic.Normal, 1, 12, SilkVertexFormat.Float3)
        ]);

    /// <summary>Gets the checked POSITION/NORMAL/TEXCOORD layout.</summary>
    internal static SilkVertexLayoutDescriptor PositionNormalTexCoord => new(
        32,
        [
            new(SilkVertexSemantic.Position, 0, 0, SilkVertexFormat.Float3),
            new(SilkVertexSemantic.Normal, 1, 12, SilkVertexFormat.Float3),
            new(SilkVertexSemantic.TexCoord, 2, 24, SilkVertexFormat.Float2)
        ]);

    /// <summary>Gets the checked POSITION/NORMAL/TEXCOORD/TANGENT layout.</summary>
    internal static SilkVertexLayoutDescriptor PositionNormalTexCoordTangent => new(
        48,
        [
            new(SilkVertexSemantic.Position, 0, 0, SilkVertexFormat.Float3),
            new(SilkVertexSemantic.Normal, 1, 12, SilkVertexFormat.Float3),
            new(SilkVertexSemantic.TexCoord, 2, 24, SilkVertexFormat.Float2),
            new(SilkVertexSemantic.Tangent, 3, 32, SilkVertexFormat.Float4)
        ]);

    /// <summary>Validates the checked mesh vertex layout.</summary>
    public void Validate()
    {
        ArgumentNullException.ThrowIfNull(Attributes);
        if (!Matches(PositionNormal) &&
            !Matches(PositionNormalTexCoord) &&
            !Matches(PositionNormalTexCoordTangent))
        {
            throw new ArgumentException(
                "The checked mesh shader requires a known position/normal layout, optionally with UV and tangent.",
                nameof(Attributes));
        }
    }

    private bool Matches(SilkVertexLayoutDescriptor expected)
    {
        if (Stride != expected.Stride || Attributes.Count != expected.Attributes.Count)
        {
            return false;
        }
        for (int index = 0; index < Attributes.Count; index++)
        {
            if (Attributes[index] != expected.Attributes[index])
            {
                return false;
            }
        }
        return true;
    }
}

/// <summary>Face-culling mode supported by Silk mesh pipelines.</summary>
/// <remarks>
/// Every backend rasterizes with counter-clockwise front faces, and hdSilk
/// normalises an authored <c>leftHanded</c> orientation into that convention
/// before the page, so "front" and "back" mean the same thing on all of them.
/// </remarks>
public enum SilkCullMode
{
    /// <summary>Rasterizes front- and back-facing triangles.</summary>
    None = 0,

    /// <summary>Culls back-facing triangles.</summary>
    Back = 1,

    /// <summary>Culls front-facing triangles.</summary>
    Front = 2
}

/// <summary>Color blending mode for a Silk graphics pipeline.</summary>
public enum SilkBlendMode
{
    /// <summary>Replaces the destination color.</summary>
    None = 0,

    /// <summary>Composites straight-alpha source color over the destination.</summary>
    StraightAlphaOver = 1
}

/// <summary>Describes a color/depth graphics pipeline.</summary>
public readonly record struct SilkGraphicsPipelineDescriptor(
    ISilkGraphicsShaderProgram Program,
    SilkVertexLayoutDescriptor VertexLayout,
    SilkTextureFormat ColorFormat,
    SilkTextureFormat DepthFormat,
    SilkCullMode CullMode = SilkCullMode.None,
    SilkTopologyKind TopologyKind = SilkTopologyKind.TriangleList)
{
    /// <summary>Gets or initializes color blending.</summary>
    public SilkBlendMode BlendMode { get; init; }

    /// <summary>Gets or initializes whether fragments update depth.</summary>
    public bool DepthWriteEnabled { get; init; } = true;

    /// <summary>Validates formats and vertex input.</summary>
    public void Validate()
    {
        ArgumentNullException.ThrowIfNull(Program);
        VertexLayout.Validate();
        if (!SilkTextureFormats.IsColorRenderTarget(ColorFormat))
        {
            throw new ArgumentException(
                "The color format must be Rgba8Unorm, Rgba16Float, or Rgba32Float.");
        }
        if (DepthFormat != SilkTextureFormat.D32Float)
        {
            throw new ArgumentException("The depth format must be D32Float.");
        }
        if (CullMode is not (SilkCullMode.None or SilkCullMode.Back or SilkCullMode.Front))
        {
            throw new ArgumentOutOfRangeException(nameof(CullMode));
        }
        if (BlendMode is not (SilkBlendMode.None or SilkBlendMode.StraightAlphaOver))
        {
            throw new ArgumentOutOfRangeException(nameof(BlendMode));
        }
        if (TopologyKind is not SilkTopologyKind.TriangleList and
            not SilkTopologyKind.LineList and
            not SilkTopologyKind.PointList)
        {
            throw new ArgumentException("The topology kind is unsupported.");
        }
    }
}

/// <summary>Backend graphics pipeline.</summary>
public interface ISilkGraphicsPipeline : IDisposable
{
    /// <summary>Gets the pipeline descriptor.</summary>
    SilkGraphicsPipelineDescriptor Descriptor { get; }
}

/// <summary>Lease wrapper for a cached graphics pipeline.</summary>
public interface ISilkGraphicsPipelineLease : ISilkGraphicsPipeline
{
    /// <summary>Gets the backend pipeline kept alive by this lease.</summary>
    ISilkGraphicsPipeline Pipeline { get; }
}

/// <summary>Thread-safe checked mesh graphics pipeline cache for one Silk device.</summary>
public sealed class SilkGraphicsPipelineCache : IDisposable
{
    private readonly object _gate = new();
    private readonly ISilkGraphicsDevice _device;
    private readonly SilkShaderBinaryFormat _shaderFormat;
    private readonly Dictionary<PipelineCacheKey, CachedPipelineEntry> _entries = [];
    private DeviceGenerationKey _generation;
    private bool _disposed;

    /// <summary>Initializes a cache for one graphics device and shader binary format.</summary>
    public SilkGraphicsPipelineCache(
        ISilkGraphicsDevice device,
        SilkShaderBinaryFormat shaderFormat)
    {
        ArgumentNullException.ThrowIfNull(device);
        if (!Enum.IsDefined(shaderFormat))
        {
            throw new ArgumentOutOfRangeException(nameof(shaderFormat));
        }

        _device = device;
        _shaderFormat = shaderFormat;
        _generation = ReadDeviceGeneration(device);
    }

    /// <summary>Gets or creates a shared checked mesh pipeline.</summary>
    public ISilkGraphicsPipeline GetOrCreateMeshPipeline(
        SilkShaderPermutationId permutation,
        SilkVertexLayoutDescriptor vertexLayout,
        SilkTextureFormat colorFormat,
        SilkTextureFormat depthFormat,
        SilkCullMode cullMode = SilkCullMode.None,
        SilkTopologyKind topologyKind = SilkTopologyKind.TriangleList) =>
        GetOrCreateMeshPipelineWithState(
            permutation,
            vertexLayout,
            colorFormat,
            depthFormat,
            cullMode,
            topologyKind,
            SilkBlendMode.None,
            depthWriteEnabled: true);

    internal ISilkGraphicsPipeline GetOrCreateMeshPipelineWithState(
        SilkShaderPermutationId permutation,
        SilkVertexLayoutDescriptor vertexLayout,
        SilkTextureFormat colorFormat,
        SilkTextureFormat depthFormat,
        SilkCullMode cullMode,
        SilkTopologyKind topologyKind,
        SilkBlendMode blendMode,
        bool depthWriteEnabled)
    {
        DeviceGenerationKey generation = ReadDeviceGeneration(_device);
        SilkShaderPermutationId canonical = permutation.CanonicalizeForPipeline();
        PipelineCacheKey key = new(
            canonical,
            CreateVertexLayoutKey(vertexLayout),
            colorFormat,
            depthFormat,
            cullMode,
            topologyKind,
            blendMode,
            depthWriteEnabled,
            _shaderFormat,
            generation);

        lock (_gate)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            if (generation != _generation)
            {
                DisposeEntries();
                _generation = generation;
            }

            if (!_entries.TryGetValue(key, out CachedPipelineEntry? entry))
            {
                entry = CreateEntry(
                    canonical,
                    canonical.CreateMeshBindingLayout(),
                    vertexLayout,
                    colorFormat,
                    depthFormat,
                    cullMode,
                    topologyKind,
                    blendMode,
                    depthWriteEnabled);
                _entries.Add(key, entry);
            }

            return entry.AcquireLease();
        }
    }

    internal ISilkGraphicsPipeline GetOrCreateSampledVolumePipeline(
        SilkVertexLayoutDescriptor vertexLayout,
        SilkTextureFormat colorFormat,
        SilkTextureFormat depthFormat,
        SilkCullMode cullMode = SilkCullMode.None,
        SilkTopologyKind topologyKind = SilkTopologyKind.TriangleList,
        SilkBlendMode blendMode = SilkBlendMode.None,
        bool depthWriteEnabled = true)
    {
        DeviceGenerationKey generation = ReadDeviceGeneration(_device);
        PipelineCacheKey key = new(
            "sampled-volume-density",
            CreateVertexLayoutKey(vertexLayout),
            colorFormat,
            depthFormat,
            cullMode,
            topologyKind,
            blendMode,
            depthWriteEnabled,
            _shaderFormat,
            generation);

        lock (_gate)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            if (generation != _generation)
            {
                DisposeEntries();
                _generation = generation;
            }

            if (!_entries.TryGetValue(key, out CachedPipelineEntry? entry))
            {
                entry = CreateEntry(
                    SilkShaderPermutationId.None,
                    SilkBindingLayoutDescriptor.SampledVolumeParameters,
                    vertexLayout,
                    colorFormat,
                    depthFormat,
                    cullMode,
                    topologyKind,
                    blendMode,
                    depthWriteEnabled,
                    sampledVolumeFragment: true);
                _entries.Add(key, entry);
            }

            return entry.AcquireLease();
        }
    }

    /// <summary>Gets or creates a runtime material pipeline from compiled shader descriptors.</summary>
    internal ISilkGraphicsPipeline GetOrCreateMaterialPipeline(
        SilkMaterialShaderProgram materialProgram,
        SilkVertexLayoutDescriptor vertexLayout,
        SilkTextureFormat colorFormat,
        SilkTextureFormat depthFormat,
        SilkCullMode cullMode = SilkCullMode.None,
        SilkTopologyKind topologyKind = SilkTopologyKind.TriangleList,
        SilkBlendMode blendMode = SilkBlendMode.None,
        bool depthWriteEnabled = true)
    {
        materialProgram.Validate();
        DeviceGenerationKey generation = ReadDeviceGeneration(_device);
        PipelineCacheKey key = new(
            materialProgram.CacheHash,
            CreateVertexLayoutKey(vertexLayout),
            colorFormat,
            depthFormat,
            cullMode,
            topologyKind,
            blendMode,
            depthWriteEnabled,
            _shaderFormat,
            generation);

        lock (_gate)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            if (generation != _generation)
            {
                DisposeEntries();
                _generation = generation;
            }

            if (!_entries.TryGetValue(key, out CachedPipelineEntry? entry))
            {
                entry = CreateEntry(
                    materialProgram,
                    vertexLayout,
                    colorFormat,
                    depthFormat,
                    cullMode,
                    topologyKind,
                    blendMode,
                    depthWriteEnabled);
                _entries.Add(key, entry);
            }

            return entry.AcquireLease();
        }
    }

    /// <inheritdoc/>
    public void Dispose()
    {
        lock (_gate)
        {
            if (_disposed)
            {
                return;
            }

            _disposed = true;
            DisposeEntries();
        }
    }

    private CachedPipelineEntry CreateEntry(
        SilkShaderPermutationId permutation,
        SilkBindingLayoutDescriptor bindingLayoutDescriptor,
        SilkVertexLayoutDescriptor vertexLayout,
        SilkTextureFormat colorFormat,
        SilkTextureFormat depthFormat,
        SilkCullMode cullMode,
        SilkTopologyKind topologyKind,
        SilkBlendMode blendMode,
        bool depthWriteEnabled,
        bool sampledVolumeFragment = false)
    {
        ISilkGraphicsShaderModule? vertexShader = null;
        ISilkGraphicsShaderModule? fragmentShader = null;
        ISilkGraphicsBindingLayout? bindingLayout = null;
        ISilkGraphicsShaderProgram? program = null;
        ISilkGraphicsPipeline? pipeline = null;
        try
        {
            vertexShader = _device.CreateShaderModule(
                SilkCheckedShaderAssets.LoadMeshVertex(_shaderFormat, permutation));
            // The sampled density volume is its own checked fragment program rather
            // than a switch inside the shared mesh permutation. A backend root
            // signature or pipeline layout must declare every resource its shader
            // binary references, so a volume texture compiled into the shared
            // fragment binary would have to be declared by every ordinary mesh
            // pipeline that never samples a volume -- which D3D12 rejects outright.
            fragmentShader = _device.CreateShaderModule(
                sampledVolumeFragment
                    ? SilkCheckedShaderAssets.LoadMeshVolumeFragment(_shaderFormat)
                    : SilkCheckedShaderAssets.LoadMeshFragment(_shaderFormat, permutation));
            bindingLayout = _device.CreateBindingLayout(bindingLayoutDescriptor);
            program = _device.CreateShaderProgram(new SilkShaderProgramDescriptor(
                vertexShader,
                fragmentShader,
                bindingLayout));
            pipeline = _device.CreateGraphicsPipeline(new SilkGraphicsPipelineDescriptor(
                program,
                vertexLayout,
                colorFormat,
                depthFormat,
                cullMode,
                topologyKind)
            {
                BlendMode = blendMode,
                DepthWriteEnabled = depthWriteEnabled,
            });
            return new CachedPipelineEntry(
                vertexShader,
                fragmentShader,
                bindingLayout,
                program,
                pipeline);
        }
        catch
        {
            pipeline?.Dispose();
            program?.Dispose();
            bindingLayout?.Dispose();
            fragmentShader?.Dispose();
            vertexShader?.Dispose();
            throw;
        }
    }

    private CachedPipelineEntry CreateEntry(
        SilkMaterialShaderProgram materialProgram,
        SilkVertexLayoutDescriptor vertexLayout,
        SilkTextureFormat colorFormat,
        SilkTextureFormat depthFormat,
        SilkCullMode cullMode,
        SilkTopologyKind topologyKind,
        SilkBlendMode blendMode,
        bool depthWriteEnabled)
    {
        ISilkGraphicsShaderModule? vertexShader = null;
        ISilkGraphicsShaderModule? fragmentShader = null;
        ISilkGraphicsBindingLayout? bindingLayout = null;
        ISilkGraphicsShaderProgram? program = null;
        ISilkGraphicsPipeline? pipeline = null;
        try
        {
            vertexShader = _device.CreateShaderModule(materialProgram.VertexShader);
            fragmentShader = _device.CreateShaderModule(materialProgram.FragmentShader);
            bindingLayout = _device.CreateBindingLayout(materialProgram.BindingLayout);
            program = _device.CreateShaderProgram(new SilkShaderProgramDescriptor(
                vertexShader,
                fragmentShader,
                bindingLayout));
            pipeline = _device.CreateGraphicsPipeline(new SilkGraphicsPipelineDescriptor(
                program,
                vertexLayout,
                colorFormat,
                depthFormat,
                cullMode,
                topologyKind)
            {
                BlendMode = blendMode,
                DepthWriteEnabled = depthWriteEnabled,
            });
            return new CachedPipelineEntry(
                vertexShader,
                fragmentShader,
                bindingLayout,
                program,
                pipeline);
        }
        catch
        {
            pipeline?.Dispose();
            program?.Dispose();
            bindingLayout?.Dispose();
            fragmentShader?.Dispose();
            vertexShader?.Dispose();
            throw;
        }
    }

    private static string CreateVertexLayoutKey(SilkVertexLayoutDescriptor layout)
    {
        layout.Validate();
        var builder = new StringBuilder();
        builder.Append(layout.Stride);
        foreach (SilkVertexAttributeDescriptor attribute in layout.Attributes)
        {
            builder
                .Append('|')
                .Append((int)attribute.Semantic)
                .Append(':')
                .Append(attribute.Location)
                .Append(':')
                .Append(attribute.Offset)
                .Append(':')
                .Append((int)attribute.Format);
        }

        return builder.ToString();
    }

    private static DeviceGenerationKey ReadDeviceGeneration(ISilkGraphicsDevice device)
    {
        ulong pickGeneration = device is ISilkPickingGraphicsDevice pickingDevice
            ? pickingDevice.PickDeviceGeneration
            : 0;
        ulong selectionGeneration = device is ISilkSelectionOutlineGraphicsDevice outlineDevice
            ? outlineDevice.SelectionOutlineDeviceGeneration
            : 0;
        return new DeviceGenerationKey(pickGeneration, selectionGeneration);
    }

    private void DisposeEntries()
    {
        foreach (CachedPipelineEntry entry in _entries.Values)
        {
            entry.Dispose();
        }
        _entries.Clear();
    }

    private readonly record struct DeviceGenerationKey(
        ulong PickGeneration,
        ulong SelectionOutlineGeneration);

    private readonly record struct PipelineCacheKey(
        object ShaderIdentity,
        string VertexLayout,
        SilkTextureFormat ColorFormat,
        SilkTextureFormat DepthFormat,
        SilkCullMode CullMode,
        SilkTopologyKind TopologyKind,
        SilkBlendMode BlendMode,
        bool DepthWriteEnabled,
        SilkShaderBinaryFormat ShaderFormat,
        DeviceGenerationKey Generation);

    private sealed class CachedPipelineEntry(
        ISilkGraphicsShaderModule vertexShader,
        ISilkGraphicsShaderModule fragmentShader,
        ISilkGraphicsBindingLayout bindingLayout,
        ISilkGraphicsShaderProgram program,
        ISilkGraphicsPipeline pipeline)
    {
        private readonly object _gate = new();
        private int _leaseCount;
        private bool _disposeRequested;
        private bool _nativeReleased;

        public ISilkGraphicsPipeline AcquireLease()
        {
            lock (_gate)
            {
                ObjectDisposedException.ThrowIf(_disposeRequested, typeof(SilkGraphicsPipelineCache));
                _leaseCount++;
            }
            return new CachedPipelineLease(this, pipeline);
        }

        public void Dispose()
        {
            bool release;
            lock (_gate)
            {
                if (_disposeRequested)
                {
                    return;
                }

                _disposeRequested = true;
                release = _leaseCount == 0 && !_nativeReleased;
                if (release)
                {
                    _nativeReleased = true;
                }
            }

            if (release)
            {
                ReleaseNative();
            }
        }

        private void ReleaseLease()
        {
            bool release;
            lock (_gate)
            {
                _leaseCount--;
                release = _disposeRequested && _leaseCount == 0 && !_nativeReleased;
                if (release)
                {
                    _nativeReleased = true;
                }
            }

            if (release)
            {
                ReleaseNative();
            }
        }

        private void ReleaseNative()
        {
            pipeline.Dispose();
            program.Dispose();
            bindingLayout.Dispose();
            fragmentShader.Dispose();
            vertexShader.Dispose();
        }

        private sealed class CachedPipelineLease(
            CachedPipelineEntry entry,
            ISilkGraphicsPipeline pipeline) : ISilkGraphicsPipelineLease
        {
            private CachedPipelineEntry? _entry = entry;

            public SilkGraphicsPipelineDescriptor Descriptor => pipeline.Descriptor;

            public ISilkGraphicsPipeline Pipeline => pipeline;

            public void Dispose() =>
                Interlocked.Exchange(ref _entry, null)?.ReleaseLease();
        }
    }
}

/// <summary>Offscreen color and depth attachments.</summary>
public readonly record struct SilkRenderingDescriptor(
    ISilkGraphicsTexture ColorAttachment,
    ISilkGraphicsTexture DepthAttachment);

/// <summary>Floating-point viewport.</summary>
public readonly record struct SilkViewport(
    float X,
    float Y,
    float Width,
    float Height,
    float MinDepth = 0,
    float MaxDepth = 1)
{
    /// <summary>Validates finite positive dimensions and normalized depth.</summary>
    public void Validate()
    {
        if (!float.IsFinite(X) || !float.IsFinite(Y) ||
            !float.IsFinite(Width) || !float.IsFinite(Height) ||
            Width <= 0 || Height <= 0 ||
            !float.IsFinite(MinDepth) || !float.IsFinite(MaxDepth) ||
            MinDepth < 0 || MaxDepth > 1 || MinDepth > MaxDepth)
        {
            throw new ArgumentOutOfRangeException(nameof(Width));
        }
    }
}

/// <summary>Integer pixel scissor rectangle with a top-left-origin pixel coordinate.</summary>
public readonly record struct SilkScissor(int X, int Y, uint Width, uint Height)
{
    /// <summary>Validates positive dimensions and non-negative origin.</summary>
    public void Validate()
    {
        if (X < 0 || Y < 0 || Width == 0 || Height == 0)
        {
            throw new ArgumentOutOfRangeException(nameof(Width));
        }
    }
}

/// <summary>Validated reflected SceneParameters ABI.</summary>
public readonly record struct SilkSceneParametersReflection(
    bool RowMajor,
    uint MatrixOffset,
    uint MatrixByteSize,
    uint TintOffset,
    uint TintByteSize,
    uint ByteSize);

/// <summary>Validated reflected PickParameters ABI and primitive-ID input.</summary>
public readonly record struct SilkPickParametersReflection(
    uint Set,
    uint Binding,
    uint TokenOffset,
    uint TokenByteSize,
    uint ByteSize,
    bool UsesPrimitiveId);

/// <summary>NativeAOT-safe loader for checked shader artifacts embedded in production assemblies.</summary>
public static partial class SilkCheckedShaderAssets
{
    private const string Prefix = "OpenUsd.Rendering.Silk.Shaders.";
    private static readonly Lazy<SilkSceneParametersReflection> ReflectionValue =
        new(LoadAndValidateReflection);
    private static readonly Lazy<SilkComputeReflection> ComputeReflectionValue =
        new(LoadAndValidateComputeReflection);
    private static readonly Lazy<SilkPickParametersReflection> PickReflectionValue =
        new(LoadAndValidatePickReflection);

    /// <summary>Gets the validated reflected constant-buffer ABI.</summary>
    public static SilkSceneParametersReflection SceneParameters => ReflectionValue.Value;

    /// <summary>Gets the validated checked compute ABI.</summary>
    public static SilkComputeReflection Compute => ComputeReflectionValue.Value;

    /// <summary>Gets the validated checked pick ABI.</summary>
    public static SilkPickParametersReflection PickParameters =>
        PickReflectionValue.Value;

    /// <summary>Gets whether a validated pinned Metal library pair is deployed.</summary>
    public static bool HasPinnedMetalLibrary => TryLoadPinnedMetalLibrary(out _);

    /// <summary>Loads the checked mesh vertex module.</summary>
    public static SilkShaderModuleDescriptor LoadMeshVertex(
        SilkShaderBinaryFormat format) =>
        LoadMeshVertex(format, SilkShaderPermutationId.None);

    /// <summary>Loads the checked mesh vertex module for a manifest permutation.</summary>
    public static SilkShaderModuleDescriptor LoadMeshVertex(
        SilkShaderBinaryFormat format,
        SilkShaderPermutationId permutation) =>
        LoadGraphicsModuleByName(
            permutation.MeshVertexArtifactName,
            SilkShaderStage.Vertex,
            format,
            GetMeshPermutationEntryPoint(permutation.MeshVertexArtifactName, "mesh.vertex", "vertexMain"));

    /// <summary>Loads the checked mesh fragment module.</summary>
    public static SilkShaderModuleDescriptor LoadMeshFragment(
        SilkShaderBinaryFormat format) =>
        LoadMeshFragment(format, SilkShaderPermutationId.None);

    /// <summary>Loads the checked mesh fragment module for a manifest permutation.</summary>
    public static SilkShaderModuleDescriptor LoadMeshFragment(
        SilkShaderBinaryFormat format,
        SilkShaderPermutationId permutation) =>
        LoadGraphicsModuleByName(
            permutation.MeshFragmentArtifactName,
            SilkShaderStage.Fragment,
            format,
            GetMeshPermutationEntryPoint(
                permutation.MeshFragmentArtifactName,
                "mesh.fragment",
                "fragmentMain"));

    /// <summary>Loads the checked sampled-density-volume mesh fragment module.</summary>
    /// <remarks>
    /// A separate checked program, not a permutation of the shared mesh fragment
    /// family: it is the only mesh fragment binary that references the 3D density
    /// texture and its sampler, and only the sampled-volume binding layout declares
    /// them. Compiling those resources into the shared binary makes every ordinary
    /// mesh pipeline reference resources its root signature does not declare, which
    /// D3D12 rejects at pipeline creation.
    /// </remarks>
    internal static SilkShaderModuleDescriptor LoadMeshVolumeFragment(
        SilkShaderBinaryFormat format) =>
        LoadGraphicsModuleByName(
            "mesh.volume.fragment",
            SilkShaderStage.Fragment,
            format,
            "volumeFragmentMain");

    /// <summary>Loads the checked pick vertex module.</summary>
    public static SilkShaderModuleDescriptor LoadPickVertex(
        SilkShaderBinaryFormat format) =>
        LoadGraphicsModule(
            "pick",
            SilkShaderStage.Vertex,
            format,
            "pickVertexMain");

    /// <summary>Loads the checked pick fragment module.</summary>
    public static SilkShaderModuleDescriptor LoadPickFragment(
        SilkShaderBinaryFormat format) =>
        LoadGraphicsModule(
            "pick",
            SilkShaderStage.Fragment,
            format,
            "pickFragmentMain");

    /// <summary>Loads the checked fill compute module.</summary>
    public static SilkShaderModuleDescriptor LoadComputeFill(
        SilkShaderBinaryFormat format) =>
        LoadComputeModule("fill", "fillMain", format);

    /// <summary>Loads the checked scale compute module.</summary>
    public static SilkShaderModuleDescriptor LoadComputeScale(
        SilkShaderBinaryFormat format) =>
        LoadComputeModule("scale", "scaleMain", format);

    private static SilkShaderModuleDescriptor LoadGraphicsModule(
        string program,
        SilkShaderStage stage,
        SilkShaderBinaryFormat format,
        string entryPoint)
    {
        string stageName = stage == SilkShaderStage.Vertex ? "vertex" : "fragment";
        return LoadGraphicsModuleByName(
            $"{program}.{stageName}",
            stage,
            format,
            entryPoint);
    }

    private static SilkShaderModuleDescriptor LoadGraphicsModuleByName(
        string artifactName,
        SilkShaderStage stage,
        SilkShaderBinaryFormat format,
        string entryPoint)
    {
        byte[] code = format switch
        {
            SilkShaderBinaryFormat.Dxil => LoadEmbedded($"{artifactName}.dxil"),
            SilkShaderBinaryFormat.SpirV => LoadEmbedded($"{artifactName}.spv"),
            SilkShaderBinaryFormat.MetalLibrary => LoadPinnedMetalLibrary(),
            _ => throw new ArgumentOutOfRangeException(nameof(format))
        };
        string nativeEntryPoint = format == SilkShaderBinaryFormat.SpirV
            ? "main"
            : entryPoint;
        return new SilkShaderModuleDescriptor(stage, format, nativeEntryPoint, code);
    }

    private static string GetMeshPermutationEntryPoint(
        string artifactName,
        string baseName,
        string baseEntryPoint)
    {
        if (artifactName == baseName)
        {
            return baseEntryPoint;
        }

        string suffix = artifactName[(baseName.Length + 1)..].Replace('+', '_');
        return $"{baseEntryPoint}_{suffix}";
    }

    internal static SilkShaderModuleDescriptor LoadMeshFragmentForTesting(
        SilkShaderBinaryFormat format,
        string artifactName) =>
        LoadGraphicsModuleByName(
            artifactName,
            SilkShaderStage.Fragment,
            format,
            "fragmentMain");

    private static SilkShaderModuleDescriptor LoadComputeModule(
        string operation,
        string entryPoint,
        SilkShaderBinaryFormat format)
    {
        byte[] code = format switch
        {
            SilkShaderBinaryFormat.Dxil => LoadEmbedded($"compute.{operation}.dxil"),
            SilkShaderBinaryFormat.SpirV => LoadEmbedded($"compute.{operation}.spv"),
            SilkShaderBinaryFormat.MetalLibrary => LoadPinnedMetalLibrary(),
            _ => throw new ArgumentOutOfRangeException(nameof(format))
        };
        string nativeEntryPoint = format == SilkShaderBinaryFormat.SpirV
            ? "main"
            : entryPoint;
        return new SilkShaderModuleDescriptor(
            SilkShaderStage.Compute,
            format,
            nativeEntryPoint,
            code);
    }

    private static SilkSceneParametersReflection LoadAndValidateReflection()
    {
        byte[] vertex = LoadEmbedded("mesh.vertex.reflection.json");
        byte[] fragment = LoadEmbedded("mesh.fragment.reflection.json");
        byte[] manifest = LoadEmbedded("manifest.json");
        if (!Encoding.UTF8.GetString(manifest).Contains(
            "-matrix-layout-row-major",
            StringComparison.Ordinal))
        {
            throw new InvalidDataException("Checked shaders are not row-major.");
        }
        SilkSceneParametersReflection vertexLayout = ParseReflection(vertex);
        SilkSceneParametersReflection fragmentLayout = ParseReflection(fragment);
        if (vertexLayout != fragmentLayout ||
            vertexLayout != new SilkSceneParametersReflection(
                true,
                0,
                64,
                64,
                16,
                80))
        {
            throw new InvalidDataException(
                "Checked shader reflection does not match the SceneParameters ABI.");
        }
        return vertexLayout;
    }

    private static SilkPickParametersReflection LoadAndValidatePickReflection()
    {
        SilkSceneParametersReflection vertexLayout = ParseReflection(
            LoadEmbedded("pick.vertex.reflection.json"));
        if (vertexLayout != SceneParameters)
        {
            throw new InvalidDataException(
                "Checked pick vertex reflection does not match SceneParameters.");
        }

        using JsonDocument document = JsonDocument.Parse(
            LoadEmbedded("pick.fragment.reflection.json"));
        JsonElement root = document.RootElement;
        JsonElement resource = root.GetProperty("resources")[0];
        if (resource.GetProperty("name").GetString() != "PickParameters")
        {
            throw new InvalidDataException(
                "Checked pick reflection is missing PickParameters.");
        }

        JsonElement bindings = resource.GetProperty("bindings");
        JsonElement d3d = bindings.GetProperty("d3d");
        JsonElement vulkan = bindings.GetProperty("vulkan");
        if (d3d.GetProperty("registerClass").GetString() != "b" ||
            d3d.GetProperty("register").GetUInt32() != 1 ||
            d3d.GetProperty("space").GetUInt32() != 0 ||
            vulkan.GetProperty("set").GetUInt32() != 0 ||
            vulkan.GetProperty("binding").GetUInt32() != 1)
        {
            throw new InvalidDataException(
                "Checked PickParameters must use b1, space 0 and set 0, binding 1.");
        }

        ValidatePickParameterShape(resource.GetProperty("shape"));
        ValidatePickParameterShape(resource.GetProperty("vulkanLayout"));
        bool usesPrimitiveId = false;
        foreach (JsonElement input in root.GetProperty("stageInputs").EnumerateArray())
        {
            JsonElement semantic = input.GetProperty("semantic");
            if (semantic.GetProperty("name").GetString() == "SV_PRIMITIVEID")
            {
                JsonElement type = input.GetProperty("type");
                usesPrimitiveId =
                    semantic.GetProperty("systemValue").GetBoolean() &&
                    input.GetProperty("location").ValueKind == JsonValueKind.Null &&
                    type.GetProperty("kind").GetString() == "scalar" &&
                    type.GetProperty("scalarType").GetString() == "uint32";
            }
        }
        if (!usesPrimitiveId)
        {
            throw new InvalidDataException(
                "Checked pick fragment reflection must consume SV_PrimitiveID.");
        }

        return new SilkPickParametersReflection(
            0,
            1,
            0,
            16,
            16,
            true);
    }

    private static SilkComputeReflection LoadAndValidateComputeReflection()
    {
        SilkComputeReflection fill = ParseComputeReflection(
            LoadEmbedded("compute.fill.reflection.json"));
        SilkComputeReflection scale = ParseComputeReflection(
            LoadEmbedded("compute.scale.reflection.json"));
        var expected = new SilkComputeReflection(
            0,
            0,
            16,
            0,
            1,
            8,
            16,
            64,
            1,
            1);
        if (fill != scale || fill != expected)
        {
            throw new InvalidDataException(
                "Checked compute reflection does not match the outputValues and " +
                "ComputeParameters ABI.");
        }
        return fill;
    }

    private static SilkSceneParametersReflection ParseReflection(ReadOnlySpan<byte> json)
    {
        using JsonDocument document = JsonDocument.Parse(json.ToArray());
        JsonElement shape = default;
        foreach (JsonElement resource in document.RootElement.GetProperty("resources").EnumerateArray())
        {
            if (resource.GetProperty("name").GetString() == "SceneParameters")
            {
                shape = resource.GetProperty("shape");
                break;
            }
        }

        if (shape.ValueKind == JsonValueKind.Undefined)
        {
            throw new InvalidDataException("Checked shader reflection is missing SceneParameters.");
        }

        JsonElement fields = shape.GetProperty("elementType").GetProperty("fields");
        JsonElement matrixLayout = fields[0].GetProperty("layout");
        JsonElement tintLayout = fields[1].GetProperty("layout");
        return new SilkSceneParametersReflection(
            true,
            matrixLayout.GetProperty("offset").GetUInt32(),
            matrixLayout.GetProperty("size").GetUInt32(),
            tintLayout.GetProperty("offset").GetUInt32(),
            tintLayout.GetProperty("size").GetUInt32(),
            shape.GetProperty("size").GetUInt32());
    }

    private static SilkComputeReflection ParseComputeReflection(ReadOnlySpan<byte> json)
    {
        using JsonDocument document = JsonDocument.Parse(json.ToArray());
        JsonElement root = document.RootElement;
        JsonElement threadGroup = root.GetProperty("entryPoint").GetProperty("threadGroupSize");
        JsonElement resources = root.GetProperty("resources");
        JsonElement storage = resources[0];
        JsonElement uniform = resources[1];
        if (storage.GetProperty("name").GetString() != "outputValues" ||
            uniform.GetProperty("name").GetString() != "ComputeParameters")
        {
            throw new InvalidDataException("Checked compute resources are out of order.");
        }
        JsonElement storageD3D = storage.GetProperty("bindings").GetProperty("d3d");
        JsonElement uniformD3D = uniform.GetProperty("bindings").GetProperty("d3d");
        JsonElement storageBindings = storage.GetProperty("bindings").GetProperty("vulkan");
        JsonElement uniformBindings = uniform.GetProperty("bindings").GetProperty("vulkan");
        JsonElement storageShape = storage.GetProperty("shape");
        JsonElement storageVulkanShape = storage.GetProperty("vulkanLayout");
        JsonElement uniformShape = uniform.GetProperty("shape");
        JsonElement uniformVulkanShape = uniform.GetProperty("vulkanLayout");
        ValidateD3DBinding(storageD3D, "u", 0);
        ValidateD3DBinding(uniformD3D, "b", 1);
        ValidateStorageShape(storageShape);
        ValidateStorageShape(storageVulkanShape);
        ValidateParameterShape(uniformShape, 8);
        ValidateParameterShape(uniformVulkanShape, 16);
        return new SilkComputeReflection(
            storageBindings.GetProperty("set").GetUInt32(),
            storageBindings.GetProperty("binding").GetUInt32(),
            storageShape.GetProperty("elementStride").GetUInt32(),
            uniformBindings.GetProperty("set").GetUInt32(),
            uniformBindings.GetProperty("binding").GetUInt32(),
            uniformShape.GetProperty("size").GetUInt32(),
            uniformVulkanShape.GetProperty("size").GetUInt32(),
            threadGroup[0].GetUInt32(),
            threadGroup[1].GetUInt32(),
            threadGroup[2].GetUInt32());
    }

    private static SilkComputeReflection ParseComputeReflectionForTesting(byte[] json) =>
        ParseComputeReflection(json);

    private static void ValidateD3DBinding(
        JsonElement binding,
        string registerClass,
        uint register)
    {
        if (binding.GetProperty("registerClass").GetString() != registerClass ||
            binding.GetProperty("register").GetUInt32() != register ||
            binding.GetProperty("space").GetUInt32() != 0)
        {
            throw new InvalidDataException(
                $"Checked compute D3D binding must be {registerClass}{register}, space 0.");
        }
    }

    private static void ValidateStorageShape(JsonElement shape)
    {
        JsonElement elementType = shape.GetProperty("elementType");
        JsonElement scalar = elementType.GetProperty("elementType");
        if (shape.GetProperty("kind").GetString() != "structuredBuffer" ||
            shape.GetProperty("access").GetString() != "readWrite" ||
            shape.GetProperty("elementStride").GetUInt32() != 16 ||
            elementType.GetProperty("kind").GetString() != "vector" ||
            elementType.GetProperty("elementCount").GetUInt32() != 4 ||
            scalar.GetProperty("kind").GetString() != "scalar" ||
            scalar.GetProperty("scalarType").GetString() != "float32")
        {
            throw new InvalidDataException(
                "Checked outputValues must be a read-write float4 structured buffer with stride 16.");
        }
    }

    private static void ValidateParameterShape(JsonElement shape, uint size)
    {
        JsonElement fields = shape.GetProperty("elementType").GetProperty("fields");
        if (shape.GetProperty("kind").GetString() != "constantBuffer" ||
            shape.GetProperty("access").GetString() != "constant" ||
            shape.GetProperty("size").GetUInt32() != size ||
            fields.GetArrayLength() != 2 ||
            !HasScalarField(fields[0], "elementCount", "uint32", 0) ||
            !HasScalarField(fields[1], "scale", "float32", 4))
        {
            throw new InvalidDataException(
                $"Checked ComputeParameters must contain uint elementCount at 0 and " +
                $"float scale at 4 in a {size}-byte constant buffer.");
        }
    }

    private static void ValidatePickParameterShape(JsonElement shape)
    {
        JsonElement fields = shape.GetProperty("elementType").GetProperty("fields");
        JsonElement field = fields[0];
        JsonElement type = field.GetProperty("type");
        JsonElement elementType = type.GetProperty("elementType");
        JsonElement layout = field.GetProperty("layout");
        if (shape.GetProperty("kind").GetString() != "constantBuffer" ||
            shape.GetProperty("access").GetString() != "constant" ||
            shape.GetProperty("size").GetUInt32() != 16 ||
            fields.GetArrayLength() != 1 ||
            field.GetProperty("name").GetString() != "pickToken" ||
            type.GetProperty("kind").GetString() != "vector" ||
            type.GetProperty("elementCount").GetUInt32() != 4 ||
            elementType.GetProperty("kind").GetString() != "scalar" ||
            elementType.GetProperty("scalarType").GetString() != "uint32" ||
            layout.GetProperty("offset").GetUInt32() != 0 ||
            layout.GetProperty("size").GetUInt32() != 16)
        {
            throw new InvalidDataException(
                "Checked PickParameters must contain one 16-byte uint4 at offset zero.");
        }
    }

    private static bool HasScalarField(
        JsonElement field,
        string name,
        string scalarType,
        uint offset)
    {
        JsonElement type = field.GetProperty("type");
        JsonElement layout = field.GetProperty("layout");
        return field.GetProperty("name").GetString() == name &&
            type.GetProperty("kind").GetString() == "scalar" &&
            type.GetProperty("scalarType").GetString() == scalarType &&
            layout.GetProperty("offset").GetUInt32() == offset &&
            layout.GetProperty("size").GetUInt32() == 4;
    }

    private static byte[] LoadEmbedded(string name)
    {
        Assembly assembly = typeof(SilkCheckedShaderAssets).Assembly;
        using Stream stream = assembly.GetManifestResourceStream(Prefix + name) ??
            throw new InvalidDataException($"Missing embedded checked shader asset '{name}'.");
        var bytes = new byte[checked((int)stream.Length)];
        stream.ReadExactly(bytes);
        return bytes;
    }
}
