# Copyright (c) marcschier. Licensed under the MIT License.
"""Generates the codeless openUsdPhysics schema artifacts.

`openUsdPhysics.schema.json` is the single source of truth. This script emits, all
from that one file:

  schema.usda                            the usdGenSchema input
  resources/plugInfo.json                the codeless plugin registration
  resources/generatedSchema.usda         the flattened schema registry layer
  precedence-manifest.json               the property/source resolution manifest
  src/OpenUsd.Physics/Schema/*.g.cs      typed managed facades and property tokens
  src/OpenUsd.Physics/PublicAPI.Unshipped.txt
                                         merged public API entries for the facades

Property types are restricted to the set `OpenUsd.UsdPrim` round-trips through its
generic typed accessors, so the managed facades need no new interop.

`usdGenSchema` remains the canonical producer of the two `resources/` files. It needs
a USD build with Python bindings, which this repository does not vendor, so this
script produces the same artifacts deterministically in the meantime. When a USD
Python build becomes available, run `usdGenSchema schema.usda resources` and the
output should be equivalent; `OpenUsdPhysicsSchemaContractTests` guards the
consistency of whichever producer wrote the files.

Usage:
    python schemas/openUsdPhysics/tools/generate_schema.py [--check]

`--check` writes nothing and fails when any artifact is out of date.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCHEMA_ROOT = Path(__file__).resolve().parent.parent
DEFINITION_PATH = SCHEMA_ROOT / "openUsdPhysics.schema.json"

GENERATED_HEADER = (
    '#usda 1.0\n'
    '(\n'
    '    "WARNING: THIS FILE IS GENERATED BY usdGenSchema.  DO NOT EDIT."\n'
    ')\n'
)

PLUGINFO_COMMENT = (
    "# Portions of this file auto-generated by usdGenSchema.\n"
    "# Edits will survive regeneration except for comments and\n"
    "# changes to types with autoGenerated=true.\n"
)

BASE_CPP_CLASS = {
    "APISchemaBase": "UsdAPISchemaBase",
    "Typed": "UsdTyped",
}

SCALAR_TYPES = {
    "bool",
    "int64",
    "double",
    "string",
    "token",
    "float3",
}

ARRAY_TYPES = {
    "bool[]",
    "int[]",
    "float[]",
    "double[]",
    "token[]",
    "string[]",
    "float2[]",
    "float3[]",
}

# Every property type is restricted to what OpenUsd.UsdPrim round-trips through its
# generic typed accessors. That keeps the generated managed facades free of new interop
# and keeps a codeless plugin usable from managed code on a stock OpenUSD runtime.
CSHARP_TYPES = {
    "bool": ("bool", "bool"),
    "int64": ("long", "long"),
    "double": ("double", "double"),
    "string": ("string", "string!"),
    "token": ("string", "string!"),
    "float3": ("UsdVec3f", "OpenUsd.UsdVec3f"),
    "bool[]": ("bool[]", "bool[]!"),
    "int[]": ("int[]", "int[]!"),
    "float[]": ("float[]", "float[]!"),
    "double[]": ("double[]", "double[]!"),
    "token[]": ("string[]", "string![]!"),
    "string[]": ("string[]", "string![]!"),
    "float2[]": ("UsdVec2f[]", "OpenUsd.UsdVec2f[]!"),
    "float3[]": ("UsdVec3f[]", "OpenUsd.UsdVec3f[]!"),
}

CSHARP_ACCESSORS = {
    "bool": ("GetBool", "SetBool"),
    "int64": ("GetInt64", "SetInt64"),
    "double": ("GetDouble", "SetDouble"),
    "string": ("GetString", "SetString"),
    "token": ("GetToken", "SetToken"),
    "float3": ("GetVec3f", "SetVec3f"),
    "bool[]": ("GetBoolArray", "SetBoolArray"),
    "int[]": ("GetInt32Array", "SetInt32Array"),
    "float[]": ("GetFloatArray", "SetFloatArray"),
    "double[]": ("GetDoubleArray", "SetDoubleArray"),
    "token[]": ("GetTokenArray", "SetTokenArray"),
    "string[]": ("GetStringArray", "SetStringArray"),
    "float2[]": ("GetVec2fArray", "SetVec2fArray"),
    "float3[]": ("GetVec3fArray", "SetVec3fArray"),
}

RESERVED_MEMBER_NAMES = {
    "Prim",
    "Path",
    "Has",
    "IsA",
    "Wrap",
    "Define",
    "SchemaIdentifier",
    "TypeName",
    "Equals",
    "GetHashCode",
    "ToString",
}

CSHARP_NAMESPACE = "OpenUsd.Physics.Schema"
CSHARP_TOKENS_CLASS = "OpenUsdPhysicsTokens"
CSHARP_CATALOG_CLASS = "OpenUsdPhysicsPropertyCatalog"
CSHARP_ROOT = SCHEMA_ROOT.parent.parent / "src" / "OpenUsd.Physics"
CSHARP_SCHEMA_DIR = CSHARP_ROOT / "Schema"
PUBLIC_API_PATH = CSHARP_ROOT / "PublicAPI.Unshipped.txt"

# The managed catalog names one value kind per schema property type, so a generic editor can
# decide how to present a property without re-deriving the mapping from a USD type string.
CATALOG_VALUE_KINDS = {
    "bool": "Bool",
    "int64": "Int64",
    "double": "Double",
    "string": "String",
    "token": "Token",
    "float3": "Float3",
    "bool[]": "BoolArray",
    "int[]": "IntArray",
    "float[]": "FloatArray",
    "double[]": "DoubleArray",
    "token[]": "TokenArray",
    "string[]": "StringArray",
    "float2[]": "Float2Array",
    "float3[]": "Float3Array",
    "rel": "Relationship",
}

# The domain a schema belongs to is spelled out per class rather than inferred from its name.
# Inference would silently mis-file a class the moment one is added whose name merely starts
# with an existing prefix, and OpenUsdPhysicsParticleClothAPI - which is cloth, not particles -
# is exactly that case.
CATALOG_DOMAINS = {
    "OpenUsdPhysicsSceneAPI": "Scene",
    "OpenUsdPhysicsRigidBodySettingsAPI": "RigidBody",
    "OpenUsdPhysicsCollisionSettingsAPI": "Collision",
    "OpenUsdPhysicsCollisionFilterSettingsAPI": "Collision",
    "OpenUsdPhysicsCookedDataAPI": "Collision",
    "OpenUsdPhysicsMaterialSettingsAPI": "Material",
    "OpenUsdPhysicsArticulationSettingsAPI": "Articulation",
    "OpenUsdPhysicsSimulationMetadataAPI": "Metadata",
    "OpenUsdPhysicsCharacterControllerAPI": "CharacterController",
    "OpenUsdPhysicsVehicleAPI": "Vehicle",
    "OpenUsdPhysicsVehicleWheelAttachmentAPI": "Vehicle",
    "OpenUsdPhysicsVehicleWheelAPI": "Vehicle",
    "OpenUsdPhysicsVehicleSuspensionAPI": "Vehicle",
    "OpenUsdPhysicsVehicleTireAPI": "Vehicle",
    "OpenUsdPhysicsVehicleTireFrictionTable": "Vehicle",
    "OpenUsdPhysicsVehicleEngineAPI": "Vehicle",
    "OpenUsdPhysicsVehicleGearsAPI": "Vehicle",
    "OpenUsdPhysicsVehicleAutoGearBoxAPI": "Vehicle",
    "OpenUsdPhysicsVehicleClutchAPI": "Vehicle",
    "OpenUsdPhysicsVehicleDifferentialAPI": "Vehicle",
    "OpenUsdPhysicsVehicleBrakesAPI": "Vehicle",
    "OpenUsdPhysicsVehicleSteeringAPI": "Vehicle",
    "OpenUsdPhysicsFixedTendon": "Tendon",
    "OpenUsdPhysicsSpatialTendon": "Tendon",
    "OpenUsdPhysicsTendonAttachmentAPI": "Tendon",
    "OpenUsdPhysicsMimicJointAPI": "MimicJoint",
    "OpenUsdPhysicsParticleSystemAPI": "Particles",
    "OpenUsdPhysicsParticleSetAPI": "Particles",
    "OpenUsdPhysicsPbdMaterialAPI": "Particles",
    "OpenUsdPhysicsDiffuseParticlesAPI": "Particles",
    "OpenUsdPhysicsParticleAnisotropyAPI": "Particles",
    "OpenUsdPhysicsParticleSmoothingAPI": "Particles",
    "OpenUsdPhysicsParticleIsosurfaceAPI": "Particles",
    "OpenUsdPhysicsParticleClothAPI": "Cloth",
    "OpenUsdPhysicsSurfaceDeformableAPI": "Cloth",
    "OpenUsdPhysicsSurfaceDeformableMaterialAPI": "Cloth",
    "OpenUsdPhysicsVolumeDeformableAPI": "Deformable",
    "OpenUsdPhysicsVolumeDeformableMaterialAPI": "Deformable",
    "OpenUsdPhysicsAttachment": "Attachment",
    "OpenUsdPhysicsAutoAttachmentAPI": "Attachment",
}

# The capability a domain needs before an editor may present it as usable. Scene and metadata
# settings are always meaningful, so they require nothing; every other domain names the exact
# capability a built world has to report before its controls stop being a lie.
CATALOG_CAPABILITIES = {
    "Scene": "None",
    "Metadata": "None",
    "RigidBody": "RigidBodies",
    "Collision": "RigidBodies",
    "Material": "RigidBodies",
    "Articulation": "Articulations",
    "Tendon": "Articulations",
    "MimicJoint": "Articulations",
    "CharacterController": "Controllers",
    "Vehicle": "Vehicles",
    "Particles": "Particles",
    "Cloth": "Cloth",
    "Deformable": "Deformables",
    # An attachment only exists to bind a deformable or a particle body to something else, so
    # the volume deformable capability is the one that decides whether it can be simulated.
    "Attachment": "Deformables",
}

CATALOG_DOMAIN_ORDER = [
    "Scene",
    "RigidBody",
    "Collision",
    "Material",
    "Articulation",
    "Tendon",
    "MimicJoint",
    "CharacterController",
    "Vehicle",
    "Particles",
    "Cloth",
    "Deformable",
    "Attachment",
    "Metadata",
]

CATALOG_DOMAIN_DOCS = {
    "Scene": "Solver and stepping settings of one physics scene.",
    "RigidBody": "Rigid body mass, damping, sleeping, and solver settings.",
    "Collision": "Collider geometry settings, filtering, and cooked collision data.",
    "Material": "Contact material settings shared by colliders.",
    "Articulation": "Reduced-coordinate articulation settings.",
    "Tendon": "Fixed and spatial tendons and their attachments.",
    "MimicJoint": "Joint axes driven to follow another joint axis.",
    "CharacterController": "Kinematic character controllers.",
    "Vehicle": "Vehicles, wheels, suspension, tires, and the drivetrain.",
    "Particles": "Particle systems, sets, and their PBD materials.",
    "Cloth": "Particle cloth and surface deformables.",
    "Deformable": "FEM volume deformables and their materials.",
    "Attachment": "Attachments binding deformable or particle bodies to other bodies.",
    "Metadata": "Simulation provenance metadata carried by the stage.",
}

CSHARP_HEADER = (
    "// Copyright (c) marcschier. Licensed under the MIT License.\n"
    "// <auto-generated>\n"
    "//     Generated by schemas/openUsdPhysics/tools/generate_schema.py from\n"
    "//     schemas/openUsdPhysics/openUsdPhysics.schema.json. Do not edit by hand.\n"
    "// </auto-generated>\n"
    "#nullable enable\n"
)


def format_float(value: float) -> str:
    """Formats a float the way USD writes one: no trailing '.0', 'inf' spelled out."""
    if isinstance(value, str):
        if value in ("inf", "-inf"):
            return value
        raise ValueError(f"Unsupported float literal '{value}'.")
    if value != value:
        raise ValueError("NaN defaults are not supported.")
    if value == int(value) and abs(value) < 1e16:
        return str(int(value))
    return repr(value)


def format_quoted(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def format_value(type_name: str, value, *, boolean_as_int: bool) -> str:
    if type_name == "bool":
        if boolean_as_int:
            return "1" if value else "0"
        return "true" if value else "false"
    if type_name == "int64":
        return str(int(value))
    if type_name == "double":
        return format_float(value)
    if type_name == "string":
        return format_quoted(value)
    if type_name == "token":
        return format_quoted(value)
    if type_name == "float3":
        return "(" + ", ".join(format_float(component) for component in value) + ")"
    if type_name == "token[]" or type_name == "string[]":
        return "[" + ", ".join(format_quoted(entry) for entry in value) + "]"
    if type_name == "int[]":
        return "[" + ", ".join(str(int(entry)) for entry in value) + "]"
    if type_name in ("float[]", "double[]"):
        return "[" + ", ".join(format_float(entry) for entry in value) + "]"
    if type_name == "bool[]":
        return "[" + ", ".join(
            ("1" if entry else "0") if boolean_as_int else ("true" if entry else "false")
            for entry in value) + "]"
    if type_name in ("float2[]", "float3[]"):
        return "[" + ", ".join(
            "(" + ", ".join(format_float(component) for component in tuple_value) + ")"
            for tuple_value in value) + "]"
    raise ValueError(f"Unsupported property type '{type_name}'.")


def sorted_properties(cls: dict) -> list:
    return sorted(cls["properties"], key=lambda prop: prop["name"])


def pascal_case(value: str) -> str:
    """Upper-cases the first character only, so camel humps and acronyms survive."""
    if not value:
        raise ValueError("Cannot derive a managed name from an empty segment.")
    return value[0].upper() + value[1:]


def member_name(prop: dict) -> str:
    return pascal_case(prop["name"].split(":")[2])


def token_name(prop: dict) -> str:
    _, group, leaf = prop["name"].split(":")
    return pascal_case(group) + pascal_case(leaf)


def xml_doc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def validate(definition: dict) -> None:
    namespace = definition["library"]["propertyNamespace"]
    seen_classes = set()
    seen_tokens: dict = {}
    for cls in definition["classes"]:
        if cls["name"] in seen_classes:
            raise ValueError(f"Duplicate class '{cls['name']}'.")
        seen_classes.add(cls["name"])
        if not cls["name"].startswith(definition["library"]["prefix"]):
            raise ValueError(
                f"Class '{cls['name']}' must start with the library prefix.")
        if cls["name"] != definition["library"]["prefix"] + cls["className"]:
            raise ValueError(
                f"Class '{cls['name']}' does not match its className "
                f"'{cls['className']}'.")
        if cls["kind"] not in ("singleApplyAPI", "concreteTyped"):
            raise ValueError(f"Unsupported schema kind '{cls['kind']}'.")
        if cls["base"] not in BASE_CPP_CLASS:
            raise ValueError(f"Unsupported base '{cls['base']}'.")
        if (cls["kind"] == "singleApplyAPI") != cls["name"].endswith("API"):
            raise ValueError(
                f"Class '{cls['name']}' kind and name suffix disagree.")
        seen_properties = set()
        seen_members = set()
        for prop in cls["properties"]:
            name = prop["name"]
            if name in seen_properties:
                raise ValueError(f"Duplicate property '{name}' on {cls['name']}.")
            seen_properties.add(name)
            if not name.startswith(namespace + ":"):
                raise ValueError(
                    f"Property '{name}' is not in the '{namespace}' namespace.")
            if name.count(":") != 2:
                raise ValueError(
                    f"Property '{name}' must be '{namespace}:<group>:<name>'.")
            member = member_name(prop)
            if member in RESERVED_MEMBER_NAMES:
                raise ValueError(
                    f"Property '{name}' maps to reserved managed member '{member}'.")
            if member in seen_members:
                raise ValueError(
                    f"Property '{name}' collides with another managed member "
                    f"'{member}' on {cls['name']}.")
            seen_members.add(member)
            token = token_name(prop)
            if seen_tokens.setdefault(token, name) != name:
                raise ValueError(
                    f"Property '{name}' collides with '{seen_tokens[token]}' on the "
                    f"generated token constant '{token}'.")
            type_name = prop["type"]
            if type_name == "rel":
                if "default" in prop or prop.get("uniform"):
                    raise ValueError(
                        f"Relationship '{name}' cannot declare a default or uniform.")
                continue
            if type_name not in SCALAR_TYPES and type_name not in ARRAY_TYPES:
                raise ValueError(f"Unsupported type '{type_name}' on '{name}'.")
            if type_name not in CSHARP_TYPES or type_name not in CSHARP_ACCESSORS:
                raise ValueError(
                    f"Type '{type_name}' on '{name}' has no managed accessor.")
            if "default" not in prop:
                raise ValueError(f"Attribute '{name}' requires a default.")
            if "allowedTokens" in prop and prop["default"] not in prop["allowedTokens"]:
                raise ValueError(
                    f"Default of '{name}' is not one of its allowed tokens.")


def render_schema_usda(definition: dict) -> str:
    library = definition["library"]
    lines = ["#usda 1.0", "(", "    subLayers = ["]
    lines.extend(
        f"        @{sub_layer}@," for sub_layer in library["subLayers"][:-1])
    lines.append(f"        @{library['subLayers'][-1]}@")
    lines.append("    ]")
    lines.append(")")
    lines.append("")
    lines.append('over "GLOBAL" (')
    lines.append("    customData = {")
    lines.append(f'        string libraryName = "{library["name"]}"')
    lines.append(f'        string libraryPath = "{library["path"]}"')
    lines.append(f'        string libraryPrefix = "{library["prefix"]}"')
    lines.append("        bool skipCodeGeneration = true")
    lines.append("    }")
    lines.append(")")
    lines.append("{")
    lines.append("}")

    for cls in definition["classes"]:
        lines.append("")
        if cls["kind"] == "concreteTyped":
            lines.append(f'class {cls["name"]} "{cls["name"]}" (')
        else:
            lines.append(f'class "{cls["name"]}" (')
        lines.append("    customData = {")
        lines.append(f'        string className = "{cls["className"]}"')
        if cls["kind"] == "singleApplyAPI":
            lines.append('        token apiSchemaType = "singleApply"')
        lines.append("    }")
        lines.append(f'    doc = """{cls["doc"]}"""')
        lines.append("")
        lines.append(f'    inherits = </{cls["base"]}>')
        lines.append(")")
        lines.append("{")
        for index, prop in enumerate(sorted_properties(cls)):
            if index > 0:
                lines.append("")
            lines.extend(
                render_property(prop, boolean_as_int=False, include_doc=True))
        lines.append("}")

    lines.append("")
    return "\n".join(lines)


def render_property(prop: dict, *, boolean_as_int: bool, include_doc: bool) -> list:
    name = prop["name"]
    type_name = prop["type"]
    if type_name == "rel":
        declaration = f"    rel {name}"
    else:
        qualifier = "uniform " if prop.get("uniform") else ""
        value = format_value(
            type_name, prop["default"], boolean_as_int=boolean_as_int)
        declaration = f"    {qualifier}{type_name} {name} = {value}"

    metadata = []
    if "allowedTokens" in prop:
        allowed = ", ".join(format_quoted(token) for token in prop["allowedTokens"])
        metadata.append(f"        allowedTokens = [{allowed}]")
    if "displayName" in prop:
        metadata.append(f'        displayName = {format_quoted(prop["displayName"])}')
    if include_doc:
        metadata.append(f'        doc = """{prop["doc"]}"""')

    if not metadata:
        return [declaration]
    return [declaration + " ("] + metadata + ["    )"]


def render_generated_schema(definition: dict) -> str:
    lines = [GENERATED_HEADER.rstrip("\n")]
    for cls in definition["classes"]:
        lines.append("")
        if cls["kind"] == "concreteTyped":
            lines.append(f'class {cls["name"]} "{cls["name"]}"')
        else:
            lines.append(f'class "{cls["name"]}"')
        lines.append("{")
        for prop in sorted_properties(cls):
            lines.extend(
                render_property(prop, boolean_as_int=True, include_doc=False))
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_plug_info(definition: dict) -> str:
    library = definition["library"]
    types = {}
    for cls in definition["classes"]:
        types[cls["name"]] = {
            "autoGenerated": True,
            "bases": [BASE_CPP_CLASS[cls["base"]]],
            "schemaIdentifier": cls["name"],
            "schemaKind": cls["kind"],
        }
    info = {
        "Plugins": [
            {
                "Info": {"Types": types},
                "Name": library["name"],
                "ResourcePath": "resources",
                "Root": "..",
                "Type": "resource",
            }
        ]
    }
    body = json.dumps(info, indent=4, sort_keys=True, separators=(", ", ": "))
    return PLUGINFO_COMMENT + body + "\n"


def render_precedence_manifest(definition: dict) -> str:
    library = definition["library"]
    precedence = sorted(definition["precedence"], key=lambda entry: entry["rank"])
    properties = []
    for cls in definition["classes"]:
        for prop in sorted_properties(cls):
            group = prop["name"].split(":")[1]
            properties.append({
                "property": prop["name"],
                "schema": cls["name"],
                "schemaKind": cls["kind"],
                "group": group,
                "type": prop["type"],
                "uniform": bool(prop.get("uniform", False)),
                "sourceNamespace": library["propertyNamespace"],
                "source": "project",
                "rank": precedence[0]["rank"],
            })
    manifest = {
        "$schemaVersion": 1,
        "generatedBy": "schemas/openUsdPhysics/tools/generate_schema.py",
        "generatedFrom": "schemas/openUsdPhysics/openUsdPhysics.schema.json",
        "resolutionRule": (
            "For one simulated property, the strongest authored opinion wins: an "
            "openUsdPhysics:* opinion overrides a physx* opinion, which overrides a "
            "standard physics:* opinion. An unsupported extension property produces a "
            "property-specific diagnostic and never suppresses supported semantics on "
            "the same object."
        ),
        "namespaces": precedence,
        "gaps": definition["gaps"],
        "properties": properties,
        "counts": {
            "schemas": len(definition["classes"]),
            "properties": len(properties),
        },
    }
    return json.dumps(manifest, indent=2, sort_keys=False) + "\n"


def render_tokens_csharp(definition: dict) -> str:
    library = definition["library"]
    lines = [CSHARP_HEADER.rstrip("\n"), ""]
    lines.append(f"namespace {CSHARP_NAMESPACE};")
    lines.append("")
    lines.append("/// <summary>")
    lines.append(
        "/// Property names of the codeless <c>openUsdPhysics</c> schema plugin. Use these "
        "constants instead of")
    lines.append("/// spelling a namespaced property name at a call site.")
    lines.append("/// </summary>")
    lines.append(f"public static class {CSHARP_TOKENS_CLASS}")
    lines.append("{")
    lines.append(
        "    /// <summary>The property namespace every openUsdPhysics property lives in.</summary>")
    lines.append(
        f'    public const string PropertyNamespace = "{library["propertyNamespace"]}";')
    lines.append("")
    lines.append(
        "    /// <summary>The plugin name registered by the generated plugInfo.json.</summary>")
    lines.append(f'    public const string PluginName = "{library["name"]}";')
    for cls in definition["classes"]:
        for prop in sorted_properties(cls):
            lines.append("")
            lines.append(
                f'    /// <summary>The <c>{xml_doc(prop["name"])}</c> property of '
                f'<c>{cls["name"]}</c>.</summary>')
            lines.append(
                f'    public const string {token_name(prop)} = "{prop["name"]}";')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_property_members(cls: dict, prop: dict) -> list:
    name = prop["name"]
    member = member_name(prop)
    token = f"{CSHARP_TOKENS_CLASS}.{token_name(prop)}"
    doc = xml_doc(prop["doc"])
    if prop["type"] == "rel":
        return [
            "",
            f"    /// <summary>Gets the targets of <c>{xml_doc(name)}</c>. {doc}</summary>",
            f"    public string[] Get{member}() => _prim.GetRelationshipTargets({token});",
            "",
            f"    /// <summary>Replaces the targets of <c>{xml_doc(name)}</c>. {doc}</summary>",
            "    /// <param name=\"targets\">The prim paths to author as targets.</param>",
            f"    public void Set{member}(string[] targets) =>",
            f"        _prim.SetRelationshipTargets({token}, targets);",
            "",
            f"    /// <summary>Clears every target of <c>{xml_doc(name)}</c>.</summary>",
            f"    public void Clear{member}() => _prim.ClearRelationshipTargets({token});",
        ]

    csharp_type = CSHARP_TYPES[prop["type"]][0]
    getter, setter = CSHARP_ACCESSORS[prop["type"]]
    return [
        "",
        f"    /// <summary>Gets or sets <c>{xml_doc(name)}</c>. {doc}</summary>",
        f"    public {csharp_type} {member}",
        "    {",
        f"        get => _prim.{getter}({token});",
        f"        set => _prim.{setter}({token}, value);",
        "    }",
    ]


def render_schemas_csharp(definition: dict) -> str:
    lines = [CSHARP_HEADER.rstrip("\n"), ""]
    lines.append(f"namespace {CSHARP_NAMESPACE};")

    for cls in definition["classes"]:
        typed = cls["kind"] == "concreteTyped"
        lines.append("")
        lines.append("/// <summary>")
        lines.append(f'/// {xml_doc(cls["doc"])}')
        lines.append("/// </summary>")
        lines.append("/// <remarks>")
        if typed:
            lines.append(
                "/// The plugin is codeless, so this facade reads and writes the underlying "
                "attributes through")
            lines.append(
                "/// <see cref=\"UsdPrim\"/> and never depends on a compiled schema library.")
        else:
            lines.append(
                "/// The plugin is codeless, so this facade reads and writes the underlying "
                "attributes through")
            lines.append(
                "/// <see cref=\"UsdPrim\"/>. Authoring the <c>apiSchemas</c> list itself is not "
                "exposed by the")
            lines.append(
                "/// managed runtime yet, so use <see cref=\"Wrap\"/> on a prim that already "
                "carries the schema.")
        lines.append("/// </remarks>")
        lines.append(f'public readonly struct {cls["name"]}')
        lines.append("{")
        lines.append(
            "    /// <summary>The schema identifier registered by the codeless plugin.</summary>")
        lines.append(f'    public const string SchemaIdentifier = "{cls["name"]}";')
        lines.append("")
        lines.append("    private readonly UsdPrim _prim;")
        lines.append("")
        lines.append(f'    private {cls["name"]}(UsdPrim prim) => _prim = prim;')
        lines.append("")
        lines.append("    /// <summary>Gets the prim this facade reads and writes.</summary>")
        lines.append("    public UsdPrim Prim => _prim;")
        lines.append("")
        if typed:
            lines.append(
                "    /// <summary>Reports whether the prim carries this concrete type.</summary>")
            lines.append("    /// <param name=\"prim\">The prim to test.</param>")
            lines.append("    public static bool IsA(UsdPrim prim) =>")
            lines.append(
                "        string.Equals(prim.TypeName, SchemaIdentifier, "
                "System.StringComparison.Ordinal);")
            lines.append("")
            lines.append(
                "    /// <summary>Defines a prim of this type and returns a facade over it."
                "</summary>")
            lines.append("    /// <param name=\"stage\">The stage to author on.</param>")
            lines.append("    /// <param name=\"path\">The absolute prim path to define.</param>")
            lines.append(f'    public static {cls["name"]} Define(UsdStage stage, string path) =>')
            lines.append("        new(stage.DefinePrim(path, SchemaIdentifier));")
        else:
            lines.append(
                "    /// <summary>Reports whether the prim already has this API schema applied."
                "</summary>")
            lines.append("    /// <param name=\"prim\">The prim to test.</param>")
            lines.append("    public static bool Has(UsdPrim prim) =>")
            lines.append(
                "        System.Array.IndexOf(prim.GetAppliedSchemas(), SchemaIdentifier) >= 0;")
        lines.append("")
        lines.append(
            "    /// <summary>Returns a facade over the prim without checking composition."
            "</summary>")
        lines.append("    /// <param name=\"prim\">The prim to wrap.</param>")
        lines.append(f'    public static {cls["name"]} Wrap(UsdPrim prim) => new(prim);')
        for prop in sorted_properties(cls):
            lines.extend(render_property_members(cls, prop))
        lines.append("}")

    lines.append("")
    return "\n".join(lines)


def catalog_domain(cls: dict) -> str:
    name = cls["name"]
    if name not in CATALOG_DOMAINS:
        raise ValueError(
            f"Class '{name}' has no catalog domain. Add it to CATALOG_DOMAINS so the "
            "generic physics editor can file it under a domain instead of guessing.")
    return CATALOG_DOMAINS[name]


def catalog_default_text(prop: dict) -> str:
    if prop["type"] == "rel" or "default" not in prop:
        return ""
    return format_value(prop["type"], prop["default"], boolean_as_int=False)


def render_catalog_csharp(definition: dict) -> str:
    lines = [CSHARP_HEADER.rstrip("\n"), ""]
    lines.append("using OpenUsd.Physics;")
    lines.append("")
    lines.append(f"namespace {CSHARP_NAMESPACE};")
    lines.append("")
    lines.append("/// <summary>Identifies the value one openUsdPhysics property carries.</summary>")
    lines.append("public enum OpenUsdPhysicsValueKind")
    lines.append("{")
    kinds = sorted(set(CATALOG_VALUE_KINDS.values()))
    for index, kind in enumerate(kinds):
        lines.append(f"    /// <summary>The <c>{kind}</c> value kind.</summary>")
        lines.append(f"    {kind}{',' if index + 1 < len(kinds) else ''}")
        if index + 1 < len(kinds):
            lines.append("")
    lines.append("}")
    lines.append("")
    lines.append("/// <summary>Identifies the simulation domain one openUsdPhysics schema belongs to.</summary>")
    lines.append("public enum OpenUsdPhysicsSchemaDomain")
    lines.append("{")
    for index, domain in enumerate(CATALOG_DOMAIN_ORDER):
        lines.append(
            f'    /// <summary>{xml_doc(CATALOG_DOMAIN_DOCS[domain])}</summary>')
        lines.append(f"    {domain}{',' if index + 1 < len(CATALOG_DOMAIN_ORDER) else ''}")
        if index + 1 < len(CATALOG_DOMAIN_ORDER):
            lines.append("")
    lines.append("}")
    lines.append("")
    lines.extend([
        "/// <summary>Describes one authorable openUsdPhysics property.</summary>",
        "/// <param name=\"Name\">The namespaced property name authored on the prim.</param>",
        "/// <param name=\"DisplayName\">The label an editor shows.</param>",
        "/// <param name=\"Documentation\">The sentence describing what the property does.</param>",
        "/// <param name=\"Kind\">The value the property carries.</param>",
        "/// <param name=\"IsUniform\">Whether the property is uniform and carries no time samples.</param>",
        "/// <param name=\"DefaultText\">The schema fallback, formatted the way USD writes it.</param>",
        "/// <param name=\"AllowedTokens\">The tokens a token property accepts, or an empty list.</param>",
        "public sealed record OpenUsdPhysicsPropertyDescriptor(",
        "    string Name,",
        "    string DisplayName,",
        "    string Documentation,",
        "    OpenUsdPhysicsValueKind Kind,",
        "    bool IsUniform,",
        "    string DefaultText,",
        "    IReadOnlyList<string> AllowedTokens)",
        "{",
        "    /// <summary>",
        "    /// Gets a value indicating whether an editor can author this property as a scalar.",
        "    /// </summary>",
        "    /// <remarks>",
        "    /// Arrays and relationships are described but not authorable through a scalar field. A",
        "    /// text box that pretended to edit a point array would either silently discard the",
        "    /// authored opinion or write a value the schema does not accept.",
        "    /// </remarks>",
        "    public bool IsScalar => Kind is OpenUsdPhysicsValueKind.Bool",
        "        or OpenUsdPhysicsValueKind.Int64",
        "        or OpenUsdPhysicsValueKind.Double",
        "        or OpenUsdPhysicsValueKind.String",
        "        or OpenUsdPhysicsValueKind.Token",
        "        or OpenUsdPhysicsValueKind.Float3;",
        "}",
        "",
        "/// <summary>Describes one openUsdPhysics schema and every property it declares.</summary>",
        "/// <param name=\"Identifier\">The schema identifier authored in <c>apiSchemas</c> or as a type.</param>",
        "/// <param name=\"Documentation\">The sentence describing what the schema models.</param>",
        "/// <param name=\"Domain\">The simulation domain the schema belongs to.</param>",
        "/// <param name=\"RequiredCapability\">The capability a built world must report.</param>",
        "/// <param name=\"IsTyped\">Whether the schema is a concrete prim type rather than an API schema.</param>",
        "/// <param name=\"Properties\">Every declared property, ordered by name.</param>",
        "public sealed record OpenUsdPhysicsSchemaDescriptor(",
        "    string Identifier,",
        "    string Documentation,",
        "    OpenUsdPhysicsSchemaDomain Domain,",
        "    UsdPhysicsCapability RequiredCapability,",
        "    bool IsTyped,",
        "    IReadOnlyList<OpenUsdPhysicsPropertyDescriptor> Properties);",
        "",
        "/// <summary>",
        "/// The machine-readable description of every openUsdPhysics schema property.",
        "/// </summary>",
        "/// <remarks>",
        "/// <para>",
        "/// The catalog exists so an editor can present every domain - including one whose runtime",
        "/// support is still being built - without hard-coding a field list per domain. A schema added",
        "/// to the definition shows up here, and therefore in every generic editor, without any editor",
        "/// change at all.",
        "/// </para>",
        "/// <para>",
        "/// It is generated from the same definition the schema, the plugin, and the managed facades",
        "/// are generated from, so a catalog entry can never describe a property the schema does not",
        "/// declare.",
        "/// </para>",
        "/// </remarks>",
        f"public static class {CSHARP_CATALOG_CLASS}",
        "{",
    ])

    ordered = sorted(
        definition["classes"],
        key=lambda cls: (
            CATALOG_DOMAIN_ORDER.index(catalog_domain(cls)),
            cls["name"]))

    for cls in ordered:
        domain = catalog_domain(cls)
        lines.append("")
        lines.append(
            f'    /// <summary>Describes <c>{xml_doc(cls["name"])}</c>.</summary>')
        lines.append(
            f'    public static OpenUsdPhysicsSchemaDescriptor {cls["className"]} {{ get; }} = new(')
        lines.append(f'        "{cls["name"]}",')
        lines.append(f'        "{escape_csharp(cls["doc"])}",')
        lines.append(f"        OpenUsdPhysicsSchemaDomain.{domain},")
        lines.append(
            f"        UsdPhysicsCapability.{CATALOG_CAPABILITIES[domain]},")
        lines.append(
            f'        IsTyped: {"true" if cls["kind"] == "concreteTyped" else "false"},')
        lines.append("        [")
        for prop in sorted_properties(cls):
            tokens = prop.get("allowedTokens", [])
            token_text = ", ".join(f'"{escape_csharp(entry)}"' for entry in tokens)
            lines.append("            new(")
            lines.append(f'                {CSHARP_TOKENS_CLASS}.{token_name(prop)},')
            lines.append(f'                "{escape_csharp(prop["displayName"])}",')
            lines.append(f'                "{escape_csharp(prop["doc"])}",')
            lines.append(
                f'                OpenUsdPhysicsValueKind.{CATALOG_VALUE_KINDS[prop["type"]]},')
            lines.append(
                f'                IsUniform: {"true" if prop.get("uniform") else "false"},')
            lines.append(f'                "{escape_csharp(catalog_default_text(prop))}",')
            lines.append(f"                [{token_text}]),")
        lines.append("        ]);")

    lines.append("")
    lines.append("    /// <summary>Gets every described schema, ordered by domain and identifier.</summary>")
    lines.append("    public static IReadOnlyList<OpenUsdPhysicsSchemaDescriptor> Schemas { get; } =")
    lines.append("    [")
    for cls in ordered:
        lines.append(f'        {cls["className"]},')
    lines.append("    ];")
    lines.extend([
        "",
        "    /// <summary>Finds the descriptor of one schema identifier.</summary>",
        "    /// <param name=\"identifier\">The schema identifier to look up.</param>",
        "    /// <param name=\"descriptor\">Receives the descriptor when one is described.</param>",
        "    /// <returns><see langword=\"true\"/> when the identifier is described.</returns>",
        "    public static bool TryGetSchema(",
        "        string identifier,",
        "        out OpenUsdPhysicsSchemaDescriptor? descriptor)",
        "    {",
        "        ArgumentNullException.ThrowIfNull(identifier);",
        "        for (int index = 0; index < Schemas.Count; index++)",
        "        {",
        "            if (string.Equals(Schemas[index].Identifier, identifier, StringComparison.Ordinal))",
        "            {",
        "                descriptor = Schemas[index];",
        "                return true;",
        "            }",
        "        }",
        "",
        "        descriptor = null;",
        "        return false;",
        "    }",
        "",
        "    /// <summary>Finds the descriptor of one namespaced property name.</summary>",
        "    /// <param name=\"name\">The namespaced property name.</param>",
        "    /// <param name=\"descriptor\">Receives the descriptor when one is described.</param>",
        "    /// <returns><see langword=\"true\"/> when the property is described.</returns>",
        "    public static bool TryGetProperty(",
        "        string name,",
        "        out OpenUsdPhysicsPropertyDescriptor? descriptor)",
        "    {",
        "        ArgumentNullException.ThrowIfNull(name);",
        "        for (int index = 0; index < Schemas.Count; index++)",
        "        {",
        "            IReadOnlyList<OpenUsdPhysicsPropertyDescriptor> properties = Schemas[index].Properties;",
        "            for (int property = 0; property < properties.Count; property++)",
        "            {",
        "                if (string.Equals(properties[property].Name, name, StringComparison.Ordinal))",
        "                {",
        "                    descriptor = properties[property];",
        "                    return true;",
        "                }",
        "            }",
        "        }",
        "",
        "        descriptor = null;",
        "        return false;",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def escape_csharp(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_public_api_lines(definition: dict) -> list:
    lines = []
    for cls in definition["classes"]:
        typed = cls["kind"] == "concreteTyped"
        full = f'{CSHARP_NAMESPACE}.{cls["name"]}'
        lines.append(full)
        lines.append(f'{full}.{cls["name"]}() -> void')
        lines.append(f"{full}.Prim.get -> OpenUsd.UsdPrim")
        lines.append(
            f'const {full}.SchemaIdentifier = "{cls["name"]}" -> string!')
        if typed:
            lines.append(
                f"static {full}.Define(OpenUsd.UsdStage! stage, string! path) -> {full}")
            lines.append(f"static {full}.IsA(OpenUsd.UsdPrim prim) -> bool")
        else:
            lines.append(f"static {full}.Has(OpenUsd.UsdPrim prim) -> bool")
        lines.append(f"static {full}.Wrap(OpenUsd.UsdPrim prim) -> {full}")
        for prop in sorted_properties(cls):
            member = member_name(prop)
            if prop["type"] == "rel":
                lines.append(f"{full}.Clear{member}() -> void")
                lines.append(f"{full}.Get{member}() -> string![]!")
                lines.append(f"{full}.Set{member}(string![]! targets) -> void")
                continue
            api_type = CSHARP_TYPES[prop["type"]][1]
            lines.append(f"{full}.{member}.get -> {api_type}")
            lines.append(f"{full}.{member}.set -> void")

    tokens = f"{CSHARP_NAMESPACE}.{CSHARP_TOKENS_CLASS}"
    lines.append(tokens)
    lines.append(
        f'const {tokens}.PluginName = "{definition["library"]["name"]}" -> string!')
    lines.append(
        f'const {tokens}.PropertyNamespace = '
        f'"{definition["library"]["propertyNamespace"]}" -> string!')
    for cls in definition["classes"]:
        for prop in sorted_properties(cls):
            lines.append(
                f'const {tokens}.{token_name(prop)} = "{prop["name"]}" -> string!')

    catalog = f"{CSHARP_NAMESPACE}.{CSHARP_CATALOG_CLASS}"
    schema_type = f"{CSHARP_NAMESPACE}.OpenUsdPhysicsSchemaDescriptor"
    property_type = f"{CSHARP_NAMESPACE}.OpenUsdPhysicsPropertyDescriptor"
    lines.append(catalog)
    lines.append(
        f"static {catalog}.Schemas.get -> "
        f"System.Collections.Generic.IReadOnlyList<{schema_type}!>!")
    lines.append(
        f"static {catalog}.TryGetProperty(string! name, out {property_type}? descriptor) -> bool")
    lines.append(
        f"static {catalog}.TryGetSchema(string! identifier, out {schema_type}? descriptor) -> bool")
    for cls in definition["classes"]:
        lines.append(f'static {catalog}.{cls["className"]}.get -> {schema_type}!')
    return lines


def public_api_rank(line: str) -> int:
    if line.startswith("#"):
        return 0
    if line.startswith("~"):
        return 1
    if line.startswith("const "):
        return 2
    if line.startswith("static "):
        return 4
    return 3


def render_public_api(definition: dict, existing: str) -> str:
    owned_types = [f'{CSHARP_NAMESPACE}.{cls["name"]}' for cls in definition["classes"]]
    owned_types.append(f"{CSHARP_NAMESPACE}.{CSHARP_TOKENS_CLASS}")
    owned_types.append(f"{CSHARP_NAMESPACE}.{CSHARP_CATALOG_CLASS}")

    def is_owned(line: str) -> bool:
        symbol = line
        for prefix in ("~", "const ", "static ", "override ", "abstract ", "virtual "):
            while symbol.startswith(prefix):
                symbol = symbol[len(prefix):]
        for owned in owned_types:
            if symbol == owned or symbol.startswith(owned + "."):
                return True
        return False

    retained = [
        line for line in existing.splitlines()
        if line and not is_owned(line)
    ]
    merged = sorted(
        set(retained) | set(render_public_api_lines(definition)),
        key=lambda line: (public_api_rank(line), line))
    return "\n".join(merged) + "\n"


def write(path: Path, content: str, check: bool, stale: list) -> None:

    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return
    if check:
        stale.append(str(path))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {path}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when an artifact is out of date.")
    arguments = parser.parse_args()

    definition = json.loads(DEFINITION_PATH.read_text(encoding="utf-8"))
    validate(definition)

    stale: list = []
    write(SCHEMA_ROOT / "schema.usda",
          render_schema_usda(definition), arguments.check, stale)
    write(SCHEMA_ROOT / "resources" / "generatedSchema.usda",
          render_generated_schema(definition), arguments.check, stale)
    write(SCHEMA_ROOT / "resources" / "plugInfo.json",
          render_plug_info(definition), arguments.check, stale)
    write(SCHEMA_ROOT / "precedence-manifest.json",
          render_precedence_manifest(definition), arguments.check, stale)
    write(CSHARP_SCHEMA_DIR / "OpenUsdPhysicsTokens.g.cs",
          render_tokens_csharp(definition), arguments.check, stale)
    write(CSHARP_SCHEMA_DIR / "OpenUsdPhysicsSchemas.g.cs",
          render_schemas_csharp(definition), arguments.check, stale)
    write(CSHARP_SCHEMA_DIR / "OpenUsdPhysicsPropertyCatalog.g.cs",
          render_catalog_csharp(definition), arguments.check, stale)

    existing_api = (
        PUBLIC_API_PATH.read_text(encoding="utf-8")
        if PUBLIC_API_PATH.exists() else "#nullable enable\n")
    write(PUBLIC_API_PATH,
          render_public_api(definition, existing_api), arguments.check, stale)

    if stale:
        print("Out-of-date schema artifacts:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print(
            "Run python schemas/openUsdPhysics/tools/generate_schema.py",
            file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
