<Project>

  <PropertyGroup>
    <_OpenUsdImagingOsxArm64ResourceRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../runtimes/osx-arm64/resources'))</_OpenUsdImagingOsxArm64ResourceRoot>
  </PropertyGroup>

  <ItemGroup Condition="'$(RuntimeIdentifier)' == '' or '$(RuntimeIdentifier)' == 'osx-arm64'">
    <Content Include="$(_OpenUsdImagingOsxArm64ResourceRoot)/**/*">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
