// Copyright (c) marcschier. Licensed under the MIT License.
// <auto-generated>
//     Generated by schemas/openUsdPhysics/tools/generate_schema.py from
//     schemas/openUsdPhysics/openUsdPhysics.schema.json. Do not edit by hand.
// </auto-generated>
#nullable enable

namespace OpenUsd.Physics.Schema;

/// <summary>
/// Property names of the codeless <c>openUsdPhysics</c> schema plugin. Use these constants instead of
/// spelling a namespaced property name at a call site.
/// </summary>
public static class OpenUsdPhysicsTokens
{
    /// <summary>The property namespace every openUsdPhysics property lives in.</summary>
    public const string PropertyNamespace = "openUsdPhysics";

    /// <summary>The plugin name registered by the generated plugInfo.json.</summary>
    public const string PluginName = "openUsdPhysics";

    /// <summary>The <c>openUsdPhysics:scene:bounceThreshold</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneBounceThreshold = "openUsdPhysics:scene:bounceThreshold";

    /// <summary>The <c>openUsdPhysics:scene:broadPhaseType</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneBroadPhaseType = "openUsdPhysics:scene:broadPhaseType";

    /// <summary>The <c>openUsdPhysics:scene:enableCCD</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneEnableCCD = "openUsdPhysics:scene:enableCCD";

    /// <summary>The <c>openUsdPhysics:scene:enableEnhancedDeterminism</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneEnableEnhancedDeterminism = "openUsdPhysics:scene:enableEnhancedDeterminism";

    /// <summary>The <c>openUsdPhysics:scene:enableStabilization</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneEnableStabilization = "openUsdPhysics:scene:enableStabilization";

    /// <summary>The <c>openUsdPhysics:scene:frictionCorrelationDistance</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneFrictionCorrelationDistance = "openUsdPhysics:scene:frictionCorrelationDistance";

    /// <summary>The <c>openUsdPhysics:scene:frictionOffsetThreshold</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneFrictionOffsetThreshold = "openUsdPhysics:scene:frictionOffsetThreshold";

    /// <summary>The <c>openUsdPhysics:scene:frictionType</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneFrictionType = "openUsdPhysics:scene:frictionType";

    /// <summary>The <c>openUsdPhysics:scene:gpuRequestMode</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneGpuRequestMode = "openUsdPhysics:scene:gpuRequestMode";

    /// <summary>The <c>openUsdPhysics:scene:maxBiasCoefficient</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneMaxBiasCoefficient = "openUsdPhysics:scene:maxBiasCoefficient";

    /// <summary>The <c>openUsdPhysics:scene:maxSubStepCount</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneMaxSubStepCount = "openUsdPhysics:scene:maxSubStepCount";

    /// <summary>The <c>openUsdPhysics:scene:positionIterationCount</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string ScenePositionIterationCount = "openUsdPhysics:scene:positionIterationCount";

    /// <summary>The <c>openUsdPhysics:scene:reportContacts</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneReportContacts = "openUsdPhysics:scene:reportContacts";

    /// <summary>The <c>openUsdPhysics:scene:solverType</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneSolverType = "openUsdPhysics:scene:solverType";

    /// <summary>The <c>openUsdPhysics:scene:timeStepsPerSecond</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneTimeStepsPerSecond = "openUsdPhysics:scene:timeStepsPerSecond";

    /// <summary>The <c>openUsdPhysics:scene:velocityIterationCount</c> property of <c>OpenUsdPhysicsSceneAPI</c>.</summary>
    public const string SceneVelocityIterationCount = "openUsdPhysics:scene:velocityIterationCount";

    /// <summary>The <c>openUsdPhysics:body:contactSlopCoefficient</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyContactSlopCoefficient = "openUsdPhysics:body:contactSlopCoefficient";

    /// <summary>The <c>openUsdPhysics:body:disableGravity</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyDisableGravity = "openUsdPhysics:body:disableGravity";

    /// <summary>The <c>openUsdPhysics:body:enableCCD</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyEnableCCD = "openUsdPhysics:body:enableCCD";

    /// <summary>The <c>openUsdPhysics:body:enableSpeculativeCCD</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyEnableSpeculativeCCD = "openUsdPhysics:body:enableSpeculativeCCD";

    /// <summary>The <c>openUsdPhysics:body:lockedAngularAxes</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyLockedAngularAxes = "openUsdPhysics:body:lockedAngularAxes";

    /// <summary>The <c>openUsdPhysics:body:lockedLinearAxes</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyLockedLinearAxes = "openUsdPhysics:body:lockedLinearAxes";

    /// <summary>The <c>openUsdPhysics:body:maxAngularVelocity</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyMaxAngularVelocity = "openUsdPhysics:body:maxAngularVelocity";

    /// <summary>The <c>openUsdPhysics:body:maxContactImpulse</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyMaxContactImpulse = "openUsdPhysics:body:maxContactImpulse";

    /// <summary>The <c>openUsdPhysics:body:maxDepenetrationVelocity</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyMaxDepenetrationVelocity = "openUsdPhysics:body:maxDepenetrationVelocity";

    /// <summary>The <c>openUsdPhysics:body:maxLinearVelocity</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyMaxLinearVelocity = "openUsdPhysics:body:maxLinearVelocity";

    /// <summary>The <c>openUsdPhysics:body:positionIterationCount</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyPositionIterationCount = "openUsdPhysics:body:positionIterationCount";

    /// <summary>The <c>openUsdPhysics:body:retainAccelerations</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyRetainAccelerations = "openUsdPhysics:body:retainAccelerations";

    /// <summary>The <c>openUsdPhysics:body:sleepThreshold</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodySleepThreshold = "openUsdPhysics:body:sleepThreshold";

    /// <summary>The <c>openUsdPhysics:body:stabilizationThreshold</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyStabilizationThreshold = "openUsdPhysics:body:stabilizationThreshold";

    /// <summary>The <c>openUsdPhysics:body:velocityIterationCount</c> property of <c>OpenUsdPhysicsRigidBodySettingsAPI</c>.</summary>
    public const string BodyVelocityIterationCount = "openUsdPhysics:body:velocityIterationCount";

    /// <summary>The <c>openUsdPhysics:collision:contactImpulseThreshold</c> property of <c>OpenUsdPhysicsCollisionSettingsAPI</c>.</summary>
    public const string CollisionContactImpulseThreshold = "openUsdPhysics:collision:contactImpulseThreshold";

    /// <summary>The <c>openUsdPhysics:collision:contactOffset</c> property of <c>OpenUsdPhysicsCollisionSettingsAPI</c>.</summary>
    public const string CollisionContactOffset = "openUsdPhysics:collision:contactOffset";

    /// <summary>The <c>openUsdPhysics:collision:minTorsionalPatchRadius</c> property of <c>OpenUsdPhysicsCollisionSettingsAPI</c>.</summary>
    public const string CollisionMinTorsionalPatchRadius = "openUsdPhysics:collision:minTorsionalPatchRadius";

    /// <summary>The <c>openUsdPhysics:collision:reportContacts</c> property of <c>OpenUsdPhysicsCollisionSettingsAPI</c>.</summary>
    public const string CollisionReportContacts = "openUsdPhysics:collision:reportContacts";

    /// <summary>The <c>openUsdPhysics:collision:restOffset</c> property of <c>OpenUsdPhysicsCollisionSettingsAPI</c>.</summary>
    public const string CollisionRestOffset = "openUsdPhysics:collision:restOffset";

    /// <summary>The <c>openUsdPhysics:collision:torsionalPatchRadius</c> property of <c>OpenUsdPhysicsCollisionSettingsAPI</c>.</summary>
    public const string CollisionTorsionalPatchRadius = "openUsdPhysics:collision:torsionalPatchRadius";

    /// <summary>The <c>openUsdPhysics:material:compliantContactDamping</c> property of <c>OpenUsdPhysicsMaterialSettingsAPI</c>.</summary>
    public const string MaterialCompliantContactDamping = "openUsdPhysics:material:compliantContactDamping";

    /// <summary>The <c>openUsdPhysics:material:compliantContactStiffness</c> property of <c>OpenUsdPhysicsMaterialSettingsAPI</c>.</summary>
    public const string MaterialCompliantContactStiffness = "openUsdPhysics:material:compliantContactStiffness";

    /// <summary>The <c>openUsdPhysics:material:frictionCombineMode</c> property of <c>OpenUsdPhysicsMaterialSettingsAPI</c>.</summary>
    public const string MaterialFrictionCombineMode = "openUsdPhysics:material:frictionCombineMode";

    /// <summary>The <c>openUsdPhysics:material:improvePatchFriction</c> property of <c>OpenUsdPhysicsMaterialSettingsAPI</c>.</summary>
    public const string MaterialImprovePatchFriction = "openUsdPhysics:material:improvePatchFriction";

    /// <summary>The <c>openUsdPhysics:material:restitutionCombineMode</c> property of <c>OpenUsdPhysicsMaterialSettingsAPI</c>.</summary>
    public const string MaterialRestitutionCombineMode = "openUsdPhysics:material:restitutionCombineMode";

    /// <summary>The <c>openUsdPhysics:articulation:enabledSelfCollisions</c> property of <c>OpenUsdPhysicsArticulationSettingsAPI</c>.</summary>
    public const string ArticulationEnabledSelfCollisions = "openUsdPhysics:articulation:enabledSelfCollisions";

    /// <summary>The <c>openUsdPhysics:articulation:fixBase</c> property of <c>OpenUsdPhysicsArticulationSettingsAPI</c>.</summary>
    public const string ArticulationFixBase = "openUsdPhysics:articulation:fixBase";

    /// <summary>The <c>openUsdPhysics:articulation:positionIterationCount</c> property of <c>OpenUsdPhysicsArticulationSettingsAPI</c>.</summary>
    public const string ArticulationPositionIterationCount = "openUsdPhysics:articulation:positionIterationCount";

    /// <summary>The <c>openUsdPhysics:articulation:sleepThreshold</c> property of <c>OpenUsdPhysicsArticulationSettingsAPI</c>.</summary>
    public const string ArticulationSleepThreshold = "openUsdPhysics:articulation:sleepThreshold";

    /// <summary>The <c>openUsdPhysics:articulation:stabilizationThreshold</c> property of <c>OpenUsdPhysicsArticulationSettingsAPI</c>.</summary>
    public const string ArticulationStabilizationThreshold = "openUsdPhysics:articulation:stabilizationThreshold";

    /// <summary>The <c>openUsdPhysics:articulation:velocityIterationCount</c> property of <c>OpenUsdPhysicsArticulationSettingsAPI</c>.</summary>
    public const string ArticulationVelocityIterationCount = "openUsdPhysics:articulation:velocityIterationCount";

    /// <summary>The <c>openUsdPhysics:simulation:identity</c> property of <c>OpenUsdPhysicsSimulationMetadataAPI</c>.</summary>
    public const string SimulationIdentity = "openUsdPhysics:simulation:identity";

    /// <summary>The <c>openUsdPhysics:simulation:identityDomain</c> property of <c>OpenUsdPhysicsSimulationMetadataAPI</c>.</summary>
    public const string SimulationIdentityDomain = "openUsdPhysics:simulation:identityDomain";

    /// <summary>The <c>openUsdPhysics:simulation:identityIndex</c> property of <c>OpenUsdPhysicsSimulationMetadataAPI</c>.</summary>
    public const string SimulationIdentityIndex = "openUsdPhysics:simulation:identityIndex";

    /// <summary>The <c>openUsdPhysics:simulation:schemaVersion</c> property of <c>OpenUsdPhysicsSimulationMetadataAPI</c>.</summary>
    public const string SimulationSchemaVersion = "openUsdPhysics:simulation:schemaVersion";

    /// <summary>The <c>openUsdPhysics:simulation:sourceRevision</c> property of <c>OpenUsdPhysicsSimulationMetadataAPI</c>.</summary>
    public const string SimulationSourceRevision = "openUsdPhysics:simulation:sourceRevision";

    /// <summary>The <c>openUsdPhysics:controller:climbingMode</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerClimbingMode = "openUsdPhysics:controller:climbingMode";

    /// <summary>The <c>openUsdPhysics:controller:contactOffset</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerContactOffset = "openUsdPhysics:controller:contactOffset";

    /// <summary>The <c>openUsdPhysics:controller:density</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerDensity = "openUsdPhysics:controller:density";

    /// <summary>The <c>openUsdPhysics:controller:enabled</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerEnabled = "openUsdPhysics:controller:enabled";

    /// <summary>The <c>openUsdPhysics:controller:halfExtents</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerHalfExtents = "openUsdPhysics:controller:halfExtents";

    /// <summary>The <c>openUsdPhysics:controller:height</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerHeight = "openUsdPhysics:controller:height";

    /// <summary>The <c>openUsdPhysics:controller:invisibleWallHeight</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerInvisibleWallHeight = "openUsdPhysics:controller:invisibleWallHeight";

    /// <summary>The <c>openUsdPhysics:controller:material</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerMaterial = "openUsdPhysics:controller:material";

    /// <summary>The <c>openUsdPhysics:controller:maxJumpHeight</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerMaxJumpHeight = "openUsdPhysics:controller:maxJumpHeight";

    /// <summary>The <c>openUsdPhysics:controller:minMoveDistance</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerMinMoveDistance = "openUsdPhysics:controller:minMoveDistance";

    /// <summary>The <c>openUsdPhysics:controller:nonWalkableMode</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerNonWalkableMode = "openUsdPhysics:controller:nonWalkableMode";

    /// <summary>The <c>openUsdPhysics:controller:radius</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerRadius = "openUsdPhysics:controller:radius";

    /// <summary>The <c>openUsdPhysics:controller:scaleCoeff</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerScaleCoeff = "openUsdPhysics:controller:scaleCoeff";

    /// <summary>The <c>openUsdPhysics:controller:shapeType</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerShapeType = "openUsdPhysics:controller:shapeType";

    /// <summary>The <c>openUsdPhysics:controller:simulationOwner</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerSimulationOwner = "openUsdPhysics:controller:simulationOwner";

    /// <summary>The <c>openUsdPhysics:controller:slopeLimit</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerSlopeLimit = "openUsdPhysics:controller:slopeLimit";

    /// <summary>The <c>openUsdPhysics:controller:stepOffset</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerStepOffset = "openUsdPhysics:controller:stepOffset";

    /// <summary>The <c>openUsdPhysics:controller:upAxis</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerUpAxis = "openUsdPhysics:controller:upAxis";

    /// <summary>The <c>openUsdPhysics:controller:volumeGrowth</c> property of <c>OpenUsdPhysicsCharacterControllerAPI</c>.</summary>
    public const string ControllerVolumeGrowth = "openUsdPhysics:controller:volumeGrowth";

    /// <summary>The <c>openUsdPhysics:vehicle:driveType</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleDriveType = "openUsdPhysics:vehicle:driveType";

    /// <summary>The <c>openUsdPhysics:vehicle:drivetrain</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleDrivetrain = "openUsdPhysics:vehicle:drivetrain";

    /// <summary>The <c>openUsdPhysics:vehicle:enabled</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleEnabled = "openUsdPhysics:vehicle:enabled";

    /// <summary>The <c>openUsdPhysics:vehicle:lateralAxis</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleLateralAxis = "openUsdPhysics:vehicle:lateralAxis";

    /// <summary>The <c>openUsdPhysics:vehicle:lateralStickyTireDamping</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleLateralStickyTireDamping = "openUsdPhysics:vehicle:lateralStickyTireDamping";

    /// <summary>The <c>openUsdPhysics:vehicle:lateralStickyTireThresholdSpeed</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleLateralStickyTireThresholdSpeed = "openUsdPhysics:vehicle:lateralStickyTireThresholdSpeed";

    /// <summary>The <c>openUsdPhysics:vehicle:lateralStickyTireThresholdTime</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleLateralStickyTireThresholdTime = "openUsdPhysics:vehicle:lateralStickyTireThresholdTime";

    /// <summary>The <c>openUsdPhysics:vehicle:longitudinalAxis</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleLongitudinalAxis = "openUsdPhysics:vehicle:longitudinalAxis";

    /// <summary>The <c>openUsdPhysics:vehicle:longitudinalStickyTireDamping</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleLongitudinalStickyTireDamping = "openUsdPhysics:vehicle:longitudinalStickyTireDamping";

    /// <summary>The <c>openUsdPhysics:vehicle:longitudinalStickyTireThresholdSpeed</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleLongitudinalStickyTireThresholdSpeed = "openUsdPhysics:vehicle:longitudinalStickyTireThresholdSpeed";

    /// <summary>The <c>openUsdPhysics:vehicle:longitudinalStickyTireThresholdTime</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleLongitudinalStickyTireThresholdTime = "openUsdPhysics:vehicle:longitudinalStickyTireThresholdTime";

    /// <summary>The <c>openUsdPhysics:vehicle:minActiveLongitudinalSlipDenominator</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleMinActiveLongitudinalSlipDenominator = "openUsdPhysics:vehicle:minActiveLongitudinalSlipDenominator";

    /// <summary>The <c>openUsdPhysics:vehicle:minLateralSlipDenominator</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleMinLateralSlipDenominator = "openUsdPhysics:vehicle:minLateralSlipDenominator";

    /// <summary>The <c>openUsdPhysics:vehicle:minPassiveLongitudinalSlipDenominator</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleMinPassiveLongitudinalSlipDenominator = "openUsdPhysics:vehicle:minPassiveLongitudinalSlipDenominator";

    /// <summary>The <c>openUsdPhysics:vehicle:subStepCountHighSpeed</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleSubStepCountHighSpeed = "openUsdPhysics:vehicle:subStepCountHighSpeed";

    /// <summary>The <c>openUsdPhysics:vehicle:subStepCountLowSpeed</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleSubStepCountLowSpeed = "openUsdPhysics:vehicle:subStepCountLowSpeed";

    /// <summary>The <c>openUsdPhysics:vehicle:subStepThresholdLongitudinalSpeed</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleSubStepThresholdLongitudinalSpeed = "openUsdPhysics:vehicle:subStepThresholdLongitudinalSpeed";

    /// <summary>The <c>openUsdPhysics:vehicle:suspensionQueryType</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleSuspensionQueryType = "openUsdPhysics:vehicle:suspensionQueryType";

    /// <summary>The <c>openUsdPhysics:vehicle:verticalAxis</c> property of <c>OpenUsdPhysicsVehicleAPI</c>.</summary>
    public const string VehicleVerticalAxis = "openUsdPhysics:vehicle:verticalAxis";

    /// <summary>The <c>openUsdPhysics:wheelAttachment:index</c> property of <c>OpenUsdPhysicsVehicleWheelAttachmentAPI</c>.</summary>
    public const string WheelAttachmentIndex = "openUsdPhysics:wheelAttachment:index";

    /// <summary>The <c>openUsdPhysics:wheelAttachment:suspension</c> property of <c>OpenUsdPhysicsVehicleWheelAttachmentAPI</c>.</summary>
    public const string WheelAttachmentSuspension = "openUsdPhysics:wheelAttachment:suspension";

    /// <summary>The <c>openUsdPhysics:wheelAttachment:suspensionFrameOrientation</c> property of <c>OpenUsdPhysicsVehicleWheelAttachmentAPI</c>.</summary>
    public const string WheelAttachmentSuspensionFrameOrientation = "openUsdPhysics:wheelAttachment:suspensionFrameOrientation";

    /// <summary>The <c>openUsdPhysics:wheelAttachment:suspensionFramePosition</c> property of <c>OpenUsdPhysicsVehicleWheelAttachmentAPI</c>.</summary>
    public const string WheelAttachmentSuspensionFramePosition = "openUsdPhysics:wheelAttachment:suspensionFramePosition";

    /// <summary>The <c>openUsdPhysics:wheelAttachment:suspensionTravelDirection</c> property of <c>OpenUsdPhysicsVehicleWheelAttachmentAPI</c>.</summary>
    public const string WheelAttachmentSuspensionTravelDirection = "openUsdPhysics:wheelAttachment:suspensionTravelDirection";

    /// <summary>The <c>openUsdPhysics:wheelAttachment:tire</c> property of <c>OpenUsdPhysicsVehicleWheelAttachmentAPI</c>.</summary>
    public const string WheelAttachmentTire = "openUsdPhysics:wheelAttachment:tire";

    /// <summary>The <c>openUsdPhysics:wheelAttachment:wheel</c> property of <c>OpenUsdPhysicsVehicleWheelAttachmentAPI</c>.</summary>
    public const string WheelAttachmentWheel = "openUsdPhysics:wheelAttachment:wheel";

    /// <summary>The <c>openUsdPhysics:wheelAttachment:wheelFrameOrientation</c> property of <c>OpenUsdPhysicsVehicleWheelAttachmentAPI</c>.</summary>
    public const string WheelAttachmentWheelFrameOrientation = "openUsdPhysics:wheelAttachment:wheelFrameOrientation";

    /// <summary>The <c>openUsdPhysics:wheelAttachment:wheelFramePosition</c> property of <c>OpenUsdPhysicsVehicleWheelAttachmentAPI</c>.</summary>
    public const string WheelAttachmentWheelFramePosition = "openUsdPhysics:wheelAttachment:wheelFramePosition";

    /// <summary>The <c>openUsdPhysics:wheel:dampingRate</c> property of <c>OpenUsdPhysicsVehicleWheelAPI</c>.</summary>
    public const string WheelDampingRate = "openUsdPhysics:wheel:dampingRate";

    /// <summary>The <c>openUsdPhysics:wheel:mass</c> property of <c>OpenUsdPhysicsVehicleWheelAPI</c>.</summary>
    public const string WheelMass = "openUsdPhysics:wheel:mass";

    /// <summary>The <c>openUsdPhysics:wheel:momentOfInertia</c> property of <c>OpenUsdPhysicsVehicleWheelAPI</c>.</summary>
    public const string WheelMomentOfInertia = "openUsdPhysics:wheel:momentOfInertia";

    /// <summary>The <c>openUsdPhysics:wheel:radius</c> property of <c>OpenUsdPhysicsVehicleWheelAPI</c>.</summary>
    public const string WheelRadius = "openUsdPhysics:wheel:radius";

    /// <summary>The <c>openUsdPhysics:wheel:toeAngle</c> property of <c>OpenUsdPhysicsVehicleWheelAPI</c>.</summary>
    public const string WheelToeAngle = "openUsdPhysics:wheel:toeAngle";

    /// <summary>The <c>openUsdPhysics:wheel:width</c> property of <c>OpenUsdPhysicsVehicleWheelAPI</c>.</summary>
    public const string WheelWidth = "openUsdPhysics:wheel:width";

    /// <summary>The <c>openUsdPhysics:suspension:camberAtMaxCompression</c> property of <c>OpenUsdPhysicsVehicleSuspensionAPI</c>.</summary>
    public const string SuspensionCamberAtMaxCompression = "openUsdPhysics:suspension:camberAtMaxCompression";

    /// <summary>The <c>openUsdPhysics:suspension:camberAtMaxDroop</c> property of <c>OpenUsdPhysicsVehicleSuspensionAPI</c>.</summary>
    public const string SuspensionCamberAtMaxDroop = "openUsdPhysics:suspension:camberAtMaxDroop";

    /// <summary>The <c>openUsdPhysics:suspension:camberAtRest</c> property of <c>OpenUsdPhysicsVehicleSuspensionAPI</c>.</summary>
    public const string SuspensionCamberAtRest = "openUsdPhysics:suspension:camberAtRest";

    /// <summary>The <c>openUsdPhysics:suspension:springDamperRate</c> property of <c>OpenUsdPhysicsVehicleSuspensionAPI</c>.</summary>
    public const string SuspensionSpringDamperRate = "openUsdPhysics:suspension:springDamperRate";

    /// <summary>The <c>openUsdPhysics:suspension:springStrength</c> property of <c>OpenUsdPhysicsVehicleSuspensionAPI</c>.</summary>
    public const string SuspensionSpringStrength = "openUsdPhysics:suspension:springStrength";

    /// <summary>The <c>openUsdPhysics:suspension:sprungMass</c> property of <c>OpenUsdPhysicsVehicleSuspensionAPI</c>.</summary>
    public const string SuspensionSprungMass = "openUsdPhysics:suspension:sprungMass";

    /// <summary>The <c>openUsdPhysics:suspension:travelDistance</c> property of <c>OpenUsdPhysicsVehicleSuspensionAPI</c>.</summary>
    public const string SuspensionTravelDistance = "openUsdPhysics:suspension:travelDistance";

    /// <summary>The <c>openUsdPhysics:tire:camberStiffness</c> property of <c>OpenUsdPhysicsVehicleTireAPI</c>.</summary>
    public const string TireCamberStiffness = "openUsdPhysics:tire:camberStiffness";

    /// <summary>The <c>openUsdPhysics:tire:frictionTable</c> property of <c>OpenUsdPhysicsVehicleTireAPI</c>.</summary>
    public const string TireFrictionTable = "openUsdPhysics:tire:frictionTable";

    /// <summary>The <c>openUsdPhysics:tire:frictionVsSlipGraph</c> property of <c>OpenUsdPhysicsVehicleTireAPI</c>.</summary>
    public const string TireFrictionVsSlipGraph = "openUsdPhysics:tire:frictionVsSlipGraph";

    /// <summary>The <c>openUsdPhysics:tire:lateralStiffnessGraph</c> property of <c>OpenUsdPhysicsVehicleTireAPI</c>.</summary>
    public const string TireLateralStiffnessGraph = "openUsdPhysics:tire:lateralStiffnessGraph";

    /// <summary>The <c>openUsdPhysics:tire:longitudinalStiffness</c> property of <c>OpenUsdPhysicsVehicleTireAPI</c>.</summary>
    public const string TireLongitudinalStiffness = "openUsdPhysics:tire:longitudinalStiffness";

    /// <summary>The <c>openUsdPhysics:tire:restLoad</c> property of <c>OpenUsdPhysicsVehicleTireAPI</c>.</summary>
    public const string TireRestLoad = "openUsdPhysics:tire:restLoad";

    /// <summary>The <c>openUsdPhysics:frictionTable:defaultFrictionValue</c> property of <c>OpenUsdPhysicsVehicleTireFrictionTable</c>.</summary>
    public const string FrictionTableDefaultFrictionValue = "openUsdPhysics:frictionTable:defaultFrictionValue";

    /// <summary>The <c>openUsdPhysics:frictionTable:frictionValues</c> property of <c>OpenUsdPhysicsVehicleTireFrictionTable</c>.</summary>
    public const string FrictionTableFrictionValues = "openUsdPhysics:frictionTable:frictionValues";

    /// <summary>The <c>openUsdPhysics:frictionTable:groundMaterials</c> property of <c>OpenUsdPhysicsVehicleTireFrictionTable</c>.</summary>
    public const string FrictionTableGroundMaterials = "openUsdPhysics:frictionTable:groundMaterials";

    /// <summary>The <c>openUsdPhysics:engine:dampingRateFullThrottle</c> property of <c>OpenUsdPhysicsVehicleEngineAPI</c>.</summary>
    public const string EngineDampingRateFullThrottle = "openUsdPhysics:engine:dampingRateFullThrottle";

    /// <summary>The <c>openUsdPhysics:engine:dampingRateZeroThrottleClutchDisengaged</c> property of <c>OpenUsdPhysicsVehicleEngineAPI</c>.</summary>
    public const string EngineDampingRateZeroThrottleClutchDisengaged = "openUsdPhysics:engine:dampingRateZeroThrottleClutchDisengaged";

    /// <summary>The <c>openUsdPhysics:engine:dampingRateZeroThrottleClutchEngaged</c> property of <c>OpenUsdPhysicsVehicleEngineAPI</c>.</summary>
    public const string EngineDampingRateZeroThrottleClutchEngaged = "openUsdPhysics:engine:dampingRateZeroThrottleClutchEngaged";

    /// <summary>The <c>openUsdPhysics:engine:idleRotationSpeed</c> property of <c>OpenUsdPhysicsVehicleEngineAPI</c>.</summary>
    public const string EngineIdleRotationSpeed = "openUsdPhysics:engine:idleRotationSpeed";

    /// <summary>The <c>openUsdPhysics:engine:maxRotationSpeed</c> property of <c>OpenUsdPhysicsVehicleEngineAPI</c>.</summary>
    public const string EngineMaxRotationSpeed = "openUsdPhysics:engine:maxRotationSpeed";

    /// <summary>The <c>openUsdPhysics:engine:momentOfInertia</c> property of <c>OpenUsdPhysicsVehicleEngineAPI</c>.</summary>
    public const string EngineMomentOfInertia = "openUsdPhysics:engine:momentOfInertia";

    /// <summary>The <c>openUsdPhysics:engine:peakTorque</c> property of <c>OpenUsdPhysicsVehicleEngineAPI</c>.</summary>
    public const string EnginePeakTorque = "openUsdPhysics:engine:peakTorque";

    /// <summary>The <c>openUsdPhysics:engine:torqueCurve</c> property of <c>OpenUsdPhysicsVehicleEngineAPI</c>.</summary>
    public const string EngineTorqueCurve = "openUsdPhysics:engine:torqueCurve";

    /// <summary>The <c>openUsdPhysics:gears:ratioScale</c> property of <c>OpenUsdPhysicsVehicleGearsAPI</c>.</summary>
    public const string GearsRatioScale = "openUsdPhysics:gears:ratioScale";

    /// <summary>The <c>openUsdPhysics:gears:ratios</c> property of <c>OpenUsdPhysicsVehicleGearsAPI</c>.</summary>
    public const string GearsRatios = "openUsdPhysics:gears:ratios";

    /// <summary>The <c>openUsdPhysics:gears:switchTime</c> property of <c>OpenUsdPhysicsVehicleGearsAPI</c>.</summary>
    public const string GearsSwitchTime = "openUsdPhysics:gears:switchTime";

    /// <summary>The <c>openUsdPhysics:autoGearBox:downRatios</c> property of <c>OpenUsdPhysicsVehicleAutoGearBoxAPI</c>.</summary>
    public const string AutoGearBoxDownRatios = "openUsdPhysics:autoGearBox:downRatios";

    /// <summary>The <c>openUsdPhysics:autoGearBox:latency</c> property of <c>OpenUsdPhysicsVehicleAutoGearBoxAPI</c>.</summary>
    public const string AutoGearBoxLatency = "openUsdPhysics:autoGearBox:latency";

    /// <summary>The <c>openUsdPhysics:autoGearBox:upRatios</c> property of <c>OpenUsdPhysicsVehicleAutoGearBoxAPI</c>.</summary>
    public const string AutoGearBoxUpRatios = "openUsdPhysics:autoGearBox:upRatios";

    /// <summary>The <c>openUsdPhysics:clutch:accuracyMode</c> property of <c>OpenUsdPhysicsVehicleClutchAPI</c>.</summary>
    public const string ClutchAccuracyMode = "openUsdPhysics:clutch:accuracyMode";

    /// <summary>The <c>openUsdPhysics:clutch:estimateIterations</c> property of <c>OpenUsdPhysicsVehicleClutchAPI</c>.</summary>
    public const string ClutchEstimateIterations = "openUsdPhysics:clutch:estimateIterations";

    /// <summary>The <c>openUsdPhysics:clutch:strength</c> property of <c>OpenUsdPhysicsVehicleClutchAPI</c>.</summary>
    public const string ClutchStrength = "openUsdPhysics:clutch:strength";

    /// <summary>The <c>openUsdPhysics:differential:averageWheelSpeedRatios</c> property of <c>OpenUsdPhysicsVehicleDifferentialAPI</c>.</summary>
    public const string DifferentialAverageWheelSpeedRatios = "openUsdPhysics:differential:averageWheelSpeedRatios";

    /// <summary>The <c>openUsdPhysics:differential:torqueRatios</c> property of <c>OpenUsdPhysicsVehicleDifferentialAPI</c>.</summary>
    public const string DifferentialTorqueRatios = "openUsdPhysics:differential:torqueRatios";

    /// <summary>The <c>openUsdPhysics:differential:wheels</c> property of <c>OpenUsdPhysicsVehicleDifferentialAPI</c>.</summary>
    public const string DifferentialWheels = "openUsdPhysics:differential:wheels";

    /// <summary>The <c>openUsdPhysics:brakes:primaryMaxBrakeTorque</c> property of <c>OpenUsdPhysicsVehicleBrakesAPI</c>.</summary>
    public const string BrakesPrimaryMaxBrakeTorque = "openUsdPhysics:brakes:primaryMaxBrakeTorque";

    /// <summary>The <c>openUsdPhysics:brakes:primaryTorqueMultipliers</c> property of <c>OpenUsdPhysicsVehicleBrakesAPI</c>.</summary>
    public const string BrakesPrimaryTorqueMultipliers = "openUsdPhysics:brakes:primaryTorqueMultipliers";

    /// <summary>The <c>openUsdPhysics:brakes:primaryWheels</c> property of <c>OpenUsdPhysicsVehicleBrakesAPI</c>.</summary>
    public const string BrakesPrimaryWheels = "openUsdPhysics:brakes:primaryWheels";

    /// <summary>The <c>openUsdPhysics:brakes:secondaryMaxBrakeTorque</c> property of <c>OpenUsdPhysicsVehicleBrakesAPI</c>.</summary>
    public const string BrakesSecondaryMaxBrakeTorque = "openUsdPhysics:brakes:secondaryMaxBrakeTorque";

    /// <summary>The <c>openUsdPhysics:brakes:secondaryTorqueMultipliers</c> property of <c>OpenUsdPhysicsVehicleBrakesAPI</c>.</summary>
    public const string BrakesSecondaryTorqueMultipliers = "openUsdPhysics:brakes:secondaryTorqueMultipliers";

    /// <summary>The <c>openUsdPhysics:brakes:secondaryWheels</c> property of <c>OpenUsdPhysicsVehicleBrakesAPI</c>.</summary>
    public const string BrakesSecondaryWheels = "openUsdPhysics:brakes:secondaryWheels";

    /// <summary>The <c>openUsdPhysics:steering:angleMultipliers</c> property of <c>OpenUsdPhysicsVehicleSteeringAPI</c>.</summary>
    public const string SteeringAngleMultipliers = "openUsdPhysics:steering:angleMultipliers";

    /// <summary>The <c>openUsdPhysics:steering:maxSteerAngle</c> property of <c>OpenUsdPhysicsVehicleSteeringAPI</c>.</summary>
    public const string SteeringMaxSteerAngle = "openUsdPhysics:steering:maxSteerAngle";

    /// <summary>The <c>openUsdPhysics:steering:wheels</c> property of <c>OpenUsdPhysicsVehicleSteeringAPI</c>.</summary>
    public const string SteeringWheels = "openUsdPhysics:steering:wheels";

    /// <summary>The <c>openUsdPhysics:fixedTendon:articulation</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonArticulation = "openUsdPhysics:fixedTendon:articulation";

    /// <summary>The <c>openUsdPhysics:fixedTendon:damping</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonDamping = "openUsdPhysics:fixedTendon:damping";

    /// <summary>The <c>openUsdPhysics:fixedTendon:enabled</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonEnabled = "openUsdPhysics:fixedTendon:enabled";

    /// <summary>The <c>openUsdPhysics:fixedTendon:forceCoefficients</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonForceCoefficients = "openUsdPhysics:fixedTendon:forceCoefficients";

    /// <summary>The <c>openUsdPhysics:fixedTendon:gearings</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonGearings = "openUsdPhysics:fixedTendon:gearings";

    /// <summary>The <c>openUsdPhysics:fixedTendon:joints</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonJoints = "openUsdPhysics:fixedTendon:joints";

    /// <summary>The <c>openUsdPhysics:fixedTendon:limitStiffness</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonLimitStiffness = "openUsdPhysics:fixedTendon:limitStiffness";

    /// <summary>The <c>openUsdPhysics:fixedTendon:lowerLimit</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonLowerLimit = "openUsdPhysics:fixedTendon:lowerLimit";

    /// <summary>The <c>openUsdPhysics:fixedTendon:offset</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonOffset = "openUsdPhysics:fixedTendon:offset";

    /// <summary>The <c>openUsdPhysics:fixedTendon:restLength</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonRestLength = "openUsdPhysics:fixedTendon:restLength";

    /// <summary>The <c>openUsdPhysics:fixedTendon:rootJoint</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonRootJoint = "openUsdPhysics:fixedTendon:rootJoint";

    /// <summary>The <c>openUsdPhysics:fixedTendon:stiffness</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonStiffness = "openUsdPhysics:fixedTendon:stiffness";

    /// <summary>The <c>openUsdPhysics:fixedTendon:upperLimit</c> property of <c>OpenUsdPhysicsFixedTendon</c>.</summary>
    public const string FixedTendonUpperLimit = "openUsdPhysics:fixedTendon:upperLimit";

    /// <summary>The <c>openUsdPhysics:spatialTendon:articulation</c> property of <c>OpenUsdPhysicsSpatialTendon</c>.</summary>
    public const string SpatialTendonArticulation = "openUsdPhysics:spatialTendon:articulation";

    /// <summary>The <c>openUsdPhysics:spatialTendon:damping</c> property of <c>OpenUsdPhysicsSpatialTendon</c>.</summary>
    public const string SpatialTendonDamping = "openUsdPhysics:spatialTendon:damping";

    /// <summary>The <c>openUsdPhysics:spatialTendon:enabled</c> property of <c>OpenUsdPhysicsSpatialTendon</c>.</summary>
    public const string SpatialTendonEnabled = "openUsdPhysics:spatialTendon:enabled";

    /// <summary>The <c>openUsdPhysics:spatialTendon:limitStiffness</c> property of <c>OpenUsdPhysicsSpatialTendon</c>.</summary>
    public const string SpatialTendonLimitStiffness = "openUsdPhysics:spatialTendon:limitStiffness";

    /// <summary>The <c>openUsdPhysics:spatialTendon:offset</c> property of <c>OpenUsdPhysicsSpatialTendon</c>.</summary>
    public const string SpatialTendonOffset = "openUsdPhysics:spatialTendon:offset";

    /// <summary>The <c>openUsdPhysics:spatialTendon:rootAttachment</c> property of <c>OpenUsdPhysicsSpatialTendon</c>.</summary>
    public const string SpatialTendonRootAttachment = "openUsdPhysics:spatialTendon:rootAttachment";

    /// <summary>The <c>openUsdPhysics:spatialTendon:stiffness</c> property of <c>OpenUsdPhysicsSpatialTendon</c>.</summary>
    public const string SpatialTendonStiffness = "openUsdPhysics:spatialTendon:stiffness";

    /// <summary>The <c>openUsdPhysics:tendonAttachment:gearing</c> property of <c>OpenUsdPhysicsTendonAttachmentAPI</c>.</summary>
    public const string TendonAttachmentGearing = "openUsdPhysics:tendonAttachment:gearing";

    /// <summary>The <c>openUsdPhysics:tendonAttachment:localPosition</c> property of <c>OpenUsdPhysicsTendonAttachmentAPI</c>.</summary>
    public const string TendonAttachmentLocalPosition = "openUsdPhysics:tendonAttachment:localPosition";

    /// <summary>The <c>openUsdPhysics:tendonAttachment:lowerLimit</c> property of <c>OpenUsdPhysicsTendonAttachmentAPI</c>.</summary>
    public const string TendonAttachmentLowerLimit = "openUsdPhysics:tendonAttachment:lowerLimit";

    /// <summary>The <c>openUsdPhysics:tendonAttachment:parentAttachment</c> property of <c>OpenUsdPhysicsTendonAttachmentAPI</c>.</summary>
    public const string TendonAttachmentParentAttachment = "openUsdPhysics:tendonAttachment:parentAttachment";

    /// <summary>The <c>openUsdPhysics:tendonAttachment:restLength</c> property of <c>OpenUsdPhysicsTendonAttachmentAPI</c>.</summary>
    public const string TendonAttachmentRestLength = "openUsdPhysics:tendonAttachment:restLength";

    /// <summary>The <c>openUsdPhysics:tendonAttachment:role</c> property of <c>OpenUsdPhysicsTendonAttachmentAPI</c>.</summary>
    public const string TendonAttachmentRole = "openUsdPhysics:tendonAttachment:role";

    /// <summary>The <c>openUsdPhysics:tendonAttachment:tendon</c> property of <c>OpenUsdPhysicsTendonAttachmentAPI</c>.</summary>
    public const string TendonAttachmentTendon = "openUsdPhysics:tendonAttachment:tendon";

    /// <summary>The <c>openUsdPhysics:tendonAttachment:upperLimit</c> property of <c>OpenUsdPhysicsTendonAttachmentAPI</c>.</summary>
    public const string TendonAttachmentUpperLimit = "openUsdPhysics:tendonAttachment:upperLimit";

    /// <summary>The <c>openUsdPhysics:mimicJoint:axis</c> property of <c>OpenUsdPhysicsMimicJointAPI</c>.</summary>
    public const string MimicJointAxis = "openUsdPhysics:mimicJoint:axis";

    /// <summary>The <c>openUsdPhysics:mimicJoint:dampingRatio</c> property of <c>OpenUsdPhysicsMimicJointAPI</c>.</summary>
    public const string MimicJointDampingRatio = "openUsdPhysics:mimicJoint:dampingRatio";

    /// <summary>The <c>openUsdPhysics:mimicJoint:enabled</c> property of <c>OpenUsdPhysicsMimicJointAPI</c>.</summary>
    public const string MimicJointEnabled = "openUsdPhysics:mimicJoint:enabled";

    /// <summary>The <c>openUsdPhysics:mimicJoint:gearing</c> property of <c>OpenUsdPhysicsMimicJointAPI</c>.</summary>
    public const string MimicJointGearing = "openUsdPhysics:mimicJoint:gearing";

    /// <summary>The <c>openUsdPhysics:mimicJoint:naturalFrequency</c> property of <c>OpenUsdPhysicsMimicJointAPI</c>.</summary>
    public const string MimicJointNaturalFrequency = "openUsdPhysics:mimicJoint:naturalFrequency";

    /// <summary>The <c>openUsdPhysics:mimicJoint:offset</c> property of <c>OpenUsdPhysicsMimicJointAPI</c>.</summary>
    public const string MimicJointOffset = "openUsdPhysics:mimicJoint:offset";

    /// <summary>The <c>openUsdPhysics:mimicJoint:referenceAxis</c> property of <c>OpenUsdPhysicsMimicJointAPI</c>.</summary>
    public const string MimicJointReferenceAxis = "openUsdPhysics:mimicJoint:referenceAxis";

    /// <summary>The <c>openUsdPhysics:mimicJoint:referenceJoint</c> property of <c>OpenUsdPhysicsMimicJointAPI</c>.</summary>
    public const string MimicJointReferenceJoint = "openUsdPhysics:mimicJoint:referenceJoint";

    /// <summary>The <c>openUsdPhysics:particleSystem:contactOffset</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemContactOffset = "openUsdPhysics:particleSystem:contactOffset";

    /// <summary>The <c>openUsdPhysics:particleSystem:enableCCD</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemEnableCCD = "openUsdPhysics:particleSystem:enableCCD";

    /// <summary>The <c>openUsdPhysics:particleSystem:enabled</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemEnabled = "openUsdPhysics:particleSystem:enabled";

    /// <summary>The <c>openUsdPhysics:particleSystem:fluidRestOffset</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemFluidRestOffset = "openUsdPhysics:particleSystem:fluidRestOffset";

    /// <summary>The <c>openUsdPhysics:particleSystem:globalSelfCollisionEnabled</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemGlobalSelfCollisionEnabled = "openUsdPhysics:particleSystem:globalSelfCollisionEnabled";

    /// <summary>The <c>openUsdPhysics:particleSystem:maxDepenetrationVelocity</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemMaxDepenetrationVelocity = "openUsdPhysics:particleSystem:maxDepenetrationVelocity";

    /// <summary>The <c>openUsdPhysics:particleSystem:maxNeighborhood</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemMaxNeighborhood = "openUsdPhysics:particleSystem:maxNeighborhood";

    /// <summary>The <c>openUsdPhysics:particleSystem:neighborhoodScale</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemNeighborhoodScale = "openUsdPhysics:particleSystem:neighborhoodScale";

    /// <summary>The <c>openUsdPhysics:particleSystem:nonParticleCollisionEnabled</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemNonParticleCollisionEnabled = "openUsdPhysics:particleSystem:nonParticleCollisionEnabled";

    /// <summary>The <c>openUsdPhysics:particleSystem:particleContactOffset</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemParticleContactOffset = "openUsdPhysics:particleSystem:particleContactOffset";

    /// <summary>The <c>openUsdPhysics:particleSystem:restOffset</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemRestOffset = "openUsdPhysics:particleSystem:restOffset";

    /// <summary>The <c>openUsdPhysics:particleSystem:simulationOwner</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemSimulationOwner = "openUsdPhysics:particleSystem:simulationOwner";

    /// <summary>The <c>openUsdPhysics:particleSystem:solidRestOffset</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemSolidRestOffset = "openUsdPhysics:particleSystem:solidRestOffset";

    /// <summary>The <c>openUsdPhysics:particleSystem:solverPositionIterationCount</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemSolverPositionIterationCount = "openUsdPhysics:particleSystem:solverPositionIterationCount";

    /// <summary>The <c>openUsdPhysics:particleSystem:wind</c> property of <c>OpenUsdPhysicsParticleSystemAPI</c>.</summary>
    public const string ParticleSystemWind = "openUsdPhysics:particleSystem:wind";

    /// <summary>The <c>openUsdPhysics:particleSet:enabled</c> property of <c>OpenUsdPhysicsParticleSetAPI</c>.</summary>
    public const string ParticleSetEnabled = "openUsdPhysics:particleSet:enabled";

    /// <summary>The <c>openUsdPhysics:particleSet:fluid</c> property of <c>OpenUsdPhysicsParticleSetAPI</c>.</summary>
    public const string ParticleSetFluid = "openUsdPhysics:particleSet:fluid";

    /// <summary>The <c>openUsdPhysics:particleSet:mass</c> property of <c>OpenUsdPhysicsParticleSetAPI</c>.</summary>
    public const string ParticleSetMass = "openUsdPhysics:particleSet:mass";

    /// <summary>The <c>openUsdPhysics:particleSet:material</c> property of <c>OpenUsdPhysicsParticleSetAPI</c>.</summary>
    public const string ParticleSetMaterial = "openUsdPhysics:particleSet:material";

    /// <summary>The <c>openUsdPhysics:particleSet:particleGroup</c> property of <c>OpenUsdPhysicsParticleSetAPI</c>.</summary>
    public const string ParticleSetParticleGroup = "openUsdPhysics:particleSet:particleGroup";

    /// <summary>The <c>openUsdPhysics:particleSet:particleSystem</c> property of <c>OpenUsdPhysicsParticleSetAPI</c>.</summary>
    public const string ParticleSetParticleSystem = "openUsdPhysics:particleSet:particleSystem";

    /// <summary>The <c>openUsdPhysics:particleSet:restPoints</c> property of <c>OpenUsdPhysicsParticleSetAPI</c>.</summary>
    public const string ParticleSetRestPoints = "openUsdPhysics:particleSet:restPoints";

    /// <summary>The <c>openUsdPhysics:particleSet:selfCollision</c> property of <c>OpenUsdPhysicsParticleSetAPI</c>.</summary>
    public const string ParticleSetSelfCollision = "openUsdPhysics:particleSet:selfCollision";

    /// <summary>The <c>openUsdPhysics:particleCloth:enabled</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothEnabled = "openUsdPhysics:particleCloth:enabled";

    /// <summary>The <c>openUsdPhysics:particleCloth:material</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothMaterial = "openUsdPhysics:particleCloth:material";

    /// <summary>The <c>openUsdPhysics:particleCloth:particleGroup</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothParticleGroup = "openUsdPhysics:particleCloth:particleGroup";

    /// <summary>The <c>openUsdPhysics:particleCloth:particleSystem</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothParticleSystem = "openUsdPhysics:particleCloth:particleSystem";

    /// <summary>The <c>openUsdPhysics:particleCloth:pressure</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothPressure = "openUsdPhysics:particleCloth:pressure";

    /// <summary>The <c>openUsdPhysics:particleCloth:restPoints</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothRestPoints = "openUsdPhysics:particleCloth:restPoints";

    /// <summary>The <c>openUsdPhysics:particleCloth:selfCollision</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothSelfCollision = "openUsdPhysics:particleCloth:selfCollision";

    /// <summary>The <c>openUsdPhysics:particleCloth:selfCollisionFilter</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothSelfCollisionFilter = "openUsdPhysics:particleCloth:selfCollisionFilter";

    /// <summary>The <c>openUsdPhysics:particleCloth:springDampings</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothSpringDampings = "openUsdPhysics:particleCloth:springDampings";

    /// <summary>The <c>openUsdPhysics:particleCloth:springIndices</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothSpringIndices = "openUsdPhysics:particleCloth:springIndices";

    /// <summary>The <c>openUsdPhysics:particleCloth:springRestLengths</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothSpringRestLengths = "openUsdPhysics:particleCloth:springRestLengths";

    /// <summary>The <c>openUsdPhysics:particleCloth:springStiffnesses</c> property of <c>OpenUsdPhysicsParticleClothAPI</c>.</summary>
    public const string ParticleClothSpringStiffnesses = "openUsdPhysics:particleCloth:springStiffnesses";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:adhesion</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialAdhesion = "openUsdPhysics:pbdMaterial:adhesion";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:adhesionOffsetScale</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialAdhesionOffsetScale = "openUsdPhysics:pbdMaterial:adhesionOffsetScale";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:cflCoefficient</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialCflCoefficient = "openUsdPhysics:pbdMaterial:cflCoefficient";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:cohesion</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialCohesion = "openUsdPhysics:pbdMaterial:cohesion";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:damping</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialDamping = "openUsdPhysics:pbdMaterial:damping";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:density</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialDensity = "openUsdPhysics:pbdMaterial:density";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:drag</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialDrag = "openUsdPhysics:pbdMaterial:drag";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:friction</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialFriction = "openUsdPhysics:pbdMaterial:friction";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:gravityScale</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialGravityScale = "openUsdPhysics:pbdMaterial:gravityScale";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:lift</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialLift = "openUsdPhysics:pbdMaterial:lift";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:particleAdhesionScale</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialParticleAdhesionScale = "openUsdPhysics:pbdMaterial:particleAdhesionScale";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:particleFrictionScale</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialParticleFrictionScale = "openUsdPhysics:pbdMaterial:particleFrictionScale";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:surfaceTension</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialSurfaceTension = "openUsdPhysics:pbdMaterial:surfaceTension";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:viscosity</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialViscosity = "openUsdPhysics:pbdMaterial:viscosity";

    /// <summary>The <c>openUsdPhysics:pbdMaterial:vorticityConfinement</c> property of <c>OpenUsdPhysicsPbdMaterialAPI</c>.</summary>
    public const string PbdMaterialVorticityConfinement = "openUsdPhysics:pbdMaterial:vorticityConfinement";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:airDrag</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesAirDrag = "openUsdPhysics:diffuseParticles:airDrag";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:bubbleDrag</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesBubbleDrag = "openUsdPhysics:diffuseParticles:bubbleDrag";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:buoyancy</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesBuoyancy = "openUsdPhysics:diffuseParticles:buoyancy";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:collisionDecay</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesCollisionDecay = "openUsdPhysics:diffuseParticles:collisionDecay";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:divergenceWeight</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesDivergenceWeight = "openUsdPhysics:diffuseParticles:divergenceWeight";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:enabled</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesEnabled = "openUsdPhysics:diffuseParticles:enabled";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:kineticEnergyWeight</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesKineticEnergyWeight = "openUsdPhysics:diffuseParticles:kineticEnergyWeight";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:lifetime</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesLifetime = "openUsdPhysics:diffuseParticles:lifetime";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:maxParticleMultiplier</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesMaxParticleMultiplier = "openUsdPhysics:diffuseParticles:maxParticleMultiplier";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:pressureWeight</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesPressureWeight = "openUsdPhysics:diffuseParticles:pressureWeight";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:threshold</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesThreshold = "openUsdPhysics:diffuseParticles:threshold";

    /// <summary>The <c>openUsdPhysics:diffuseParticles:useAccurateVelocity</c> property of <c>OpenUsdPhysicsDiffuseParticlesAPI</c>.</summary>
    public const string DiffuseParticlesUseAccurateVelocity = "openUsdPhysics:diffuseParticles:useAccurateVelocity";

    /// <summary>The <c>openUsdPhysics:particleAnisotropy:enabled</c> property of <c>OpenUsdPhysicsParticleAnisotropyAPI</c>.</summary>
    public const string ParticleAnisotropyEnabled = "openUsdPhysics:particleAnisotropy:enabled";

    /// <summary>The <c>openUsdPhysics:particleAnisotropy:max</c> property of <c>OpenUsdPhysicsParticleAnisotropyAPI</c>.</summary>
    public const string ParticleAnisotropyMax = "openUsdPhysics:particleAnisotropy:max";

    /// <summary>The <c>openUsdPhysics:particleAnisotropy:min</c> property of <c>OpenUsdPhysicsParticleAnisotropyAPI</c>.</summary>
    public const string ParticleAnisotropyMin = "openUsdPhysics:particleAnisotropy:min";

    /// <summary>The <c>openUsdPhysics:particleAnisotropy:scale</c> property of <c>OpenUsdPhysicsParticleAnisotropyAPI</c>.</summary>
    public const string ParticleAnisotropyScale = "openUsdPhysics:particleAnisotropy:scale";

    /// <summary>The <c>openUsdPhysics:particleSmoothing:enabled</c> property of <c>OpenUsdPhysicsParticleSmoothingAPI</c>.</summary>
    public const string ParticleSmoothingEnabled = "openUsdPhysics:particleSmoothing:enabled";

    /// <summary>The <c>openUsdPhysics:particleSmoothing:strength</c> property of <c>OpenUsdPhysicsParticleSmoothingAPI</c>.</summary>
    public const string ParticleSmoothingStrength = "openUsdPhysics:particleSmoothing:strength";

    /// <summary>The <c>openUsdPhysics:isosurface:enabled</c> property of <c>OpenUsdPhysicsParticleIsosurfaceAPI</c>.</summary>
    public const string IsosurfaceEnabled = "openUsdPhysics:isosurface:enabled";

    /// <summary>The <c>openUsdPhysics:isosurface:gridFilteringPasses</c> property of <c>OpenUsdPhysicsParticleIsosurfaceAPI</c>.</summary>
    public const string IsosurfaceGridFilteringPasses = "openUsdPhysics:isosurface:gridFilteringPasses";

    /// <summary>The <c>openUsdPhysics:isosurface:gridSmoothingRadius</c> property of <c>OpenUsdPhysicsParticleIsosurfaceAPI</c>.</summary>
    public const string IsosurfaceGridSmoothingRadius = "openUsdPhysics:isosurface:gridSmoothingRadius";

    /// <summary>The <c>openUsdPhysics:isosurface:gridSpacing</c> property of <c>OpenUsdPhysicsParticleIsosurfaceAPI</c>.</summary>
    public const string IsosurfaceGridSpacing = "openUsdPhysics:isosurface:gridSpacing";

    /// <summary>The <c>openUsdPhysics:isosurface:maxSubgrids</c> property of <c>OpenUsdPhysicsParticleIsosurfaceAPI</c>.</summary>
    public const string IsosurfaceMaxSubgrids = "openUsdPhysics:isosurface:maxSubgrids";

    /// <summary>The <c>openUsdPhysics:isosurface:maxTriangles</c> property of <c>OpenUsdPhysicsParticleIsosurfaceAPI</c>.</summary>
    public const string IsosurfaceMaxTriangles = "openUsdPhysics:isosurface:maxTriangles";

    /// <summary>The <c>openUsdPhysics:isosurface:maxVertices</c> property of <c>OpenUsdPhysicsParticleIsosurfaceAPI</c>.</summary>
    public const string IsosurfaceMaxVertices = "openUsdPhysics:isosurface:maxVertices";

    /// <summary>The <c>openUsdPhysics:isosurface:numMeshNormalSmoothingPasses</c> property of <c>OpenUsdPhysicsParticleIsosurfaceAPI</c>.</summary>
    public const string IsosurfaceNumMeshNormalSmoothingPasses = "openUsdPhysics:isosurface:numMeshNormalSmoothingPasses";

    /// <summary>The <c>openUsdPhysics:isosurface:numMeshSmoothingPasses</c> property of <c>OpenUsdPhysicsParticleIsosurfaceAPI</c>.</summary>
    public const string IsosurfaceNumMeshSmoothingPasses = "openUsdPhysics:isosurface:numMeshSmoothingPasses";

    /// <summary>The <c>openUsdPhysics:isosurface:surfaceDistance</c> property of <c>OpenUsdPhysicsParticleIsosurfaceAPI</c>.</summary>
    public const string IsosurfaceSurfaceDistance = "openUsdPhysics:isosurface:surfaceDistance";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:collisionIterationMultiplier</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableCollisionIterationMultiplier = "openUsdPhysics:surfaceDeformable:collisionIterationMultiplier";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:collisionPairUpdateFrequency</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableCollisionPairUpdateFrequency = "openUsdPhysics:surfaceDeformable:collisionPairUpdateFrequency";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:enableCCD</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableEnableCCD = "openUsdPhysics:surfaceDeformable:enableCCD";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:enabled</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableEnabled = "openUsdPhysics:surfaceDeformable:enabled";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:material</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableMaterial = "openUsdPhysics:surfaceDeformable:material";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:maxDisplacement</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableMaxDisplacement = "openUsdPhysics:surfaceDeformable:maxDisplacement";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:restPoints</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableRestPoints = "openUsdPhysics:surfaceDeformable:restPoints";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:selfCollision</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableSelfCollision = "openUsdPhysics:surfaceDeformable:selfCollision";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:selfCollisionFilterDistance</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableSelfCollisionFilterDistance = "openUsdPhysics:surfaceDeformable:selfCollisionFilterDistance";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:simulationIndices</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableSimulationIndices = "openUsdPhysics:surfaceDeformable:simulationIndices";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:simulationOwner</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableSimulationOwner = "openUsdPhysics:surfaceDeformable:simulationOwner";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:solverPositionIterationCount</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableSolverPositionIterationCount = "openUsdPhysics:surfaceDeformable:solverPositionIterationCount";

    /// <summary>The <c>openUsdPhysics:surfaceDeformable:vertexVelocityDamping</c> property of <c>OpenUsdPhysicsSurfaceDeformableAPI</c>.</summary>
    public const string SurfaceDeformableVertexVelocityDamping = "openUsdPhysics:surfaceDeformable:vertexVelocityDamping";

    /// <summary>The <c>openUsdPhysics:surfaceDeformableMaterial:bendingDamping</c> property of <c>OpenUsdPhysicsSurfaceDeformableMaterialAPI</c>.</summary>
    public const string SurfaceDeformableMaterialBendingDamping = "openUsdPhysics:surfaceDeformableMaterial:bendingDamping";

    /// <summary>The <c>openUsdPhysics:surfaceDeformableMaterial:bendingStiffness</c> property of <c>OpenUsdPhysicsSurfaceDeformableMaterialAPI</c>.</summary>
    public const string SurfaceDeformableMaterialBendingStiffness = "openUsdPhysics:surfaceDeformableMaterial:bendingStiffness";

    /// <summary>The <c>openUsdPhysics:surfaceDeformableMaterial:density</c> property of <c>OpenUsdPhysicsSurfaceDeformableMaterialAPI</c>.</summary>
    public const string SurfaceDeformableMaterialDensity = "openUsdPhysics:surfaceDeformableMaterial:density";

    /// <summary>The <c>openUsdPhysics:surfaceDeformableMaterial:dynamicFriction</c> property of <c>OpenUsdPhysicsSurfaceDeformableMaterialAPI</c>.</summary>
    public const string SurfaceDeformableMaterialDynamicFriction = "openUsdPhysics:surfaceDeformableMaterial:dynamicFriction";

    /// <summary>The <c>openUsdPhysics:surfaceDeformableMaterial:elasticityDamping</c> property of <c>OpenUsdPhysicsSurfaceDeformableMaterialAPI</c>.</summary>
    public const string SurfaceDeformableMaterialElasticityDamping = "openUsdPhysics:surfaceDeformableMaterial:elasticityDamping";

    /// <summary>The <c>openUsdPhysics:surfaceDeformableMaterial:poissonsRatio</c> property of <c>OpenUsdPhysicsSurfaceDeformableMaterialAPI</c>.</summary>
    public const string SurfaceDeformableMaterialPoissonsRatio = "openUsdPhysics:surfaceDeformableMaterial:poissonsRatio";

    /// <summary>The <c>openUsdPhysics:surfaceDeformableMaterial:thickness</c> property of <c>OpenUsdPhysicsSurfaceDeformableMaterialAPI</c>.</summary>
    public const string SurfaceDeformableMaterialThickness = "openUsdPhysics:surfaceDeformableMaterial:thickness";

    /// <summary>The <c>openUsdPhysics:surfaceDeformableMaterial:youngsModulus</c> property of <c>OpenUsdPhysicsSurfaceDeformableMaterialAPI</c>.</summary>
    public const string SurfaceDeformableMaterialYoungsModulus = "openUsdPhysics:surfaceDeformableMaterial:youngsModulus";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:collisionIndices</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableCollisionIndices = "openUsdPhysics:volumeDeformable:collisionIndices";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:collisionRestPoints</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableCollisionRestPoints = "openUsdPhysics:volumeDeformable:collisionRestPoints";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:enableCCD</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableEnableCCD = "openUsdPhysics:volumeDeformable:enableCCD";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:enabled</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableEnabled = "openUsdPhysics:volumeDeformable:enabled";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:kinematicEnabled</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableKinematicEnabled = "openUsdPhysics:volumeDeformable:kinematicEnabled";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:material</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableMaterial = "openUsdPhysics:volumeDeformable:material";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:maxDepenetrationVelocity</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableMaxDepenetrationVelocity = "openUsdPhysics:volumeDeformable:maxDepenetrationVelocity";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:selfCollision</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableSelfCollision = "openUsdPhysics:volumeDeformable:selfCollision";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:selfCollisionFilterDistance</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableSelfCollisionFilterDistance = "openUsdPhysics:volumeDeformable:selfCollisionFilterDistance";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:settlingThreshold</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableSettlingThreshold = "openUsdPhysics:volumeDeformable:settlingThreshold";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:simulationHexahedralResolution</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableSimulationHexahedralResolution = "openUsdPhysics:volumeDeformable:simulationHexahedralResolution";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:simulationIndices</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableSimulationIndices = "openUsdPhysics:volumeDeformable:simulationIndices";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:simulationOwner</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableSimulationOwner = "openUsdPhysics:volumeDeformable:simulationOwner";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:simulationRestPoints</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableSimulationRestPoints = "openUsdPhysics:volumeDeformable:simulationRestPoints";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:sleepThreshold</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableSleepThreshold = "openUsdPhysics:volumeDeformable:sleepThreshold";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:solverPositionIterationCount</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableSolverPositionIterationCount = "openUsdPhysics:volumeDeformable:solverPositionIterationCount";

    /// <summary>The <c>openUsdPhysics:volumeDeformable:vertexVelocityDamping</c> property of <c>OpenUsdPhysicsVolumeDeformableAPI</c>.</summary>
    public const string VolumeDeformableVertexVelocityDamping = "openUsdPhysics:volumeDeformable:vertexVelocityDamping";

    /// <summary>The <c>openUsdPhysics:volumeDeformableMaterial:damping</c> property of <c>OpenUsdPhysicsVolumeDeformableMaterialAPI</c>.</summary>
    public const string VolumeDeformableMaterialDamping = "openUsdPhysics:volumeDeformableMaterial:damping";

    /// <summary>The <c>openUsdPhysics:volumeDeformableMaterial:dampingScale</c> property of <c>OpenUsdPhysicsVolumeDeformableMaterialAPI</c>.</summary>
    public const string VolumeDeformableMaterialDampingScale = "openUsdPhysics:volumeDeformableMaterial:dampingScale";

    /// <summary>The <c>openUsdPhysics:volumeDeformableMaterial:density</c> property of <c>OpenUsdPhysicsVolumeDeformableMaterialAPI</c>.</summary>
    public const string VolumeDeformableMaterialDensity = "openUsdPhysics:volumeDeformableMaterial:density";

    /// <summary>The <c>openUsdPhysics:volumeDeformableMaterial:dynamicFriction</c> property of <c>OpenUsdPhysicsVolumeDeformableMaterialAPI</c>.</summary>
    public const string VolumeDeformableMaterialDynamicFriction = "openUsdPhysics:volumeDeformableMaterial:dynamicFriction";

    /// <summary>The <c>openUsdPhysics:volumeDeformableMaterial:elasticityDamping</c> property of <c>OpenUsdPhysicsVolumeDeformableMaterialAPI</c>.</summary>
    public const string VolumeDeformableMaterialElasticityDamping = "openUsdPhysics:volumeDeformableMaterial:elasticityDamping";

    /// <summary>The <c>openUsdPhysics:volumeDeformableMaterial:poissonsRatio</c> property of <c>OpenUsdPhysicsVolumeDeformableMaterialAPI</c>.</summary>
    public const string VolumeDeformableMaterialPoissonsRatio = "openUsdPhysics:volumeDeformableMaterial:poissonsRatio";

    /// <summary>The <c>openUsdPhysics:volumeDeformableMaterial:youngsModulus</c> property of <c>OpenUsdPhysicsVolumeDeformableMaterialAPI</c>.</summary>
    public const string VolumeDeformableMaterialYoungsModulus = "openUsdPhysics:volumeDeformableMaterial:youngsModulus";

    /// <summary>The <c>openUsdPhysics:attachment:actor0</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentActor0 = "openUsdPhysics:attachment:actor0";

    /// <summary>The <c>openUsdPhysics:attachment:actor1</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentActor1 = "openUsdPhysics:attachment:actor1";

    /// <summary>The <c>openUsdPhysics:attachment:attachmentType</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentAttachmentType = "openUsdPhysics:attachment:attachmentType";

    /// <summary>The <c>openUsdPhysics:attachment:collisionFilterIndices0</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentCollisionFilterIndices0 = "openUsdPhysics:attachment:collisionFilterIndices0";

    /// <summary>The <c>openUsdPhysics:attachment:collisionFilterIndices1</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentCollisionFilterIndices1 = "openUsdPhysics:attachment:collisionFilterIndices1";

    /// <summary>The <c>openUsdPhysics:attachment:damping</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentDamping = "openUsdPhysics:attachment:damping";

    /// <summary>The <c>openUsdPhysics:attachment:elementIndices0</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentElementIndices0 = "openUsdPhysics:attachment:elementIndices0";

    /// <summary>The <c>openUsdPhysics:attachment:elementIndices1</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentElementIndices1 = "openUsdPhysics:attachment:elementIndices1";

    /// <summary>The <c>openUsdPhysics:attachment:enabled</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentEnabled = "openUsdPhysics:attachment:enabled";

    /// <summary>The <c>openUsdPhysics:attachment:filterType0</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentFilterType0 = "openUsdPhysics:attachment:filterType0";

    /// <summary>The <c>openUsdPhysics:attachment:filterType1</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentFilterType1 = "openUsdPhysics:attachment:filterType1";

    /// <summary>The <c>openUsdPhysics:attachment:points0</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentPoints0 = "openUsdPhysics:attachment:points0";

    /// <summary>The <c>openUsdPhysics:attachment:points1</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentPoints1 = "openUsdPhysics:attachment:points1";

    /// <summary>The <c>openUsdPhysics:attachment:stiffness</c> property of <c>OpenUsdPhysicsAttachment</c>.</summary>
    public const string AttachmentStiffness = "openUsdPhysics:attachment:stiffness";

    /// <summary>The <c>openUsdPhysics:autoAttachment:collisionFilteringOffset</c> property of <c>OpenUsdPhysicsAutoAttachmentAPI</c>.</summary>
    public const string AutoAttachmentCollisionFilteringOffset = "openUsdPhysics:autoAttachment:collisionFilteringOffset";

    /// <summary>The <c>openUsdPhysics:autoAttachment:deformableVertexOverlapOffset</c> property of <c>OpenUsdPhysicsAutoAttachmentAPI</c>.</summary>
    public const string AutoAttachmentDeformableVertexOverlapOffset = "openUsdPhysics:autoAttachment:deformableVertexOverlapOffset";

    /// <summary>The <c>openUsdPhysics:autoAttachment:enableCollisionFiltering</c> property of <c>OpenUsdPhysicsAutoAttachmentAPI</c>.</summary>
    public const string AutoAttachmentEnableCollisionFiltering = "openUsdPhysics:autoAttachment:enableCollisionFiltering";

    /// <summary>The <c>openUsdPhysics:autoAttachment:enableDeformableFilteringPairs</c> property of <c>OpenUsdPhysicsAutoAttachmentAPI</c>.</summary>
    public const string AutoAttachmentEnableDeformableFilteringPairs = "openUsdPhysics:autoAttachment:enableDeformableFilteringPairs";

    /// <summary>The <c>openUsdPhysics:autoAttachment:enableDeformableVertexAttachments</c> property of <c>OpenUsdPhysicsAutoAttachmentAPI</c>.</summary>
    public const string AutoAttachmentEnableDeformableVertexAttachments = "openUsdPhysics:autoAttachment:enableDeformableVertexAttachments";

    /// <summary>The <c>openUsdPhysics:autoAttachment:enableRigidSurfaceAttachments</c> property of <c>OpenUsdPhysicsAutoAttachmentAPI</c>.</summary>
    public const string AutoAttachmentEnableRigidSurfaceAttachments = "openUsdPhysics:autoAttachment:enableRigidSurfaceAttachments";

    /// <summary>The <c>openUsdPhysics:autoAttachment:enabled</c> property of <c>OpenUsdPhysicsAutoAttachmentAPI</c>.</summary>
    public const string AutoAttachmentEnabled = "openUsdPhysics:autoAttachment:enabled";

    /// <summary>The <c>openUsdPhysics:autoAttachment:maskShapes</c> property of <c>OpenUsdPhysicsAutoAttachmentAPI</c>.</summary>
    public const string AutoAttachmentMaskShapes = "openUsdPhysics:autoAttachment:maskShapes";

    /// <summary>The <c>openUsdPhysics:autoAttachment:rigidSurfaceSamplingDistance</c> property of <c>OpenUsdPhysicsAutoAttachmentAPI</c>.</summary>
    public const string AutoAttachmentRigidSurfaceSamplingDistance = "openUsdPhysics:autoAttachment:rigidSurfaceSamplingDistance";

    /// <summary>The <c>openUsdPhysics:collisionFilter:enabled</c> property of <c>OpenUsdPhysicsCollisionFilterSettingsAPI</c>.</summary>
    public const string CollisionFilterEnabled = "openUsdPhysics:collisionFilter:enabled";

    /// <summary>The <c>openUsdPhysics:collisionFilter:filterGroups</c> property of <c>OpenUsdPhysicsCollisionFilterSettingsAPI</c>.</summary>
    public const string CollisionFilterFilterGroups = "openUsdPhysics:collisionFilter:filterGroups";

    /// <summary>The <c>openUsdPhysics:collisionFilter:filterIndices</c> property of <c>OpenUsdPhysicsCollisionFilterSettingsAPI</c>.</summary>
    public const string CollisionFilterFilterIndices = "openUsdPhysics:collisionFilter:filterIndices";

    /// <summary>The <c>openUsdPhysics:collisionFilter:filteredPairs</c> property of <c>OpenUsdPhysicsCollisionFilterSettingsAPI</c>.</summary>
    public const string CollisionFilterFilteredPairs = "openUsdPhysics:collisionFilter:filteredPairs";

    /// <summary>The <c>openUsdPhysics:collisionFilter:invertFilteredGroups</c> property of <c>OpenUsdPhysicsCollisionFilterSettingsAPI</c>.</summary>
    public const string CollisionFilterInvertFilteredGroups = "openUsdPhysics:collisionFilter:invertFilteredGroups";

    /// <summary>The <c>openUsdPhysics:collisionFilter:mergeGroupName</c> property of <c>OpenUsdPhysicsCollisionFilterSettingsAPI</c>.</summary>
    public const string CollisionFilterMergeGroupName = "openUsdPhysics:collisionFilter:mergeGroupName";

    /// <summary>The <c>openUsdPhysics:collisionFilter:pairFilterMode</c> property of <c>OpenUsdPhysicsCollisionFilterSettingsAPI</c>.</summary>
    public const string CollisionFilterPairFilterMode = "openUsdPhysics:collisionFilter:pairFilterMode";

    /// <summary>The <c>openUsdPhysics:cookedData:assetPath</c> property of <c>OpenUsdPhysicsCookedDataAPI</c>.</summary>
    public const string CookedDataAssetPath = "openUsdPhysics:cookedData:assetPath";

    /// <summary>The <c>openUsdPhysics:cookedData:assetSubIdentifier</c> property of <c>OpenUsdPhysicsCookedDataAPI</c>.</summary>
    public const string CookedDataAssetSubIdentifier = "openUsdPhysics:cookedData:assetSubIdentifier";

    /// <summary>The <c>openUsdPhysics:cookedData:buildRevision</c> property of <c>OpenUsdPhysicsCookedDataAPI</c>.</summary>
    public const string CookedDataBuildRevision = "openUsdPhysics:cookedData:buildRevision";

    /// <summary>The <c>openUsdPhysics:cookedData:contentHash</c> property of <c>OpenUsdPhysicsCookedDataAPI</c>.</summary>
    public const string CookedDataContentHash = "openUsdPhysics:cookedData:contentHash";

    /// <summary>The <c>openUsdPhysics:cookedData:enabled</c> property of <c>OpenUsdPhysicsCookedDataAPI</c>.</summary>
    public const string CookedDataEnabled = "openUsdPhysics:cookedData:enabled";

    /// <summary>The <c>openUsdPhysics:cookedData:format</c> property of <c>OpenUsdPhysicsCookedDataAPI</c>.</summary>
    public const string CookedDataFormat = "openUsdPhysics:cookedData:format";

    /// <summary>The <c>openUsdPhysics:cookedData:missingDataBehavior</c> property of <c>OpenUsdPhysicsCookedDataAPI</c>.</summary>
    public const string CookedDataMissingDataBehavior = "openUsdPhysics:cookedData:missingDataBehavior";

    /// <summary>The <c>openUsdPhysics:cookedData:sdfBitsPerSubgridPixel</c> property of <c>OpenUsdPhysicsCookedDataAPI</c>.</summary>
    public const string CookedDataSdfBitsPerSubgridPixel = "openUsdPhysics:cookedData:sdfBitsPerSubgridPixel";

    /// <summary>The <c>openUsdPhysics:cookedData:sdfNarrowBandThickness</c> property of <c>OpenUsdPhysicsCookedDataAPI</c>.</summary>
    public const string CookedDataSdfNarrowBandThickness = "openUsdPhysics:cookedData:sdfNarrowBandThickness";

    /// <summary>The <c>openUsdPhysics:cookedData:sdfResolution</c> property of <c>OpenUsdPhysicsCookedDataAPI</c>.</summary>
    public const string CookedDataSdfResolution = "openUsdPhysics:cookedData:sdfResolution";

    /// <summary>The <c>openUsdPhysics:cookedData:sdfSubgridResolution</c> property of <c>OpenUsdPhysicsCookedDataAPI</c>.</summary>
    public const string CookedDataSdfSubgridResolution = "openUsdPhysics:cookedData:sdfSubgridResolution";
}
