/* Copyright (c) marcschier. Licensed under the MIT License. */

/*
 * Physics extraction ABI.
 *
 * One batched call traverses a composed stage exactly once on the stage owner thread and
 * produces one immutable, pointer-free extraction page. The page is the only physics
 * input the simulation worker ever sees: it holds no USD handle, no pointer, and no
 * back-reference into the stage, so every stage object may be released the moment
 * openusd_physics_extract_stage returns.
 *
 * The page is deliberately independent of the retained simulation build page
 * (native/openusd_physx/include/openusd_physx_world.h). Extraction records every authored
 * physics opinion of every supported schema domain together with stable identities,
 * ordered diagnostics, and a content fingerprint; the managed composer then projects the
 * subset that the retained world ABI can consume into a build page. Domains the retained
 * ABI cannot consume yet survive in the extraction page and are reported per object
 * instead of being silently dropped.
 *
 * Layout rules, all enforced by the managed validator:
 *   - Every section offset is relative to the first byte of the page and is a multiple of
 *     OPENUSD_PHYSICS_EXTRACT_ALIGNMENT.
 *   - An empty section declares a zero offset and a zero count.
 *   - Section order is: strings, objects, properties, relationships, targets, numbers,
 *     texts, points, indices, diagnostics.
 *   - Records are fixed size and are never reordered inside a section: object order is
 *     stage traversal order, and every index reference points backwards or into a
 *     previously declared section only.
 */

#ifndef OPENUSD_PHYSICS_EXTRACT_H
#define OPENUSD_PHYSICS_EXTRACT_H

#include "openusd_dotnet.h"

#ifdef __cplusplus
extern "C" {
#endif

/* "USDPXEXT" in little endian byte order. */
#define OPENUSD_PHYSICS_EXTRACT_PAGE_MAGIC UINT64_C(0x5458455850445355)
#define OPENUSD_PHYSICS_EXTRACT_ABI_VERSION 1u
#define OPENUSD_PHYSICS_EXTRACT_ALIGNMENT 8u
#define OPENUSD_PHYSICS_EXTRACT_HEADER_BYTES 216u
#define OPENUSD_PHYSICS_EXTRACT_PAGE_MAX_BYTES UINT64_C(0x20000000)
#define OPENUSD_PHYSICS_EXTRACT_MAX_OBJECTS (1u << 20)
#define OPENUSD_PHYSICS_EXTRACT_MAX_PROPERTIES (1u << 22)
#define OPENUSD_PHYSICS_EXTRACT_MAX_RELATIONSHIPS (1u << 21)
#define OPENUSD_PHYSICS_EXTRACT_MAX_TARGETS (1u << 21)
#define OPENUSD_PHYSICS_EXTRACT_MAX_NUMBERS (1u << 24)
#define OPENUSD_PHYSICS_EXTRACT_MAX_TEXTS (1u << 22)
#define OPENUSD_PHYSICS_EXTRACT_MAX_POINTS (1u << 24)
#define OPENUSD_PHYSICS_EXTRACT_MAX_INDICES (1u << 25)
#define OPENUSD_PHYSICS_EXTRACT_MAX_DIAGNOSTICS (1u << 16)
#define OPENUSD_PHYSICS_EXTRACT_MAX_STRING_BYTES (1u << 26)
#define OPENUSD_PHYSICS_EXTRACT_MESSAGE_BYTES 192u
#define OPENUSD_PHYSICS_EXTRACT_INVALID_ID UINT64_C(0)

typedef enum openusd_physics_extract_up_axis
{
    OPENUSD_PHYSICS_EXTRACT_UP_AXIS_X = 0,
    OPENUSD_PHYSICS_EXTRACT_UP_AXIS_Y = 1,
    OPENUSD_PHYSICS_EXTRACT_UP_AXIS_Z = 2
} openusd_physics_extract_up_axis;

typedef enum openusd_physics_extract_page_flags
{
    OPENUSD_PHYSICS_EXTRACT_PAGE_FLAG_NONE = 0,
    /* kilogramsPerUnit was not authored and the standard fallback of 1.0 was used. */
    OPENUSD_PHYSICS_EXTRACT_PAGE_FLAG_KILOGRAMS_FALLBACK = 1u << 0,
    /* metersPerUnit was not authored and the standard fallback of 0.01 was used. */
    OPENUSD_PHYSICS_EXTRACT_PAGE_FLAG_METERS_FALLBACK = 1u << 1,
    /* timeCodesPerSecond was not authored and the stage default was used. */
    OPENUSD_PHYSICS_EXTRACT_PAGE_FLAG_TIME_CODES_FALLBACK = 1u << 2,
    /* No authored start or end time code was found. */
    OPENUSD_PHYSICS_EXTRACT_PAGE_FLAG_TIME_RANGE_FALLBACK = 1u << 3,
    /* The stage up axis required a change of basis into PhysX space. */
    OPENUSD_PHYSICS_EXTRACT_PAGE_FLAG_UP_AXIS_CONVERTED = 1u << 4,
    /* At least one object was disabled by an error diagnostic. */
    OPENUSD_PHYSICS_EXTRACT_PAGE_FLAG_HAS_DISABLED_OBJECTS = 1u << 5,
    /* At least one section hit its capacity bound and stopped accepting records. */
    OPENUSD_PHYSICS_EXTRACT_PAGE_FLAG_TRUNCATED = 1u << 6,
    /* At least one foreign physx* opinion contributed to a resolved property. */
    OPENUSD_PHYSICS_EXTRACT_PAGE_FLAG_HAS_FOREIGN_OPINIONS = 1u << 7,
    /* The stage traversal visited at least one instance proxy. */
    OPENUSD_PHYSICS_EXTRACT_PAGE_FLAG_HAS_INSTANCES = 1u << 8
} openusd_physics_extract_page_flags;

typedef enum openusd_physics_extract_object_type
{
    OPENUSD_PHYSICS_EXTRACT_OBJECT_UNKNOWN = 0,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_SCENE = 1,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_RIGID_BODY = 2,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_COLLIDER = 3,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_MATERIAL = 4,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_COLLISION_GROUP = 5,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_JOINT = 6,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_ARTICULATION_ROOT = 7,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FILTERED_PAIRS = 8,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_CHARACTER_CONTROLLER = 9,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_VEHICLE = 10,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_VEHICLE_WHEEL_ATTACHMENT = 11,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_VEHICLE_FRICTION_TABLE = 12,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FIXED_TENDON = 13,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_SPATIAL_TENDON = 14,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_TENDON_ATTACHMENT = 15,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_MIMIC_JOINT = 16,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_PARTICLE_SYSTEM = 17,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_PARTICLE_SET = 18,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_PARTICLE_CLOTH = 19,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_DIFFUSE_PARTICLES = 20,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_SURFACE_DEFORMABLE = 21,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_VOLUME_DEFORMABLE = 22,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_ATTACHMENT = 23,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_COLLISION_FILTER = 24,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_COOKED_DATA = 25,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_PBD_MATERIAL = 26,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_SURFACE_DEFORMABLE_MATERIAL = 27,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_VOLUME_DEFORMABLE_MATERIAL = 28,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_SIMULATION_METADATA = 29,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_COUNT = 30
} openusd_physics_extract_object_type;

typedef enum openusd_physics_extract_domain
{
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_NONE = 0,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_SCENE = 1u << 0,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_RIGID_BODY = 1u << 1,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_COLLISION = 1u << 2,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_MATERIAL = 1u << 3,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_JOINT = 1u << 4,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_ARTICULATION = 1u << 5,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_TENDON = 1u << 6,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_MIMIC = 1u << 7,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_CONTROLLER = 1u << 8,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_VEHICLE = 1u << 9,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_PARTICLE = 1u << 10,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_DEFORMABLE = 1u << 11,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_ATTACHMENT = 1u << 12,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_FILTERING = 1u << 13,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_COOKED_DATA = 1u << 14,
    OPENUSD_PHYSICS_EXTRACT_DOMAIN_SIMULATION_METADATA = 1u << 15
} openusd_physics_extract_domain;

typedef enum openusd_physics_extract_object_flags
{
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_NONE = 0,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_ENABLED = 1u << 0,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_DISABLED_BY_DIAGNOSTIC = 1u << 1,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_DYNAMIC = 1u << 2,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_KINEMATIC = 1u << 3,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_ANIMATED = 1u << 4,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_STATIC = 1u << 5,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_INSTANCE_PROXY = 1u << 6,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_IN_PROTOTYPE = 1u << 7,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_PROJECT_OPINIONS = 1u << 8,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_FOREIGN_OPINIONS = 1u << 9,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_STANDARD_OPINIONS = 1u << 10,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_UNSUPPORTED_DOMAIN = 1u << 11,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_INVISIBLE = 1u << 12,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_GUIDE_PURPOSE = 1u << 13,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_TIME_SAMPLED_TRANSFORM = 1u << 14,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_MASS_AUTHORED = 1u << 15,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_CONTRADICTORY_OWNERSHIP = 1u << 16,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_NESTED_BODY = 1u << 17,
    OPENUSD_PHYSICS_EXTRACT_OBJECT_FLAG_DEFAULT_SCENE = 1u << 18
} openusd_physics_extract_object_flags;

typedef enum openusd_physics_extract_geometry
{
    OPENUSD_PHYSICS_EXTRACT_GEOMETRY_NONE = 0,
    OPENUSD_PHYSICS_EXTRACT_GEOMETRY_SPHERE = 1,
    OPENUSD_PHYSICS_EXTRACT_GEOMETRY_BOX = 2,
    OPENUSD_PHYSICS_EXTRACT_GEOMETRY_CAPSULE = 3,
    OPENUSD_PHYSICS_EXTRACT_GEOMETRY_CYLINDER = 4,
    OPENUSD_PHYSICS_EXTRACT_GEOMETRY_CONE = 5,
    OPENUSD_PHYSICS_EXTRACT_GEOMETRY_PLANE = 6,
    OPENUSD_PHYSICS_EXTRACT_GEOMETRY_MESH = 7,
    OPENUSD_PHYSICS_EXTRACT_GEOMETRY_CONVEX_MESH = 8,
    OPENUSD_PHYSICS_EXTRACT_GEOMETRY_POINTS = 9,
    OPENUSD_PHYSICS_EXTRACT_GEOMETRY_TET_MESH = 10
} openusd_physics_extract_geometry;

typedef enum openusd_physics_extract_source
{
    OPENUSD_PHYSICS_EXTRACT_SOURCE_PROJECT = 0,
    OPENUSD_PHYSICS_EXTRACT_SOURCE_FOREIGN = 1,
    OPENUSD_PHYSICS_EXTRACT_SOURCE_STANDARD = 2,
    OPENUSD_PHYSICS_EXTRACT_SOURCE_FALLBACK = 3
} openusd_physics_extract_source;

typedef enum openusd_physics_extract_value_type
{
    OPENUSD_PHYSICS_EXTRACT_VALUE_NONE = 0,
    OPENUSD_PHYSICS_EXTRACT_VALUE_BOOL = 1,
    OPENUSD_PHYSICS_EXTRACT_VALUE_INTEGER = 2,
    OPENUSD_PHYSICS_EXTRACT_VALUE_REAL = 3,
    OPENUSD_PHYSICS_EXTRACT_VALUE_VEC2 = 4,
    OPENUSD_PHYSICS_EXTRACT_VALUE_VEC3 = 5,
    OPENUSD_PHYSICS_EXTRACT_VALUE_VEC4 = 6,
    OPENUSD_PHYSICS_EXTRACT_VALUE_QUAT = 7,
    OPENUSD_PHYSICS_EXTRACT_VALUE_MATRIX4 = 8,
    OPENUSD_PHYSICS_EXTRACT_VALUE_TEXT = 9,
    OPENUSD_PHYSICS_EXTRACT_VALUE_REAL_ARRAY = 10,
    OPENUSD_PHYSICS_EXTRACT_VALUE_INTEGER_ARRAY = 11,
    OPENUSD_PHYSICS_EXTRACT_VALUE_VEC2_ARRAY = 12,
    OPENUSD_PHYSICS_EXTRACT_VALUE_VEC3_ARRAY = 13,
    OPENUSD_PHYSICS_EXTRACT_VALUE_TEXT_ARRAY = 14
} openusd_physics_extract_value_type;

typedef enum openusd_physics_extract_property_flags
{
    OPENUSD_PHYSICS_EXTRACT_PROPERTY_FLAG_NONE = 0,
    OPENUSD_PHYSICS_EXTRACT_PROPERTY_FLAG_TIME_SAMPLED = 1u << 0,
    OPENUSD_PHYSICS_EXTRACT_PROPERTY_FLAG_UNIFORM = 1u << 1,
    OPENUSD_PHYSICS_EXTRACT_PROPERTY_FLAG_UNMAPPED = 1u << 2,
    OPENUSD_PHYSICS_EXTRACT_PROPERTY_FLAG_SHADOWS_WEAKER = 1u << 3,
    OPENUSD_PHYSICS_EXTRACT_PROPERTY_FLAG_INVALID = 1u << 4,
    OPENUSD_PHYSICS_EXTRACT_PROPERTY_FLAG_CONVERTED = 1u << 5,
    OPENUSD_PHYSICS_EXTRACT_PROPERTY_FLAG_AMBIGUOUS_FOREIGN = 1u << 6
} openusd_physics_extract_property_flags;

/*
 * Canonical simulated property keys. A key identifies one simulated quantity independent
 * of which namespace authored it; the winning namespace is reported by the record's
 * source field and the verbatim authored name is always carried alongside. A property
 * that carries no canonical meaning is recorded with key UNMAPPED and its verbatim name.
 */
typedef enum openusd_physics_extract_key
{
    OPENUSD_PHYSICS_EXTRACT_KEY_UNMAPPED = 0,

    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_GRAVITY_DIRECTION = 1,
    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_GRAVITY_MAGNITUDE = 2,
    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_POSITION_ITERATIONS = 3,
    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_VELOCITY_ITERATIONS = 4,
    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_BOUNCE_THRESHOLD = 5,
    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_ENABLE_CCD = 6,
    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_ENABLE_STABILIZATION = 7,
    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_ENABLE_DETERMINISM = 8,
    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_TIME_STEPS_PER_SECOND = 9,
    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_MAX_SUBSTEPS = 10,
    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_GPU_REQUEST_MODE = 11,
    OPENUSD_PHYSICS_EXTRACT_KEY_SCENE_REPORT_CONTACTS = 12,

    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_ENABLED = 20,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_KINEMATIC = 21,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_STARTS_ASLEEP = 22,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_VELOCITY = 23,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_ANGULAR_VELOCITY = 24,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_DISABLE_GRAVITY = 25,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_MAX_LINEAR_VELOCITY = 26,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_MAX_ANGULAR_VELOCITY = 27,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_POSITION_ITERATIONS = 28,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_VELOCITY_ITERATIONS = 29,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_ENABLE_CCD = 30,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_SLEEP_THRESHOLD = 31,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_LINEAR_DAMPING = 32,
    OPENUSD_PHYSICS_EXTRACT_KEY_BODY_ANGULAR_DAMPING = 33,

    OPENUSD_PHYSICS_EXTRACT_KEY_MASS_MASS = 40,
    OPENUSD_PHYSICS_EXTRACT_KEY_MASS_DENSITY = 41,
    OPENUSD_PHYSICS_EXTRACT_KEY_MASS_CENTER_OF_MASS = 42,
    OPENUSD_PHYSICS_EXTRACT_KEY_MASS_DIAGONAL_INERTIA = 43,
    OPENUSD_PHYSICS_EXTRACT_KEY_MASS_PRINCIPAL_AXES = 44,

    OPENUSD_PHYSICS_EXTRACT_KEY_COLLISION_ENABLED = 50,
    OPENUSD_PHYSICS_EXTRACT_KEY_COLLISION_APPROXIMATION = 51,
    OPENUSD_PHYSICS_EXTRACT_KEY_COLLISION_CONTACT_OFFSET = 52,
    OPENUSD_PHYSICS_EXTRACT_KEY_COLLISION_REST_OFFSET = 53,
    OPENUSD_PHYSICS_EXTRACT_KEY_COLLISION_REPORT_CONTACTS = 54,

    OPENUSD_PHYSICS_EXTRACT_KEY_MATERIAL_STATIC_FRICTION = 60,
    OPENUSD_PHYSICS_EXTRACT_KEY_MATERIAL_DYNAMIC_FRICTION = 61,
    OPENUSD_PHYSICS_EXTRACT_KEY_MATERIAL_RESTITUTION = 62,
    OPENUSD_PHYSICS_EXTRACT_KEY_MATERIAL_DENSITY = 63,
    OPENUSD_PHYSICS_EXTRACT_KEY_MATERIAL_FRICTION_COMBINE = 64,
    OPENUSD_PHYSICS_EXTRACT_KEY_MATERIAL_RESTITUTION_COMBINE = 65,

    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_ENABLED = 70,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_LOCAL_POS0 = 71,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_LOCAL_ROT0 = 72,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_LOCAL_POS1 = 73,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_LOCAL_ROT1 = 74,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_AXIS = 75,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_LOWER_LIMIT = 76,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_UPPER_LIMIT = 77,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_MIN_DISTANCE = 78,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_MAX_DISTANCE = 79,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_CONE_ANGLE0 = 80,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_CONE_ANGLE1 = 81,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_BREAK_FORCE = 82,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_BREAK_TORQUE = 83,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_COLLISION_ENABLED = 84,
    OPENUSD_PHYSICS_EXTRACT_KEY_JOINT_EXCLUDE_FROM_ARTICULATION = 85,

    OPENUSD_PHYSICS_EXTRACT_KEY_DRIVE_STIFFNESS = 90,
    OPENUSD_PHYSICS_EXTRACT_KEY_DRIVE_DAMPING = 91,
    OPENUSD_PHYSICS_EXTRACT_KEY_DRIVE_MAX_FORCE = 92,
    OPENUSD_PHYSICS_EXTRACT_KEY_DRIVE_TARGET_POSITION = 93,
    OPENUSD_PHYSICS_EXTRACT_KEY_DRIVE_TARGET_VELOCITY = 94,
    OPENUSD_PHYSICS_EXTRACT_KEY_DRIVE_TYPE = 95,
    OPENUSD_PHYSICS_EXTRACT_KEY_LIMIT_LOW = 96,
    OPENUSD_PHYSICS_EXTRACT_KEY_LIMIT_HIGH = 97,

    OPENUSD_PHYSICS_EXTRACT_KEY_FILTER_INVERT_GROUPS = 100,
    OPENUSD_PHYSICS_EXTRACT_KEY_FILTER_MERGE_GROUP = 101,
    OPENUSD_PHYSICS_EXTRACT_KEY_FILTER_ENABLED = 102,
    OPENUSD_PHYSICS_EXTRACT_KEY_FILTER_MODE = 103,

    OPENUSD_PHYSICS_EXTRACT_KEY_ARTICULATION_FIX_BASE = 110,
    OPENUSD_PHYSICS_EXTRACT_KEY_ARTICULATION_SELF_COLLISIONS = 111,
    OPENUSD_PHYSICS_EXTRACT_KEY_ARTICULATION_POSITION_ITERATIONS = 112,
    OPENUSD_PHYSICS_EXTRACT_KEY_ARTICULATION_VELOCITY_ITERATIONS = 113,

    OPENUSD_PHYSICS_EXTRACT_KEY_SIMULATION_IDENTITY = 120,
    OPENUSD_PHYSICS_EXTRACT_KEY_SIMULATION_IDENTITY_DOMAIN = 121,
    OPENUSD_PHYSICS_EXTRACT_KEY_SIMULATION_IDENTITY_INDEX = 122,

    /* Articulation tendons and the attachments that make up a spatial tendon. */
    OPENUSD_PHYSICS_EXTRACT_KEY_TENDON_ENABLED = 150,
    OPENUSD_PHYSICS_EXTRACT_KEY_TENDON_STIFFNESS = 151,
    OPENUSD_PHYSICS_EXTRACT_KEY_TENDON_DAMPING = 152,
    OPENUSD_PHYSICS_EXTRACT_KEY_TENDON_LIMIT_STIFFNESS = 153,
    OPENUSD_PHYSICS_EXTRACT_KEY_TENDON_OFFSET = 154,
    OPENUSD_PHYSICS_EXTRACT_KEY_TENDON_REST_LENGTH = 155,
    OPENUSD_PHYSICS_EXTRACT_KEY_TENDON_LOWER_LIMIT = 156,
    OPENUSD_PHYSICS_EXTRACT_KEY_TENDON_UPPER_LIMIT = 157,
    OPENUSD_PHYSICS_EXTRACT_KEY_TENDON_GEARINGS = 158,
    OPENUSD_PHYSICS_EXTRACT_KEY_TENDON_FORCE_COEFFICIENTS = 159,
    OPENUSD_PHYSICS_EXTRACT_KEY_ATTACHMENT_GEARING = 160,
    OPENUSD_PHYSICS_EXTRACT_KEY_ATTACHMENT_LOCAL_POSITION = 161,
    OPENUSD_PHYSICS_EXTRACT_KEY_ATTACHMENT_REST_LENGTH = 162,
    OPENUSD_PHYSICS_EXTRACT_KEY_ATTACHMENT_LOWER_LIMIT = 163,
    OPENUSD_PHYSICS_EXTRACT_KEY_ATTACHMENT_UPPER_LIMIT = 164,
    OPENUSD_PHYSICS_EXTRACT_KEY_ATTACHMENT_ROLE = 165,

    /* Mimic joints. */
    OPENUSD_PHYSICS_EXTRACT_KEY_MIMIC_ENABLED = 170,
    OPENUSD_PHYSICS_EXTRACT_KEY_MIMIC_GEARING = 171,
    OPENUSD_PHYSICS_EXTRACT_KEY_MIMIC_OFFSET = 172,
    OPENUSD_PHYSICS_EXTRACT_KEY_MIMIC_AXIS = 173,
    OPENUSD_PHYSICS_EXTRACT_KEY_MIMIC_REFERENCE_AXIS = 174,
    OPENUSD_PHYSICS_EXTRACT_KEY_MIMIC_NATURAL_FREQUENCY = 175,
    OPENUSD_PHYSICS_EXTRACT_KEY_MIMIC_DAMPING_RATIO = 176,

    /* Vehicle chassis and frame. */
    OPENUSD_PHYSICS_EXTRACT_KEY_VEHICLE_ENABLED = 180,
    OPENUSD_PHYSICS_EXTRACT_KEY_VEHICLE_DRIVE_TYPE = 181,
    OPENUSD_PHYSICS_EXTRACT_KEY_VEHICLE_LONGITUDINAL_AXIS = 182,
    OPENUSD_PHYSICS_EXTRACT_KEY_VEHICLE_LATERAL_AXIS = 183,
    OPENUSD_PHYSICS_EXTRACT_KEY_VEHICLE_VERTICAL_AXIS = 184,
    OPENUSD_PHYSICS_EXTRACT_KEY_VEHICLE_SUSPENSION_QUERY_TYPE = 185,

    /* Vehicle engine. */
    OPENUSD_PHYSICS_EXTRACT_KEY_ENGINE_PEAK_TORQUE = 190,
    OPENUSD_PHYSICS_EXTRACT_KEY_ENGINE_MAX_ROTATION_SPEED = 191,
    OPENUSD_PHYSICS_EXTRACT_KEY_ENGINE_IDLE_ROTATION_SPEED = 192,
    OPENUSD_PHYSICS_EXTRACT_KEY_ENGINE_MOMENT_OF_INERTIA = 193,
    OPENUSD_PHYSICS_EXTRACT_KEY_ENGINE_DAMPING_FULL_THROTTLE = 194,
    OPENUSD_PHYSICS_EXTRACT_KEY_ENGINE_DAMPING_ZERO_THROTTLE_CLUTCH_ENGAGED = 195,
    OPENUSD_PHYSICS_EXTRACT_KEY_ENGINE_DAMPING_ZERO_THROTTLE_CLUTCH_DISENGAGED = 196,

    /* Vehicle gearbox, autobox, clutch, differential, brakes and steering. */
    OPENUSD_PHYSICS_EXTRACT_KEY_GEARS_RATIOS = 200,
    OPENUSD_PHYSICS_EXTRACT_KEY_GEARS_RATIO_SCALE = 201,
    OPENUSD_PHYSICS_EXTRACT_KEY_GEARS_SWITCH_TIME = 202,
    OPENUSD_PHYSICS_EXTRACT_KEY_AUTO_GEAR_BOX_UP_RATIOS = 203,
    OPENUSD_PHYSICS_EXTRACT_KEY_AUTO_GEAR_BOX_DOWN_RATIOS = 204,
    OPENUSD_PHYSICS_EXTRACT_KEY_AUTO_GEAR_BOX_LATENCY = 205,
    OPENUSD_PHYSICS_EXTRACT_KEY_CLUTCH_STRENGTH = 206,
    OPENUSD_PHYSICS_EXTRACT_KEY_DIFFERENTIAL_WHEELS = 207,
    OPENUSD_PHYSICS_EXTRACT_KEY_DIFFERENTIAL_TORQUE_RATIOS = 208,
    OPENUSD_PHYSICS_EXTRACT_KEY_BRAKES_MAX_BRAKE_TORQUE = 209,
    OPENUSD_PHYSICS_EXTRACT_KEY_BRAKES_WHEELS = 210,
    OPENUSD_PHYSICS_EXTRACT_KEY_BRAKES_TORQUE_MULTIPLIERS = 211,
    OPENUSD_PHYSICS_EXTRACT_KEY_STEERING_MAX_STEER_ANGLE = 212,
    OPENUSD_PHYSICS_EXTRACT_KEY_STEERING_WHEELS = 213,
    OPENUSD_PHYSICS_EXTRACT_KEY_STEERING_ANGLE_MULTIPLIERS = 214,
    OPENUSD_PHYSICS_EXTRACT_KEY_BRAKES_SECONDARY_MAX_BRAKE_TORQUE = 215,
    OPENUSD_PHYSICS_EXTRACT_KEY_BRAKES_SECONDARY_WHEELS = 216,
    OPENUSD_PHYSICS_EXTRACT_KEY_BRAKES_SECONDARY_TORQUE_MULTIPLIERS = 217,

    /* Vehicle wheel attachment, wheel, suspension and tire. */
    OPENUSD_PHYSICS_EXTRACT_KEY_WHEEL_ATTACHMENT_INDEX = 220,
    OPENUSD_PHYSICS_EXTRACT_KEY_WHEEL_ATTACHMENT_SUSPENSION_POSITION = 221,
    OPENUSD_PHYSICS_EXTRACT_KEY_WHEEL_ATTACHMENT_SUSPENSION_TRAVEL_DIR = 222,
    OPENUSD_PHYSICS_EXTRACT_KEY_WHEEL_ATTACHMENT_WHEEL_POSITION = 223,
    OPENUSD_PHYSICS_EXTRACT_KEY_WHEEL_RADIUS = 224,
    OPENUSD_PHYSICS_EXTRACT_KEY_WHEEL_WIDTH = 225,
    OPENUSD_PHYSICS_EXTRACT_KEY_WHEEL_MASS = 226,
    OPENUSD_PHYSICS_EXTRACT_KEY_WHEEL_MOMENT_OF_INERTIA = 227,
    OPENUSD_PHYSICS_EXTRACT_KEY_WHEEL_DAMPING_RATE = 228,
    OPENUSD_PHYSICS_EXTRACT_KEY_SUSPENSION_SPRING_STRENGTH = 229,
    OPENUSD_PHYSICS_EXTRACT_KEY_SUSPENSION_SPRING_DAMPER_RATE = 230,
    OPENUSD_PHYSICS_EXTRACT_KEY_SUSPENSION_TRAVEL_DISTANCE = 231,
    OPENUSD_PHYSICS_EXTRACT_KEY_SUSPENSION_SPRUNG_MASS = 232,
    OPENUSD_PHYSICS_EXTRACT_KEY_TIRE_LONGITUDINAL_STIFFNESS = 233,
    OPENUSD_PHYSICS_EXTRACT_KEY_TIRE_CAMBER_STIFFNESS = 234,
    OPENUSD_PHYSICS_EXTRACT_KEY_TIRE_REST_LOAD = 235,

    /* Character controller. */
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_ENABLED = 240,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_SHAPE_TYPE = 241,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_RADIUS = 242,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_HEIGHT = 243,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_HALF_EXTENTS = 244,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_UP_AXIS = 245,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_SLOPE_LIMIT = 246,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_STEP_OFFSET = 247,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_CONTACT_OFFSET = 248,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_DENSITY = 249,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_SCALE_COEFF = 250,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_VOLUME_GROWTH = 251,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_NON_WALKABLE_MODE = 252,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_CLIMBING_MODE = 253,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_MIN_MOVE_DISTANCE = 254,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_MAX_JUMP_HEIGHT = 255,
    OPENUSD_PHYSICS_EXTRACT_KEY_CONTROLLER_INVISIBLE_WALL_HEIGHT = 256,

    /* Position based dynamics particle systems. */
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_ENABLED = 260,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_CONTACT_OFFSET = 261,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_REST_OFFSET = 262,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_PARTICLE_CONTACT_OFFSET = 263,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_SOLID_REST_OFFSET = 264,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_FLUID_REST_OFFSET = 265,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_MAX_DEPENETRATION_VELOCITY = 266,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_NEIGHBORHOOD_SCALE = 267,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_MAX_NEIGHBORHOOD = 268,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_SOLVER_POSITION_ITERATIONS = 269,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_WIND = 270,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_ENABLE_CCD = 271,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_GLOBAL_SELF_COLLISION = 272,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_SYSTEM_NON_PARTICLE_COLLISION = 273,

    /* Particle sets and particle cloth. */
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_BODY_ENABLED = 280,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_BODY_FLUID = 281,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_BODY_MASS = 282,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_BODY_GROUP = 283,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_BODY_SELF_COLLISION = 284,
    OPENUSD_PHYSICS_EXTRACT_KEY_PARTICLE_BODY_REST_POINTS = 285,

    /* Position based dynamics material response. */
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_FRICTION = 300,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_DAMPING = 301,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_ADHESION = 302,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_ADHESION_OFFSET_SCALE = 303,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_PARTICLE_FRICTION_SCALE = 304,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_PARTICLE_ADHESION_SCALE = 305,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_VISCOSITY = 306,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_SURFACE_TENSION = 307,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_COHESION = 308,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_VORTICITY_CONFINEMENT = 309,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_DRAG = 310,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_LIFT = 311,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_GRAVITY_SCALE = 312,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_DENSITY = 313,
    OPENUSD_PHYSICS_EXTRACT_KEY_PBD_MATERIAL_CFL_COEFFICIENT = 314,

    /* Surface and volume deformables. The two share every key whose meaning is
     * identical so the vocabulary stays namespace neutral; the object kind is
     * what tells a consumer which solver the value belongs to. */
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_ENABLED = 320,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_ENABLE_CCD = 321,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_SELF_COLLISION = 322,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_SELF_COLLISION_FILTER_DISTANCE = 323,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_SOLVER_POSITION_ITERATIONS = 324,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_VERTEX_VELOCITY_DAMPING = 325,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MAX_DISPLACEMENT = 326,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_COLLISION_ITERATION_MULTIPLIER = 327,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_COLLISION_PAIR_UPDATE_FREQUENCY = 328,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_REST_POINTS = 329,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_SIMULATION_INDICES = 330,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_KINEMATIC = 331,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MAX_DEPENETRATION_VELOCITY = 332,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_SETTLING_THRESHOLD = 333,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_SLEEP_THRESHOLD = 334,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_SIMULATION_REST_POINTS = 335,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_COLLISION_INDICES = 336,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_COLLISION_REST_POINTS = 337,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_HEXAHEDRAL_RESOLUTION = 338,

    /* Surface and volume deformable material response. */
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MATERIAL_YOUNGS_MODULUS = 350,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MATERIAL_POISSONS_RATIO = 351,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MATERIAL_DYNAMIC_FRICTION = 352,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MATERIAL_DENSITY = 353,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MATERIAL_ELASTICITY_DAMPING = 354,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MATERIAL_BENDING_STIFFNESS = 355,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MATERIAL_BENDING_DAMPING = 356,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MATERIAL_THICKNESS = 357,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MATERIAL_DAMPING = 358,
    OPENUSD_PHYSICS_EXTRACT_KEY_DEFORMABLE_MATERIAL_DAMPING_SCALE = 359,

    /* Relationship keys share the enumeration so one lookup covers both sections. */
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_SIMULATION_OWNER = 130,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_BODY0 = 131,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_BODY1 = 132,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_FILTERED_PAIRS = 133,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_FILTERED_GROUPS = 134,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_MATERIAL_BINDING = 135,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_COLLIDERS = 136,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_ATTACHMENT_ACTOR0 = 137,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_ATTACHMENT_ACTOR1 = 138,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_ARTICULATION = 139,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_PARTICLE_SYSTEM = 140,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_TENDON_ROOT_JOINT = 141,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_TENDON_JOINTS = 142,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_TENDON_ROOT_ATTACHMENT = 143,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_ATTACHMENT_TENDON = 144,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_ATTACHMENT_PARENT = 145,
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_MIMIC_REFERENCE_JOINT = 146,
    /* The material a particle body or a deformable binds through its own
     * project namespace relationship rather than through material:binding. */
    OPENUSD_PHYSICS_EXTRACT_KEY_REL_DEFORMABLE_MATERIAL = 147
} openusd_physics_extract_key;

typedef enum openusd_physics_extract_severity
{
    OPENUSD_PHYSICS_EXTRACT_SEVERITY_INFORMATION = 0,
    OPENUSD_PHYSICS_EXTRACT_SEVERITY_WARNING = 1,
    OPENUSD_PHYSICS_EXTRACT_SEVERITY_ERROR = 2
} openusd_physics_extract_severity;

typedef enum openusd_physics_extract_category
{
    OPENUSD_PHYSICS_EXTRACT_CATEGORY_UNITS = 0,
    OPENUSD_PHYSICS_EXTRACT_CATEGORY_OWNERSHIP = 1,
    OPENUSD_PHYSICS_EXTRACT_CATEGORY_SCHEMA = 2,
    OPENUSD_PHYSICS_EXTRACT_CATEGORY_PRECEDENCE = 3,
    OPENUSD_PHYSICS_EXTRACT_CATEGORY_CAPABILITY = 4,
    OPENUSD_PHYSICS_EXTRACT_CATEGORY_GEOMETRY = 5,
    OPENUSD_PHYSICS_EXTRACT_CATEGORY_CAPACITY = 6,
    OPENUSD_PHYSICS_EXTRACT_CATEGORY_INSTANCE = 7
} openusd_physics_extract_category;

typedef enum openusd_physics_extract_code
{
    OPENUSD_PHYSICS_EXTRACT_CODE_NONE = 0,
    OPENUSD_PHYSICS_EXTRACT_CODE_KILOGRAMS_PER_UNIT_FALLBACK = 1,
    OPENUSD_PHYSICS_EXTRACT_CODE_METERS_PER_UNIT_FALLBACK = 2,
    OPENUSD_PHYSICS_EXTRACT_CODE_TIME_CODES_PER_SECOND_FALLBACK = 3,
    OPENUSD_PHYSICS_EXTRACT_CODE_TIME_RANGE_FALLBACK = 4,
    OPENUSD_PHYSICS_EXTRACT_CODE_UP_AXIS_CONVERTED = 5,
    OPENUSD_PHYSICS_EXTRACT_CODE_NON_FINITE_UNITS = 6,
    OPENUSD_PHYSICS_EXTRACT_CODE_MULTIPLE_SIMULATION_OWNERS = 10,
    OPENUSD_PHYSICS_EXTRACT_CODE_UNKNOWN_SIMULATION_OWNER = 11,
    OPENUSD_PHYSICS_EXTRACT_CODE_NESTED_RIGID_BODY = 12,
    OPENUSD_PHYSICS_EXTRACT_CODE_CONTRADICTORY_OWNERSHIP = 13,
    OPENUSD_PHYSICS_EXTRACT_CODE_ANIMATED_DYNAMIC_BODY = 14,
    OPENUSD_PHYSICS_EXTRACT_CODE_JOINT_BODY_UNRESOLVED = 15,
    OPENUSD_PHYSICS_EXTRACT_CODE_ORPHANED_COLLIDER = 16,
    OPENUSD_PHYSICS_EXTRACT_CODE_FOREIGN_OPINION_USED = 20,
    OPENUSD_PHYSICS_EXTRACT_CODE_FOREIGN_OPINION_AMBIGUOUS = 21,
    OPENUSD_PHYSICS_EXTRACT_CODE_FOREIGN_OPINION_UNMAPPED = 22,
    OPENUSD_PHYSICS_EXTRACT_CODE_PROPERTY_TYPE_UNSUPPORTED = 23,
    OPENUSD_PHYSICS_EXTRACT_CODE_PROPERTY_VALUE_INVALID = 24,
    OPENUSD_PHYSICS_EXTRACT_CODE_DOMAIN_NOT_SIMULATED = 30,
    OPENUSD_PHYSICS_EXTRACT_CODE_GEOMETRY_UNSUPPORTED = 31,
    OPENUSD_PHYSICS_EXTRACT_CODE_GEOMETRY_DEGENERATE = 32,
    OPENUSD_PHYSICS_EXTRACT_CODE_CAPACITY_EXCEEDED = 40,
    OPENUSD_PHYSICS_EXTRACT_CODE_INSTANCE_PROXY_LIMIT = 41
} openusd_physics_extract_code;

/* Caller-provided extraction bounds. Zero requests the built-in default bound. */
typedef struct openusd_physics_extract_options
{
    uint32_t struct_size;
    uint32_t version;
    /* The time code to sample at. A non-finite value requests the default time. */
    double time_code;
    uint32_t flags;
    uint32_t max_objects;
    uint32_t max_properties;
    uint32_t max_relationships;
    uint32_t max_targets;
    uint32_t max_numbers;
    uint32_t max_texts;
    uint32_t max_points;
    uint32_t max_indices;
    uint32_t max_diagnostics;
    uint32_t max_string_bytes;
    uint32_t reserved0;
} openusd_physics_extract_options;

#define OPENUSD_PHYSICS_EXTRACT_OPTIONS_VERSION 1u

typedef enum openusd_physics_extract_option_flags
{
    OPENUSD_PHYSICS_EXTRACT_OPTION_NONE = 0,
    /* Record collider geometry point and index data for mesh approximations. */
    OPENUSD_PHYSICS_EXTRACT_OPTION_INCLUDE_MESH_DATA = 1u << 0,
    /* Record every authored physics property, not only canonical simulated keys. */
    OPENUSD_PHYSICS_EXTRACT_OPTION_INCLUDE_UNMAPPED = 1u << 1,
    /* Skip prims whose composed visibility is invisible. */
    OPENUSD_PHYSICS_EXTRACT_OPTION_SKIP_INVISIBLE = 1u << 2,
    /* Skip prims whose composed purpose is guide. */
    OPENUSD_PHYSICS_EXTRACT_OPTION_SKIP_GUIDE = 1u << 3
} openusd_physics_extract_option_flags;

/* A borrowed, immutable view of one extraction page. */
typedef struct openusd_physics_extract_view
{
    uint32_t struct_size;
    uint32_t version;
    const unsigned char* data;
    size_t byte_size;
} openusd_physics_extract_view;

#define OPENUSD_PHYSICS_EXTRACT_VIEW_VERSION 1u

typedef struct openusd_physics_extraction openusd_physics_extraction;

/*
 * Traverses the composed stage exactly once and produces one extraction page.
 *
 * The page is owned by the returned extraction object; the view borrows it until
 * openusd_physics_extraction_release is called. The call performs no callback into
 * managed code, retains no stage reference beyond its own scope, and never publishes a
 * pointer into the page contents.
 */
OPENUSD_DOTNET_API openusd_status openusd_physics_extract_stage(
    const openusd_stage* stage,
    const openusd_physics_extract_options* options,
    openusd_physics_extraction** extraction,
    openusd_physics_extract_view* view,
    openusd_error_buffer* error);

/* Releases one extraction produced by openusd_physics_extract_stage. */
OPENUSD_DOTNET_API void openusd_physics_extraction_release(
    openusd_physics_extraction* extraction);

/*
 * Returns how many stage traversals this process has performed. Tests assert that one
 * extraction of an arbitrarily large stage advances the counter by exactly one.
 */
OPENUSD_DOTNET_API uint64_t openusd_physics_extract_get_traversal_count(void);

/* Returns how many prims the last completed traversal visited. */
OPENUSD_DOTNET_API uint64_t openusd_physics_extract_get_visited_prim_count(void);

#ifdef __cplusplus
}
#endif

#endif
