# Copyright (c) marcschier. Licensed under the MIT License.
#
# Generates or verifies docs/support-manifest.md from eng/support-manifest.json.
#
# Usage:
#   python eng/generate-support-manifest.py            # generate the document
#   python eng/generate-support-manifest.py --verify   # fail if stale
#
# Stale-claim detection in --verify mode:
#   - Every evidenceTests path must exist under the repository root.
#   - Every workflow claim must name an existing workflow job.
#   - Native capability coverage must match the native header exactly.
#   - The manifest version must match version.json.
#   - The committed docs/support-manifest.md must match the generated output exactly.

import argparse
import difflib
import json
import pathlib
import re
import sys


CAPABILITY_DEFINE_PATTERN = re.compile(
    r"#define\s+(OPENUSD_CAPABILITY_[A-Z0-9_]+)\s+\(UINT64_C\(1\)",
    re.MULTILINE,
)

VALID_STATUSES = frozenset({
    "implemented",
    "workflow-gated",
    "compile-only",
    "pending-hosted-proof",
    "implemented-not-gated",
    "excluded",
    "unreachable",
    "not-supported",
})

STATUSES_REQUIRING_EVIDENCE = frozenset({
    "implemented",
    "workflow-gated",
    "compile-only",
    "pending-hosted-proof",
    "implemented-not-gated",
})

VALID_PLATFORMS = frozenset({"win-x64", "linux-x64", "osx-arm64"})

STATUSES_REQUIRING_WORKFLOW = frozenset({
    "workflow-gated",
    "compile-only",
    "pending-hosted-proof",
})

STATUSES_REQUIRING_TEST = frozenset({
    "implemented",
    "implemented-not-gated",
})

GENERATED_DOC_PATH = "docs/support-manifest.md"


def read_text(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def write_text(path: pathlib.Path, value: str) -> None:
    path.write_text(value, encoding="utf-8", newline="\n")


def unified_diff(path: pathlib.Path, current: str, generated: str) -> str:
    return "".join(difflib.unified_diff(
        current.splitlines(keepends=True),
        generated.splitlines(keepends=True),
        fromfile=str(path),
        tofile=f"{path} (generated)",
        lineterm="\n",
    ))


def _status_badge(status: str) -> str:
    mapping = {
        "implemented": "Implemented",
        "workflow-gated": "Workflow-gated",
        "compile-only": "Compile-only",
        "pending-hosted-proof": "Pending hosted proof",
        "implemented-not-gated": "Implemented, not gated",
        "excluded": "Excluded",
        "unreachable": "Unreachable",
        "not-supported": "Not supported",
    }
    return mapping.get(status, status)


def _wrap_text(text: str, max_width: int) -> list[str]:
    """Wrap text to lines of at most max_width characters."""
    words = text.split()
    lines: list[str] = []
    current: list[str] = []
    current_len = 0
    for word in words:
        if current and current_len + 1 + len(word) > max_width:
            lines.append(" ".join(current))
            current = [word]
            current_len = len(word)
        else:
            current.append(word)
            current_len = current_len + 1 + len(word) if current_len else len(word)
    if current:
        lines.append(" ".join(current))
    return lines


def generate_document(manifest: dict) -> str:
    version = manifest["version"]
    lines: list[str] = []

    lines.append("<!-- generated by eng/generate-support-manifest.py -- do not edit -->")
    lines.append("")
    lines.append("# OpenUSD support manifest")
    lines.append("")
    for wrapped in _wrap_text(
        f"Executable support summary for `{version}`. Generated from "
        "`eng/support-manifest.json`; do not edit by hand. The source manifest "
        "contains descriptions, evidence paths, platform claims, native ABI "
        "cross-references, and exclusion reasons. "
        "See [`docs/support-matrix.md`](support-matrix.md) for the full "
        "human-authored support matrix with narrative detail.",
        120,
    ):
        lines.append(wrapped)
    lines.append("")

    lines.append("## Status terms")
    lines.append("")
    lines.append("| Term | Meaning |")
    lines.append("| --- | --- |")
    for status, meaning in manifest["statusTerms"].items():
        lines.append(f"| {_status_badge(status)} | {meaning} |")
    lines.append("")

    for area in manifest["areas"]:
        lines.append(f"## {area['title']}")
        lines.append("")
        desc = area.get("description")
        if desc:
            for wrapped in _wrap_text(desc, 120):
                lines.append(wrapped)
            lines.append("")

        lines.append("| Feature | Status |")
        lines.append("| --- | --- |")

        for entry in area["entries"]:
            entry_id = entry["id"]
            status = entry["status"]
            badge = _status_badge(status)
            lines.append(f"| `{entry_id}` | {badge} |")

        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "_This document is regenerated by `python eng/generate-support-manifest.py`._"
    )
    lines.append(
        "_Run without `--verify` to update it after editing"
        " `eng/support-manifest.json`._"
    )
    lines.append("")

    return "\n".join(lines)


def validate_manifest(
    manifest: dict,
    root: pathlib.Path,
    native_capabilities: set[str],
    expected_version: str,
) -> list[str]:
    """Returns a list of error messages; empty means the manifest is valid."""
    errors: list[str] = []

    if manifest.get("$schemaVersion") != 1:
        errors.append("Manifest $schemaVersion must be 1")

    if "version" not in manifest:
        errors.append("Manifest missing 'version' field")
    elif manifest["version"] != expected_version:
        errors.append(
            f"Manifest version '{manifest['version']}' does not match "
            f"version.json '{expected_version}'"
        )

    if manifest.get("generatedDocPath") != GENERATED_DOC_PATH:
        errors.append(
            f"Manifest generatedDocPath must be '{GENERATED_DOC_PATH}'"
        )

    valid_statuses = set(manifest.get("statusTerms", {}).keys())
    if valid_statuses != VALID_STATUSES:
        errors.append(
            "Manifest statusTerms must define exactly: "
            f"{', '.join(sorted(VALID_STATUSES))}"
        )

    seen_ids: set[str] = set()
    seen_area_ids: set[str] = set()
    declared_native_capabilities: list[str] = []
    resolved_root = root.resolve()
    for area in manifest.get("areas", []):
        area_id = area.get("id", "<unknown>")
        if not isinstance(area_id, str) or not area_id.strip():
            errors.append("Every area requires a non-empty string id")
        if not isinstance(area.get("title"), str) or not area["title"].strip():
            errors.append(f"{area_id}: area requires a non-empty title")
        if not isinstance(area.get("description"), str) or not area[
            "description"
        ].strip():
            errors.append(f"{area_id}: area requires a non-empty description")
        if not isinstance(area.get("entries"), list) or not area["entries"]:
            errors.append(f"{area_id}: area requires at least one entry")
            continue
        if area_id in seen_area_ids:
            errors.append(f"Duplicate area id '{area_id}'")
        seen_area_ids.add(area_id)
        for entry in area.get("entries", []):
            entry_id = entry.get("id", "<missing>")
            full_id = f"{area_id}/{entry_id}"
            if not isinstance(entry_id, str) or not entry_id.strip():
                errors.append(f"{area_id}: every entry requires a non-empty string id")
            if not isinstance(entry.get("description"), str) or not entry[
                "description"
            ].strip():
                errors.append(f"{full_id}: entry requires a non-empty description")

            if entry_id in seen_ids:
                errors.append(f"{full_id}: duplicate entry id '{entry_id}'")
            seen_ids.add(entry_id)

            status = entry.get("status")
            if status not in valid_statuses:
                errors.append(
                    f"{full_id}: invalid status '{status}'; "
                    f"must be one of: {', '.join(sorted(valid_statuses))}"
                )

            # Stale-claim check 1: evidence paths must exist when the status
            # makes a positive implementation claim.
            if status in STATUSES_REQUIRING_EVIDENCE:
                test_paths = entry.get("evidenceTests", [])
                workflow_files = entry.get("evidenceWorkflows", [])
                if not test_paths and not workflow_files:
                    errors.append(
                        f"{full_id}: status '{status}' requires at least one "
                        "evidenceTests or evidenceWorkflows entry"
                    )
                platforms = entry.get("evidencePlatforms", [])
                if not platforms:
                    errors.append(
                        f"{full_id}: status '{status}' requires evidencePlatforms"
                    )
                unknown_platforms = sorted(set(platforms) - VALID_PLATFORMS)
                if unknown_platforms:
                    errors.append(
                        f"{full_id}: unknown evidencePlatforms: "
                        f"{', '.join(unknown_platforms)}"
                    )
            if (
                status in STATUSES_REQUIRING_WORKFLOW
                and not entry.get("evidenceWorkflows")
            ):
                errors.append(
                    f"{full_id}: status '{status}' requires evidenceWorkflows"
                )
            if status in STATUSES_REQUIRING_TEST and not entry.get(
                "evidenceTests"
            ):
                errors.append(
                    f"{full_id}: status '{status}' requires evidenceTests"
                )

            # Stale-claim check 2: referenced test paths must exist.
            for test_path in entry.get("evidenceTests", []):
                if (
                    not isinstance(test_path, str)
                    or "\\" in test_path
                    or pathlib.PurePosixPath(test_path).is_absolute()
                    or ".." in pathlib.PurePosixPath(test_path).parts
                ):
                    errors.append(
                        f"{full_id}: evidenceTests path must be repository-relative: "
                        f"{test_path}"
                    )
                    continue
                full_path = (root / test_path).resolve()
                if not full_path.is_relative_to(resolved_root):
                    errors.append(
                        f"{full_id}: evidenceTests path escapes repository: "
                        f"{test_path}"
                    )
                    continue
                if not full_path.exists():
                    errors.append(
                        f"{full_id}: evidenceTests path does not exist: {test_path}"
                    )

            # Stale-claim check 3: referenced workflow files must exist.
            workflow_jobs = entry.get("evidenceWorkflowJobs", {})
            for workflow_file in entry.get("evidenceWorkflows", []):
                if (
                    not isinstance(workflow_file, str)
                    or "\\" in workflow_file
                    or len(pathlib.PurePosixPath(workflow_file).parts) != 1
                ):
                    errors.append(
                        f"{full_id}: evidenceWorkflows must contain file names only: "
                        f"{workflow_file}"
                    )
                    continue
                workflow_path = root / ".github" / "workflows" / workflow_file
                if not workflow_path.exists():
                    errors.append(
                        f"{full_id}: evidenceWorkflows file does not exist: {workflow_file}"
                    )
                    continue
                jobs = workflow_jobs.get(workflow_file, [])
                if not jobs:
                    errors.append(
                        f"{full_id}: workflow '{workflow_file}' requires at least "
                        "one evidenceWorkflowJobs job id"
                    )
                    continue
                workflow_text = read_text(workflow_path)
                for job in jobs:
                    job_pattern = re.compile(
                        rf"^  {re.escape(job)}:\s*$",
                        re.MULTILINE,
                    )
                    if not job_pattern.search(workflow_text):
                        errors.append(
                            f"{full_id}: job '{job}' does not exist in workflow "
                            f"'{workflow_file}'"
                        )
            extra_job_workflows = sorted(
                set(workflow_jobs) - set(entry.get("evidenceWorkflows", []))
            )
            if extra_job_workflows:
                errors.append(
                    f"{full_id}: evidenceWorkflowJobs has unreferenced workflows: "
                    f"{', '.join(extra_job_workflows)}"
                )

            # Stale-claim check 4: nativeCapability must exist in header.
            native_cap = entry.get("nativeCapability")
            if native_cap:
                declared_native_capabilities.append(native_cap)
                if native_cap not in native_capabilities:
                    errors.append(
                        f"{full_id}: nativeCapability '{native_cap}' not found "
                        "in native/openusd_dotnet/include/openusd_dotnet.h"
                    )

            # Excluded/unreachable entries must have an exclusionReason.
            if status in ("excluded", "unreachable", "not-supported"):
                if not entry.get("exclusionReason"):
                    errors.append(
                        f"{full_id}: status '{status}' must include an exclusionReason"
                    )

    duplicate_native_capabilities = sorted({
        capability
        for capability in declared_native_capabilities
        if declared_native_capabilities.count(capability) > 1
    })
    if duplicate_native_capabilities:
        errors.append(
            "Native capabilities mapped more than once: "
            f"{', '.join(duplicate_native_capabilities)}"
        )
    missing_native_capabilities = sorted(
        native_capabilities - set(declared_native_capabilities)
    )
    if missing_native_capabilities:
        errors.append(
            "Native capabilities missing from manifest: "
            f"{', '.join(missing_native_capabilities)}"
        )

    return errors


def parse_native_capabilities(header_text: str) -> set[str]:
    return set(CAPABILITY_DEFINE_PATTERN.findall(header_text))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate or verify the support manifest document."
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Verify that the committed document is up to date; exit 1 if not.",
    )
    args = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parents[1]
    manifest_path = root / "eng" / "support-manifest.json"
    header_path = (
        root / "native" / "openusd_dotnet" / "include" / "openusd_dotnet.h"
    )

    try:
        manifest = json.loads(read_text(manifest_path))
    except (json.JSONDecodeError, OSError) as exc:
        print(f"Failed to read support manifest: {exc}", file=sys.stderr)
        return 1

    try:
        native_capabilities = parse_native_capabilities(read_text(header_path))
    except OSError as exc:
        print(f"Failed to read native header: {exc}", file=sys.stderr)
        return 1

    try:
        expected_version = json.loads(read_text(root / "version.json"))["version"]
    except (KeyError, json.JSONDecodeError, OSError) as exc:
        print(f"Failed to read version.json: {exc}", file=sys.stderr)
        return 1

    # Validate manifest integrity and stale-claim checks.
    errors = validate_manifest(
        manifest,
        root,
        native_capabilities,
        expected_version,
    )
    if errors:
        print(
            f"Support manifest validation failed with {len(errors)} error(s):",
            file=sys.stderr,
        )
        for error in errors:
            print(f"  {error}", file=sys.stderr)
        return 1

    generated = generate_document(manifest)

    doc_path = root / manifest["generatedDocPath"]

    if args.verify:
        if not doc_path.exists():
            print(
                f"Generated support document is missing: {doc_path}\n"
                "Run 'python eng/generate-support-manifest.py' to create it.",
                file=sys.stderr,
            )
            return 1
        current = read_text(doc_path)
        if current != generated:
            print(
                f"Generated support document is out of date: {doc_path}\n"
                "Run 'python eng/generate-support-manifest.py' to regenerate it.",
                file=sys.stderr,
            )
            print(unified_diff(doc_path, current, generated), file=sys.stderr)
            return 1
        print(f"Support manifest verified: {doc_path}")
        return 0

    write_text(doc_path, generated)
    print(f"Support manifest generated: {doc_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
