# Copyright (c) marcschier. Licensed under the MIT License.

import re


SCALARS = {
    "uint32_t": "uint",
    "int32_t": "int",
    "uint64_t": "ulong",
}


def pascal_case(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def fields(header: str, native_name: str) -> list[tuple[str, str]]:
    match = re.search(
        rf"typedef struct {native_name}\s*\{{(?P<body>.*?)\}}\s*{native_name};",
        header, re.DOTALL)
    if match is None:
        raise ValueError(f"Missing EXR structure: {native_name}")
    result = []
    for line in match.group("body").splitlines():
        if not line.strip():
            continue
        field = re.fullmatch(r"\s*(uint32_t|int32_t|uint64_t)\s+(\w+);\s*", line)
        if field is None:
            raise ValueError(f"Unsupported EXR field declaration: {line.strip()}")
        result.append((field.group(1), field.group(2)))
    return result


def layout_size(members: list[tuple[str, str]]) -> int:
    offset = 0
    for scalar, _ in members:
        size = 8 if scalar == "uint64_t" else 4
        offset = (offset + size - 1) // size * size + size
    return (offset + 7) // 8 * 8


def structure(name: str, members: list[tuple[str, str]]) -> str:
    declarations = []
    for scalar, field in members:
        managed_type = "OpenUsdImageEncodeStatus" if field == "status" else SCALARS[scalar]
        declarations.append(f"    internal {managed_type} {pascal_case(field)};")
    return (
        "[StructLayout(LayoutKind.Sequential, Pack = 8)]\n"
        f"internal struct {name}\n{{\n"
        + "\n".join(declarations)
        + "\n}"
    )


def generate(header: str) -> str:
    version = re.search(r"^#define OPENUSD_IMAGE_EXR_VERSION (\d+)u$", header, re.MULTILINE)
    if version is None or version.group(1) != "1":
        raise ValueError("EXR generator requires explicit request/result version 1")
    request = fields(header, "openusd_image_encode_exr_request_v1")
    result = fields(header, "openusd_image_encode_exr_result_v1")
    if layout_size(request) != 112 or layout_size(result) != 40:
        raise ValueError("EXR version-1 layouts must remain exactly 112/40 bytes")
    statuses = re.findall(r"^#define OPENUSD_IMAGE_ENCODE_([A-Z_]+) (\d+)u$", header, re.MULTILINE)
    statuses = [(name, int(value)) for name, value in statuses if not name.startswith("PHASE_")]
    if [value for _, value in statuses] != list(range(8)):
        raise ValueError("EXR encode status domain must remain explicitly ordered 0..7")
    callback = re.search(
        r"typedef uint32_t \(OPENUSD_IMAGE_ENCODE_CALL \*openusd_image_encode_cancel_v1\)"
        r"\(\s*void\* context, uint32_t phase, uint32_t completed_rows, uint64_t output_extent\);",
        header)
    if callback is None:
        raise ValueError("EXR cancellation callback ABI changed")
    function = re.search(
        r"OPENUSD_DOTNET_API uint32_t OPENUSD_IMAGE_ENCODE_CALL openusd_image_encode_exr_rgba16f_v1"
        r"\((?P<parameters>.*?)\);", header, re.DOTALL)
    expected = [
        "const openusd_image_encode_exr_request_v1* request",
        "uint32_t request_bytes",
        "const uint8_t* rgba16f_le",
        "uint64_t rgba16f_bytes",
        "uint64_t windows_file_handle",
        "openusd_image_encode_cancel_v1 cancellation",
        "void* cancellation_context",
        "openusd_image_encode_exr_result_v1* result",
        "uint32_t result_bytes",
    ]
    if function is None or [
        " ".join(parameter.split()) for parameter in function.group("parameters").split(",")
    ] != expected:
        raise ValueError("EXR bulk operation signature changed")
    enum_members = ",\n".join(f"    {pascal_case(name.lower())} = {value}" for name, value in statuses)
    request_text = structure("OpenUsdImageExrRequest", request)
    result_text = structure("OpenUsdImageExrResult", result)
    return f"""// Copyright (c) marcschier. Licensed under the MIT License.
// <auto-generated />
#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace OpenUsd.Interop;

internal enum OpenUsdImageEncodeStatus : uint
{{
{enum_members}
}}

{request_text}

{result_text}

public static unsafe partial class OpenUsdNativeRuntime
{{
    private static partial class NativeMethods
    {{
        [LibraryImport(OpenUsdNativeContract.LibraryName, EntryPoint = "openusd_image_encode_exr_rgba16f_v1")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial uint EncodeExrRgba16Float(
            OpenUsdImageExrRequest* request,
            uint requestBytes,
            byte* rgba16fLe,
            ulong rgba16fBytes,
            ulong borrowedWindowsHandle,
            delegate* unmanaged[Cdecl]<nint, uint, uint, ulong, uint> cancellation,
            nint cancellationContext,
            OpenUsdImageExrResult* result,
            uint resultBytes);
    }}
}}
"""
