<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenUsd\OpenUsd.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>OpenUsd.HelloStage</AssemblyName>
    <RootNamespace>OpenUsd.HelloStage</RootNamespace>
    <IsSampleProject>true</IsSampleProject>
  </PropertyGroup>

</Project>
