# Copyright (c) marcschier. Licensed under the MIT License.

cmake_minimum_required(VERSION 3.28)
foreach(required REPO_ROOT SDK_INCLUDE_ROOT WORK_ROOT BUILD_GENERATOR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required for the owned header-identity probe.")
    endif()
endforeach()
file(TO_CMAKE_PATH "${REPO_ROOT}" REPO_ROOT)
file(TO_CMAKE_PATH "${SDK_INCLUDE_ROOT}" SDK_INCLUDE_ROOT)
file(TO_CMAKE_PATH "${WORK_ROOT}" WORK_ROOT)
set(copy "${WORK_ROOT}/sdk")
set(project "${WORK_ROOT}/project")
set(build "${WORK_ROOT}/build")
file(MAKE_DIRECTORY "${copy}/pxr/usd/pcp" "${project}")
file(COPY_FILE "${SDK_INCLUDE_ROOT}/pxr/pxr.h" "${copy}/pxr/pxr.h")
foreach(header primIndex.h layerStack.h errors.h)
    file(COPY_FILE "${SDK_INCLUDE_ROOT}/pxr/usd/pcp/${header}" "${copy}/pxr/usd/pcp/${header}")
endforeach()
file(WRITE "${project}/CMakeLists.txt"
    "cmake_minimum_required(VERSION 3.28)\n"
    "project(PropertyHeaderIdentity LANGUAGES NONE)\n"
    "add_library(pcp INTERFACE IMPORTED)\n"
    "set_target_properties(pcp PROPERTIES INTERFACE_INCLUDE_DIRECTORIES \"${copy}\")\n"
    "include(\"${REPO_ROOT}/native/openusd_dotnet/cmake/PropertyPcpCompatibility.cmake\")\n"
    "openusd_configure_property_pcp_compatibility()\n")
set(configure "${CMAKE_COMMAND}" -S "${project}" -B "${build}" -G "${BUILD_GENERATOR}")
if(DEFINED BUILD_MAKE_PROGRAM)
    list(APPEND configure "-DCMAKE_MAKE_PROGRAM=${BUILD_MAKE_PROGRAM}")
endif()
execute_process(COMMAND ${configure} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Verified SDK fixture did not configure: ${output}${error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --target openusd_verify_property_pcp_headers
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Verified SDK fixture did not build: ${output}${error}")
endif()

foreach(header primIndex.h layerStack.h errors.h)
    set(target "${copy}/pxr/usd/pcp/${header}")
    file(APPEND "${target}" "\n// header-identity negative fixture\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --target openusd_verify_property_pcp_headers
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "PCP header identity mismatch")
        message(FATAL_ERROR "Modified ${header} was not rejected during build: ${output}${error}")
    endif()
    execute_process(COMMAND ${configure} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "PCP header identity mismatch")
        message(FATAL_ERROR "Modified ${header} was not rejected during configure: ${output}${error}")
    endif()
    file(COPY_FILE "${SDK_INCLUDE_ROOT}/pxr/usd/pcp/${header}" "${target}")
    execute_process(COMMAND ${configure} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Restored header identity did not configure: ${output}${error}")
    endif()
endforeach()

file(READ "${copy}/pxr/pxr.h" original_version)
string(REPLACE "#define PXR_VERSION 2605" "#define PXR_VERSION 9999" wrong_version "${original_version}")
file(WRITE "${copy}/pxr/pxr.h" "${wrong_version}")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --target openusd_verify_property_pcp_headers
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "PCP SDK version mismatch")
    message(FATAL_ERROR "Wrong SDK version was not rejected during build: ${output}${error}")
endif()
execute_process(COMMAND ${configure} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "PCP SDK version mismatch")
    message(FATAL_ERROR "Wrong SDK version was not rejected during configure: ${output}${error}")
endif()
file(COPY_FILE "${SDK_INCLUDE_ROOT}/pxr/pxr.h" "${copy}/pxr/pxr.h")
execute_process(COMMAND ${configure} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Restored SDK version did not configure: ${output}${error}")
endif()

file(REMOVE "${copy}/pxr/usd/pcp/primIndex.h")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --target openusd_verify_property_pcp_headers
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "Missing pinned PCP header")
    message(FATAL_ERROR "Missing header was not rejected during build: ${output}${error}")
endif()
file(COPY_FILE "${SDK_INCLUDE_ROOT}/pxr/usd/pcp/primIndex.h" "${copy}/pxr/usd/pcp/primIndex.h")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --target openusd_verify_property_pcp_headers
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Restored header identity did not build: ${output}${error}")
endif()
message(STATUS "PROPERTY_PCP_HEADERS_OK: exact identities checked at configure and every build")
