# Copyright (c) marcschier. Licensed under the MIT License.
cmake_minimum_required(VERSION 3.28)
function(openusd_verify_storage_admission_sdk sdk_root patch_lock)
    if(NOT EXISTS "${sdk_root}/.openusd-storage-admission.json")
        message(FATAL_ERROR "SDK storage admission requires verified installed patch provenance.")
    endif()
    file(READ "${sdk_root}/.openusd-storage-admission.json" metadata)
    file(READ "${patch_lock}" lock)
    file(SHA256 "${patch_lock}" lock_sha)
    string(TOUPPER "${lock_sha}" lock_sha)
    string(JSON recorded_sha GET "${metadata}" patchLockSha256)
    string(JSON schema GET "${metadata}" schemaVersion)
    string(JSON version GET "${metadata}" accessorVersion)
    string(JSON commit GET "${metadata}" sourceCommit)
    string(JSON expected_commit GET "${lock}" sourceCommit)
    if(NOT recorded_sha STREQUAL lock_sha OR NOT schema EQUAL 1 OR
        NOT version EQUAL 1 OR NOT commit STREQUAL expected_commit)
        message(FATAL_ERROR "SDK storage-admission patch/accessor/source identity mismatch.")
    endif()
    string(JSON count LENGTH "${metadata}" files)
    math(EXPR last "${count} - 1")
    set(verified)
    foreach(index RANGE 0 ${last})
        string(JSON path GET "${metadata}" files ${index} path)
        string(JSON expected GET "${metadata}" files ${index} sha256)
        if(IS_ABSOLUTE "${path}" OR path MATCHES "(^|[/\\\\])\\.\\.([/\\\\]|$)" OR
            NOT EXISTS "${sdk_root}/${path}")
            message(FATAL_ERROR "Missing or invalid SDK admission provenance file: ${path}")
        endif()
        file(SHA256 "${sdk_root}/${path}" actual)
        string(TOUPPER "${actual}" actual)
        if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "SDK admission file SHA256 mismatch: ${path}; expected ${expected}, observed ${actual}")
        endif()
        list(APPEND verified "${path}")
    endforeach()
    foreach(header include/pxr/usd/sdf/storageAdmission.h include/pxr/base/vt/arrayEdit.h)
        if(NOT header IN_LIST verified)
            message(FATAL_ERROR "SDK admission provenance omits required header ${header}.")
        endif()
    endforeach()
    if(NOT "lib/usd_ms.dll" IN_LIST verified AND NOT "lib/libusd_ms.so" IN_LIST verified AND
        NOT "lib/libusd_ms.dylib" IN_LIST verified)
        message(FATAL_ERROR "SDK admission provenance omits the actual SDK binary.")
    endif()
    string(JSON patch_count LENGTH "${lock}" patches)
    math(EXPR patch_last "${patch_count} - 1")
    foreach(patch RANGE 0 ${patch_last})
        string(JSON file_count LENGTH "${lock}" patches ${patch} files)
        math(EXPR file_last "${file_count} - 1")
        foreach(index RANGE 0 ${file_last})
            string(JSON path GET "${lock}" patches ${patch} files ${index} path)
            string(REPLACE "\\" "/" path "${path}")
            if(path STREQUAL "pxr/base/vt/arrayEdit.h" OR path STREQUAL "pxr/usd/sdf/storageAdmission.h")
                string(JSON expected GET "${lock}" patches ${patch} files ${index} afterSha256)
                file(SHA256 "${sdk_root}/include/${path}" actual)
                string(TOUPPER "${actual}" actual)
                if(NOT actual STREQUAL expected)
                    message(FATAL_ERROR "SDK admission header differs from exact tracked patch: ${path}")
                endif()
            endif()
        endforeach()
    endforeach()
    if(TARGET usd_m)
        foreach(property IMPORTED_LOCATION_RELEASE IMPORTED_IMPLIB_RELEASE)
            get_target_property(imported usd_m ${property})
            if(imported)
                file(REAL_PATH "${imported}" imported)
                file(RELATIVE_PATH relative "${sdk_root}" "${imported}")
                if(NOT relative IN_LIST verified)
                    message(FATAL_ERROR "SDK link target ${property} is not bound by the verified admission provenance.")
                endif()
            endif()
        endforeach()
    endif()
endfunction()

if(DEFINED STORAGE_ADMISSION_SDK_ROOT AND DEFINED STORAGE_ADMISSION_PATCH_LOCK)
    openusd_verify_storage_admission_sdk("${STORAGE_ADMISSION_SDK_ROOT}" "${STORAGE_ADMISSION_PATCH_LOCK}")
endif()
